### PR TITLE
Bumper Stickers: add location rules

### PR DESCRIPTION
**Pull request by FelicitusNeko**
## What is this fixing or adding?
Adds location access rules for Bumper Stickers' Treasure Bumper, Bonus Booster, and All Hazards locations.

## How was this tested?
Ran AP unit tests. Then generated manually a few times and reviewed the spoiler file to confirm that the behaviour is consistent with what should be happening.

## If this makes graphical changes, please attach screenshots.
n/a

### CODE REVIEW

**Comment by alwaysintreble** [comment]
As mentioned in discord already, this should really be adding tests; especially when testing is one of the claims as none of the generic tests are affected by this change. You also shouldn't be setting rules in "generate basic"

**Comment by FelicitusNeko** [comment]
I'm not sure what you mean by "adding tests". As for setting rules in `generate_basic`, I'm guessing you mean the completion condition. That was in `generate_basic` before and nobody said anything, but if it needs to be moved, I can do so.

**Comment by alwaysintreble** [comment]
https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/world%20api.md#tests

**Review by alwaysintreble — APPROVED** [review]

**Comment by black-sliver** [comment]
Tests failing. So either tests bad or code bad.
If you need help figuring things out, I think talking over it in Discord is easier.

**Comment by FelicitusNeko** [comment]
Definitely bad tests. I am absolutely not practiced at writing unit tests. I'll let you know as soon as I can set some time for this.

**Comment by black-sliver** [comment]
`assertAccessDependency` is a rather complex test and not always the best approach. It will test that the listed locations are only ever accessible with the listed items, but assumes that everything else does not depend on those items.

In your case, you could just collect items and check that the expected latest location is accessible, but the next isn't, using 

```python
items = self.get_item_by_name("Treasure Bumper")
# some kind of loop, doing
self.collect(items[i])
self.assertTrue(self.can_reach_location(locations[i]))
self.assertFalse(self.can_reach_location(locations[i+1]))
```

**Comment by black-sliver** [comment]
Test still failing. If you run them in pycharm, you can inspect it, or you could use subtests or a custom failure message to get a better output. i.e. assertTrue(something, "{x+1} couldn't be reached in {x}")

**Comment by FelicitusNeko** [comment]
Sorry for taking so long, but it works now.

**Review by black-sliver — APPROVED** [review]
Assuming the changed rules are actually correct, lgtm

**Pull request merged**
