### PR TITLE
Add generic multiworld tracker, move lttp multiworld tracker

### PR DESCRIPTION
**Pull request by freyacodes**
(Rewritten because of change in scope)

This relates to the discussion in #1477

## What is this fixing or adding?
* Move existing multitracker to a new path
* Add a new generic multiworld tracker based on the original
* Add a dynamic navigation menu

The navigation menu can support multiple multitrackers. It will only appear if there are games present with a specific multitracker available (or if you navigated to one of the specific ones). 

## How was this tested?
This has been tested by opening the multiworld trackers with and without ALttP worlds. No gameplay was attempted. This PR is based on the latest revision of `main` as of this writing.

## If this makes graphical changes, please attach screenshots.
<details> 
<summary>Screenshots</summary>

image
image

</details>

### CODE REVIEW

**Comment by Berserker66** [comment]
Commented on the issue why this will not be merged in its current incarnation.

**Comment by LegendaryLinux** [comment]
As mentioned in https://github.com/ArchipelagoMW/Archipelago/issues/1477, I think the LttP specific code should be removed, not embraced.

**Comment by Berserker66** [comment]
This now has conflicts in the js file

**Review by Berserker66 — APPROVED** [review]
cleared the conflict, fixed LttP not tracking at all, fixed pep8-ness, tested.
Since this now includes my code, it should be reviewed and tested by another maintainer though.

**Comment by LegendaryLinux** [comment]
I'll tinker with this sometime this week. I think the answer is to adjust the header to display a hamburger menu when the screen layout is taller than it is shorter, and have that button be clickable to reveal the menu.

**Comment by Berserker66** [comment]
I'll merge it for now, as I want to test it on the test server and it should be functional. Obviously feel free to PR in style upgrades later.
(Currently the tracker is LttP only and broken, so this PR is a clear upgrade)

**Pull request merged**
