### PR TITLE
WebHost: Round percentage of checks, fix possible 500 error

### PR DESCRIPTION
**Pull request by remyjette**
## What is this fixing or adding?

* Round the percentage of total checks done instead of truncating to an int

  Playing the Inscryption beta test, the world has exactly 100 checks and thanks to truncating and floats, sometimes they wouldn't match which was bothering me:

  image

* Don't return a 500 error if a multiworld has no locations

  If the multiworld has no locations at all, the summary row added in #1965 would cause a divide-by-zero and return a 500 error. While a multiworld with 0 locations isn't really a real use case, I still don't like returning 500 errors.

## How was this tested?

Ran WebHost.py locally

## If this makes graphical changes, please attach screenshots.

image

### CODE REVIEW

**Comment by LegendaryLinux** [comment]
I approve of the concept of this change, though I'm not familiar enough with the Jinja to make an educated assessment.

**Comment by Berserker66** [comment]
the | operator works similar to a unix command line, it "pipes" the left stuff further with that modification. So in this case the number is rounded and then converted to an integer.

**Comment by LegendaryLinux** [comment]
Ah, okay. Seems good to me then, though I have not tested it myself.

**Review by black-sliver — COMMENTED** [review]
I'm wondering if the flooring (i.e. int, not round) was intentional so it wouldn't show 100% unless you really have 100%?

Other than that, it might be nicer to move some processing from jinja to python (i.e. pass in the data differently), but i think reworking that is probably out of scope for this PR.

**Comment by remyjette** [comment]
> I'm wondering if the flooring (i.e. int, not round) was intentional so it wouldn't show 100% unless you really have 100%?

Maybe, but I feel like rounding rather than truncating is still more intuitive to non-programmers

If someone sees 299/300 and then percent 100, I'd expect them to say "oh okay not every check is done but the percentage of checks is rounded, makes sense, that's what the raw numbers to the left are there for"

Whereas seeing 57/100 show 56% tends to make heads explode for folks who don't understand IEEE 754 floats - it _looks_ like a bug.

I guess we could say "round except if it would make it 100% with checks done != total locations" but that seems messy to me

**Comment by black-sliver** [comment]
Could also do multiply first and then do integer division to avoid the pesky float errors

**Comment by LegendaryLinux** [comment]
What if we rounded the percentage to two decimap places? Then we could give a more accurate representation without taking up too much space.

**Comment by remyjette** [comment]
> What if we rounded the percentage to two decimal places? Then we could give a more accurate representation without taking up too much space.

Here's what that would look like:

image

I'm happy to swap this PR to that if folks prefer it.

**Comment by LegendaryLinux** [comment]
I like it. Others?

**Comment by BootsinSoots** [comment]
I feel like two decimal places is the appropriate number. People stop paying attention after the 2nd and this is still intuitive to people even if they struggled with mathematics

**Review by LegendaryLinux — APPROVED** [review]

**Review by LegendaryLinux — CHANGES_REQUESTED** [review]
Let's go with the two decimal places and I'll approve and merge.

**Comment by remyjette** [comment]
> Let's go with the two decimal places and I'll approve and merge.

Done. I've switched from using `round()` to `"{0:.2f}".format` as otherwise 0 checks would be `0.0` and I didn't like the inconsistency of 1 decimal in some places but two decimals in others. If that behavior is considered desirable I can always swap it back

Also made more sense to me to just always do the rounding in the template as it's a presentation concern so probably should be in the template and that way we dont need the `"{0:.2f}".format` in multiple spots in tracker.py.
In addition, doing it in the template means we don't have to special case spectator slots with no locations adding `.0`s everywhere in tracker.py to make things floats, because again I didn't like the inconsistency that that just showed as `100` while a completed slot showed as `100.00`

**Comment by LegendaryLinux** [comment]
I was all ready to approve, but then I decided to test things.

image

**Comment by remyjette** [comment]
> I was all ready to approve, but then I decided to test things. The LttP tracker gives too many decimals.
> 
> image
> 

Crap. Thanks for catching that... I'll fix the lttp tracker and double check the Factorio tracker as well tomorrow.

**Comment by remyjette** [comment]
Fixed. Screenshots of all three multitrackers:

Generic

image

Lttp:

image

Factorio: 

image

**Comment by remyjette** [comment]
And, fixed 
image

**Review by LegendaryLinux — APPROVED** [review]

**Pull request merged**
