### PR TITLE
The Messenger: use the new region helpers

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
Having The Messenger use the new region management helpers instead of its own custom implementation

## How was this tested?
Just the unit tests, though they're thorough.

### CODE REVIEW

**Comment by Berserker66** [comment]
why does this make further changes to BaseClasses?

**Comment by alwaysintreble** [comment]
The original version of that was short-sighted and it misses my use case where you don't provide names for any of the entrances. Should I do that as a separate PR?

**Comment by Berserker66** [comment]
... you leave me speechless.

**Comment by ThePhar** [comment]
If we're making more changes to core, let's do those in a separate PR first.

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
