### PR TITLE
SNIClient: log exceptions and keep task alive

### PR DESCRIPTION
**Pull request by beauxq**
## What is this fixing or adding?

I think this is a better solution to this problem:
https://github.com/ArchipelagoMW/Archipelago/pull/3404

To the user it displays the "An error occurred..." message.
In the text file log, it gives the full stack trace.
It allows the `game_watcher` task to continue.

## How was this tested?

In `snes_read` I put:
```python
if random() < 0.05:
    return None
```

and in Super Metroid's client I un-handled the `None` value of the first `snes_read` so it would throw an exception.

I saw the "An error occurred..." message in the client window,
and I looked in the text log and saw full stack trace,
and the client was able to continue playing.

### CODE REVIEW

**Comment by NewSoupVi** [comment]
I also think this solution has some downsides, for example, if someone carelessly does

`if snes_read(...)`

then this code will happily run even in case of `None` thanks to the falsyness of `None`

I imagine there are other scenarios in which `None` can go "accidentally unhandled" since I imagine most reads are compared. Maybe a lot of those cases aren't so bad, but I do think the *design* of having an *exception* that must be handled is cleaner - It just probably breaks a lot of clients which is bad

**Comment by beauxq** [comment]
> I also think this solution has some downsides, for example, if someone carelessly does...

That's not a downside to this solution because if that's a problem, it's a problem before this solution is applied.

This is about fixing a specific problem of the `game_watcher` task dying and the user being unaware that it has died.
You seem to be thinking about a different problem.

To address that problem, we could return a sentinel that is not falsy. But that's irrelevant to this PR.
This PR is an improvement no matter whether we change the error sentinel or even if we decide that throwing an exception is better.

**Comment by NewSoupVi** [comment]
That's fair, it was specifically in reference to 3404 and I prefer 3404's approach generally, but you're right that on its own & considering what it actually does, this PR is fine

**Review by black-sliver — APPROVED** [review]
Since there was no decision on the exception-less snes.read, and silently dying game_watcher is an actual problem, I believe we should merge this.

Why this and not 3404? I believe that the output provided here is less intrusive for something that is effectively only a warning once the game watcher continues to run.

**Comment by Silvris** [comment]
I think it should be intrusive, players need to know there was an error that occurred and should report it to the world developer.

**Comment by black-sliver** [comment]
The error is in SNI not receiving data from the console. The world dev can't do anything about that

**Comment by Silvris** [comment]
But this will catch exceptions that are not just SNI receiving data, it doesn't filter to only those exceptions. Arguably, you could even say the world dev should be handling those situations anyways, since the typing of `snes_read` is `bytes | None`.

**Comment by black-sliver** [comment]
Yeah, I understand.

I am assuming here that if the game never connects and the UI says "check the log" it'll be reported to the world, while a one off read error will be read as a warning by the user. But only time will tell and if the solution is not good enough, we can still rework it.

**Comment by beauxq** [comment]
I've also been doing a little work towards a new snes read interface, that can more safely not require as much error handling from the world dev.

**Comment by beauxq** [comment]
```python
class SubversionMemory(Enum):
    game_mode = Read(WRAM_START + 0x0998, 1)
    send_queue = Read(SRAM_START + 0x2700, 8 * 127)
    send_queue_r_count = Read(SRAM_START + 0x2680, 4)
    recv_queue_w_count = Read(SRAM_START + 0x2602, 2)

...

class SubversionSNIClient(SNIClient):
    def __init__(self) -> None:
        self.snes_reader = SnesReader(SubversionMemory, ctx)

...

    async def game_watcher(self, ctx: "SNIContext") -> None:
        ...

        # This is the 1 and only place where reading happens in game_watcher,
        # so only 1 place to check for the read error.
        snes_data = await self.snes_reader.read()
        if snes_data is None:
            snes_logger.info("error reading from snes")
            return

        ...

        # This is just getting the memory that was read at the top of game_watcher
        gamemode = snes_data.get(SubversionMemory.game_mode)
```

**Comment by beauxq** [comment]
@NewSoupVi  Since you raised a concern about this:

There is a PEP currently in the works for new `Sentinel` values in Python.
and your concern about accidentally interpreting it as `bool` has come up,
(someone else expressing your concern: https://discuss.python.org/t/pep-661-sentinel-values/9126/167 )
but so far it looks like they're not planning on allowing it to raise an exception.

So if they don't change their mind, even though there would be a new sentinel pattern in Python,
we would still have to make our own custom sentinel (that doesn't have the same support from IDEs and tools)
to raise an exception in `__bool__`
I hope they change their mind so we can get better help from tools for this error checking.

**Pull request merged**
