### PR TITLE
The Witness: Fix extremely late crash when Nothing items exist

### PR DESCRIPTION
**Pull request by NewSoupVi**
In the area hint code, I forgot to check `item is None` before doing `item.player == world.player` in a couple of places. This caused an unnecessary crash when Nothing items exist.

Tested: New unit test *(Edit: That is no longer part of the PR)*

### CODE REVIEW

**Comment by alwaysintreble** [comment]
i disagree with this on principle. there should be no unfilled locations when fill is finished. #2830

**Comment by NewSoupVi** [comment]
> i disagree with this on principle. there should be no unfilled locations when fill is finished. #2830

Idk how to respond to that. Makes sense, I guess. Witness is fine with unfilled locations and right now they're still "a thing" so

**Comment by NewSoupVi** [comment]
Simplified the change & decided to get rid of the unit test.
It's now one additional line that protects against this for now and wouldn't cause problems in the future
Maybe that's less controversial, iono

**Review by Exempt-Medic — APPROVED** [review]
It's one line. I would personally much rather have #2830 but this is one line, and if this gets merged first, it can just be undone in a bigger PR that undoes the other places Witness accounts for this

**Pull request closed without merging**
