### PR TITLE
LTTP: Add Master Keys option and remove option to disable Key Drop Shuffle 

### PR DESCRIPTION
**Pull request by Alchav**
## What is this fixing or adding?
- Adds Master Keys option, which condenses the small keys down to one per dungeon, or, if Universal Small Keys is on, a single universal small key (which is an advancement item and not sold in shops). Keys are no longer consumed on use. 
- Removes the Key Drop Shuffle option, instead always shuffling key drop keys. Master Keys is incompatible with Key Drop Shuffle. Instead of keeping an option that is incompatible with another, to allow an arbitrary selection of keys to be placed in their vanilla locations based on an old technical limitation, it is dropped. When you want items arbitrarily forced into particular locations, Item Plando is always there for you.

## How was this tested?
~~Has yet to be tested fully. Will be left as draft until sufficient testing has occurred.~~
Test games thus far have gone well.

### CODE REVIEW

**Comment by t3hf1gm3nt** [comment]
*Sigh*
I both love and hate what this PR is doing
On the one hand, Master Keys option looks neat
On the other hand, I am not a fan of forcing key drop shuffle to always be on
And I should not have to be forced to use item plando to replicate it being off
I've had this argument on the discord already and do not wish to rehash it again
So I will ask if there is SOME way to make Master Keys able to coexist with key drop shuffle being a toggle, even if it's some way of if one option is turned on it forces the other option off, I would rather that happen
I am also just one fool. If I'm in the minority, then so be it and I'll just grumble about being forced to interact with item plando

**Comment by Kappatechy** [comment]
I'd suggest setting Key Drop locations to give Nothing instead of Small Keys when Master Keys are on and Key Drop Shuffle is off. The only dungeon this might cause issue with is Eastern Palace, since ALL of its keys are Key Drops. A judgment call would need to be made on whether to include an Eastern Palace Master Key, or leave the vanilla Key Drops there.

**Comment by Berserker66** [comment]
I would recommend splitting off non-controversial changes into their own PR, so they can get in sooner.
Past that, the plan we posted to Discord was:
at least 1 version with KDS available
at least 1 version with KDS being default
and then at the earliest to remove it. So switching KDS to default on for the next release would be the next step there.

**Comment by eudaimonistic** [comment]
If the controversy is inevitable, it's wise to butt up against it at the earliest opportunity.  The feature itself isn't half-baked, it's just uncomfortable for people who have a long history of playing the game.  They are not more likely to accept it if we push things away from here and now.

lttp as a pure apworld is necessary for the future, and diverging from the past isn't such a bad thing along the way.  I'm not alone in saying that it's good to see anyone working on lttp at all.  We shouldn't wait to rip the bandaid.

**Comment by Kappatechy** [comment]
There are users, myself included, who are vehemently opposed to removing the Key Drop Shuffle option (i.e., forcing it always on). If the Master Keys feature REQUIRES the removal of Key Drop Shuffle as an option, it's going to be met with all the same pushback.

My recommendation, if you truly cannot find any way to make the two settings compatible, would be to make them different options on the same setting. Like how Standard/Open/Inverted is a single "world state" option, and Universal Keys were bundled into Small Key Shuffle. That works around the drama associated with removal of the KDS option, and makes Master Keys much more likely to be accepted by the community.

**Pull request closed without merging**
