### PR TITLE
SMZ3: Add "Start Inventory From Pool" to Options.py

### PR DESCRIPTION
**Pull request by dontjoome**
Add "start_inventory_from_pool" to options since total gave the okay!

## What is this fixing or adding?
Start inventory from pool, so as to not find duplicates out in the wild if people choose to use starting items

## How was this tested?
Used ArchipelagoLauncher to generate new yamls with the option, added all the Super Metroid Keys and other various items to "start inventory from pool", then generated and viewed the output log and lastly connected to the server to make sure the items were received as expected.

image
image
image
image

### CODE REVIEW

**Review by ScipioWright — APPROVED** [review]
Syntax is correct, and get_filler_item_name is defined in the world class.
Would prefer get_filler_item_name use the world's random instead of multiworld's but that's out of scope for a PR like this.

**Comment by Exempt-Medic** [comment]
@lordlou

**Review by lordlou — COMMENTED** [review]
I think setting Dungeon items in StartInventoryPool for a Non Keysanity world wont work here (will probably throw an exception) because in that case Dungeons items are prefilled and not added to the item pool.

**Comment by Exempt-Medic** [comment]
> I think setting Dungeon items in StartInventoryPool for a Non Keysanity world wont work here (will probably throw an exception) because in that case Dungeons items are prefilled and not added to the item pool.

That's just how `start_inventory_from_pool` works. (Well, unless this PR gets merged https://github.com/ArchipelagoMW/Archipelago/pull/3158). What's wrong with that? The regular start inventory option would still exist as well

**Comment by lordlou** [comment]
So you're saying if a player adds a Dungeon item in `start_inventory_from_pool` in a Non-Keysanity world, it would be expected to fail? I think it should be possible to make it work but some code would be needed to remove those items from the prefill and I think the content of `start_inventory_from_pool` would need to be modified to remove those Dungeon items (so it does throw Exception later on, when it tries to remove those from the real pool).

**Comment by Exempt-Medic** [comment]
> So you're saying if a player adds a Dungeon item in `start_inventory_from_pool` in a Non-Keysanity world, it would be expected to fail? I think it should be possible to make it work but some code would be needed to remove those items from the prefill and I think the content of `start_inventory_from_pool` would need to be modified to remove those Dungeon items (so it does throw Exception later on, when it tries to remove those from the real pool).

It's up to you if you think that that should be considered a bug. But since the items aren't in the pool when the option gets used, they can't be used in it. A player could always just use regular `start_inventory` instead if they wanted to.

**Review by lordlou — APPROVED** [review]
I'm ok with this but players have to keep in mind that Dungeon items arent in the pool for Non-Keysanity worlds, meaning that specifying a Dungeon items in StartInventoryPool in those case will fail generation:
image

**Comment by Exempt-Medic** [comment]
This has conflicts btw @dontjoome

**Comment by dontjoome** [comment]
My b, noticed email on my phone and github was missing about half the screen, that look alright? honestly hard for me to tell without being at my pc but it's late :D

**Pull request closed without merging**
