### PR TITLE
The Witness: Junk hints for Shivers, Mystic Quest and Heretic

### PR DESCRIPTION
**Pull request by NewSoupVi**
It's another one of these yay

Also modified one joke hint because it was a bit too close to looking like an actual error.

### CODE REVIEW

**Review by ReverM — APPROVED** [review]
LGTM

**Review by Exempt-Medic — APPROVED** [review]
LGTM

**Comment by black-sliver** [comment]
Are we sure we want to have "I suck" in hints? I'd be fine with it, but just double checking.

**Comment by NewSoupVi** [comment]
Is that aimed at me? If so, I don't think it's bad

**Comment by black-sliver** [comment]
It was aimed at everyone subscribed to the PR (you, medic and rever)

**Comment by Exempt-Medic** [comment]
The phrase seems good to me. It fits the general joking tone of the hints and the ocassionally meta / fourth-wall-beaking style of both the game and the other hints

**Review by black-sliver — APPROVED** [review]

**Pull request merged**
