### PR TITLE
AHIT: Fix act shuffle test fail

### PR DESCRIPTION
**Pull request by CookieCat45**
## What is this fixing or adding?
Fixes an act shuffle test failure caused by Alpine Free Roam being placed on Time Rift - Balcony

## How was this tested?
Running the act shuffle test a few times

### CODE REVIEW

**Review by Jouramie — APPROVED** [review]
LGTM

I'm just unsure why tests would fail with this placement. My understanding from the wiki is that Balcony is accessible from any act in Arctic Cruise, and requires Rock the Boat to be completed. So Rock the Boat must be accessible, and therefore Balcony and therefore Alpine Free Roam would be accessible anyway? I have not play the rando, so I must be missing something.

**Comment by Exempt-Medic** [comment]
Are the additional indirect conditions supposed to fix the other bug here? If so, you can remove the change in `Regions.py`

**Review by Exempt-Medic — APPROVED** [review]
I don't love the pattern of excluding it because it was causing test failures but it works so \*shrug\*

**Review by black-sliver — APPROVED** [review]
I don't understand any of it, but it follows the same pattern as others and fixes the issue, so I assume it's fine.

**Pull request merged**
