### PR TITLE
Tests: assign the world to WorldTestBase, and a default player field

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
new options API is a nightmare to use from tests atm. Assigns the world to the class after it's created, and sets a player field on the base for usage because I hate typing `1` in method calls. Also some docstrings and very miniscule performance improvement

## How was this tested?
how else

### CODE REVIEW

**Comment by black-sliver** [comment]
Why not leave `self.options` as-is, change WorldTestBase to a generic WorldTestBase[W] and `self.world: W` to get `self.world.options` as a correctly typed solution?

**Comment by alwaysintreble** [comment]
you still wouldn't get correct typing when accessing options that way unless you added typing to `self.world` on your test base. The base `options` can get typing to at least `PerGameCommonOptions` after the next version, which will basically be the same behavior. I posited what the actual gain would be from writing the world instead of exclusively the options, and nothing came to mind at the time, but I suppose it would add some slight convenience in my own world, so it's probably worth it.

**Comment by black-sliver** [comment]
As I said in the initial sdv pr. player=1 is confusing if the player variable is unused (in setup)

**Comment by black-sliver** [comment]
Is there a reason you didn't change AllSealsRequired to use self.world in test_shop_chest.py?

**Comment by alwaysintreble** [comment]
when i moved my world to the new options api i missed updating the tests to it. the other tests that are changing in this PR are access attributes on the world itself, not options. i already addresses all of those in my world rewrite and i'd rather not do it twice and resolve all the conflicts😓

**Review by black-sliver — APPROVED** [review]
lgtm then, not sure if we still want a peer review?

**Comment by alwaysintreble** [comment]
i think at the very least @agilbert1412 wants this if we should

**Review by agilbert1412 — APPROVED** [review]
I do have a significant number of tests that could benefit from this simplified syntax, so I like it.
Code seems good.

**Pull request merged**
