### PR TITLE
Increase Location count and Item pool count

### PR DESCRIPTION
**Pull request by Mathx2**
Increased max total locations from 100 to 500
Increased max number of revives from 10 to 50
Increased max weight for all item groups from 100 to 500

### CODE REVIEW

**Comment by Ijwu** [comment]
I can get behind increased total locations and increased revives. I don't see much of a point in increasing the weights unless you **really** want to fine tune your custom weights. They are already 0-100 implying an easy percentage for each one if you get all of them to add up to 100.

**Comment by alwaysintreble** [comment]
I'm personally very wary of these changes since this would make it theoretically possible for someone to have to open 3000 chests to get all of their locations. 50 for revives also seems incredibly high when the randomizer already makes the game significantly easier than vanilla also. As for increasing the weight numbers that actually doesn't do anything and if anything would just confuse people so I'm hard against that one. For this many locations the logic would also be incredibly borked as it could then potentially place almost 490 locations all in sphere 5.

**Comment by Mathx2** [comment]
I understand the position of not needing to increase max weight from 100 to 500.
By increasing the total number of locations from 100 to 500, you wouldn't need to open 3k chests to get the 500 locations. It would literally be the first 500 chests you open.
increasing the max revives from 10 to 50 will maintain 10% of max locations to max revives, this will maintain a sense of balance for how often you would receive a revive item.

**Comment by Berserker66** [comment]
50 max revives will tip the effect of random/random-low and such very strongly.

**Comment by alwaysintreble** [comment]
Maybe you've only played on an item pickup step of 0 but that can be set to 5 meaning that an AP location is only achieved once every 6 chests opened in the game.

**Comment by Mathx2** [comment]
yes alwaysintreble, i see what you mean now, as you said i've only played on item pickup step 0

**Comment by Alchav** [comment]
> yes alwaysintreble, i see what you mean now, as you said i've only played on item pickup step 0

You mentioned to me that you often have a lot of difficulty dying a lot and running out of locations. I'm going to mention that having a larger number of pickups between AP checks makes your game easier, as you will get more items for yourself on top of the items sent to you

**Comment by Mathx2** [comment]
I've never had a great deal of skill in this game so the fact that i die a lot isn't the problem. i was also looking at it from a number of checks RoR2 has compared to other games like alttp which has a much larger popularity

**Review by Ijwu — APPROVED** [review]

**Pull request merged**
