### PR TITLE
Pokemon Emerald: Add exhaustive list of ROM changes

### PR DESCRIPTION
**Pull request by Zunawe**
## What is this fixing or adding?

Adds a detailed list of changes made to the game via the base patch that a player might be interested in knowing. Something to link to if someone asks or is curious, but contains many small things that don't really _need_ to be covered by the game page and would probably just clutter it up.

## How was this tested?

Reading

### CODE REVIEW

**Comment by nicholassaylor** [comment]
Might this be something that you mention on the game page itself? Right now there's a section that lists some of the other changes, so maybe something to the extent of "For an exhaustive list of changes, look at ..." could be added? 

Not sure how much you want to point to this file, but I think it might be a good idea for someone who is interested in the changes, but might not be in the Discord or isn't particularly tech-savvy.

**Comment by Zunawe** [comment]
That's reasonable, but I don't know how I'd reliably link to the right version. New changes may get merged that would make the latest on GitHub newer than what the webhost can do. I don't know of a URL that links to a file in the source code at the latest release's tag. Manually updating to the next tag is something extra to remember, and isn't testable until after the release is made.

For now, this is at least putting the info in a reasonable place that can be linked to and doesn't interfere with anything. Can decide whether to move it or how to link to it in the future.

**Comment by agilbert1412** [comment]
My suggestion for this would be to follow the same pattern I've used for the Supported mods documentation in Stardew. The Archipelago webhost page links to an MD page that is on my own Github repo, instead of in Archipelago itself. This allows me to update it frequently, without waiting on core devs for months every time we need to bump up a version number without any content changes.

I believe you would probably appreciate that same freedom

**Comment by Zunawe** [comment]
I cannot update the base patch separately from the apworld, so keeping this document separate only really serves to solve this link problem. And then either the separate document needs to be updated only when the webhost is updated, or I need to remember to modify the link in a PR before the webhost updates any time changes are made.

That's not super disorganized, but what's on webhost will not always be the only version available. I may reconsider whether to put this info at the bottom of the game info page, but I still am only looking to attach the document to the apworld for now.

**Review by agilbert1412 — APPROVED** [review]

**Comment by black-sliver** [comment]
I think It's fine having the file there. Having it external means people have to potentially dig through multiple versions. Did anyone proof read this?

**Review by nicholassaylor — APPROVED** [review]
Proofread, LGTM

**Review by black-sliver — APPROVED** [review]

**Pull request merged**
