### PR TITLE
Tests: implement filler item test

### PR DESCRIPTION
**Pull request by alwaysintreble**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
A Not Implemented Error and test to force worlds to implement handling for `get_filler_item_name` instead of assuming random items

### CODE REVIEW

**Comment by Berserker66** [comment]
I disagree with this. But if this is to happen, then at least use abstractmethod https://docs.python.org/3/library/abc.html#abc.abstractmethod

**Comment by BootsinSoots** [comment]
In an effort to help provide feedback, especially on dangling PRs, this one now has merge conflicts, and may be superseded by a later PR.

**Comment by NewSoupVi** [comment]
This was previously marked as "potentially superceded by https://github.com/ArchipelagoMW/Archipelago/pull/2073", and *that* PR is now superceded by https://github.com/ArchipelagoMW/Archipelago/pull/2081.

If I'm understanding things correctly, they don't seem to do exactly the same thing. That PR just asks "does it generate with item links", but this PR asks specifically for an implementation of `get_filler_item_name`. For the record, I have been telling new world devs to add `get_filler_item_name` to their implementations on their new game PRs, because in my (limited) opinion it seems necessary. But Berserker disagrees with it being a test, so...

What do we think? Should I close this PR? It seems like it will not go anywhere unless we make a decision on it.

**Comment by BadMagic100** [comment]
If we require a member of an abstract class to be implemented, it should throw. So i agree with this implementation

**Review by silasary — APPROVED** [review]

**Pull request closed without merging**
