### PR TITLE
Core: Rename "count_exclusive" methods to "count_unique"

### PR DESCRIPTION
**Pull request by NewSoupVi**
Based on this poll https://discord.com/channels/731205301247803413/1243111773419339847/1243199985797828658

Will undraft once that poll finishes, although it's looking like everyone is unanimously on board with this change so far.

We haven't released a major stable version with the `exclusive` variants in it yet, so this change can still be made without making any aliases. Requires changing some worlds tho that have already started using these methods.

### CODE REVIEW

**Comment by NewSoupVi** [comment]
Oh it messes up some lint stuff. Will fix that in a moment

**Comment by Exempt-Medic** [comment]
You'll want to fix [this](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/bomb_rush_cyberfunk/Rules.py) too

**Comment by NewSoupVi** [comment]
Ye my b, I hadn't actually done the group functions yet

**Comment by NewSoupVi** [comment]
@Rensen3 I can't request a review from you through github so pinging you instead

**Review by TRPG0 — APPROVED** [review]
👍

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
