### PR TITLE
Fill: fix swap error found in CI

### PR DESCRIPTION
**Pull request by black-sliver**
https://discord.com/channels/731205301247803413/731214280439103580/1167195750082560121

Swap now assumes the unplaced items can be placed before the to-be-swapped item.
Unsure if that is safe or unsafe.

### CODE REVIEW

**Comment by Berserker66** [comment]
I  thought the remaining item pool is already in state, since in reverse fill they're yet to be placed into earlier spheres. IF the bug was just that it wasn't correctly in swap state, then this should be safe.

**Review by Berserker66 — APPROVED** [review]
So approving that if the above theory is correct, this should be good.  But this is one where people testing it would be nice.

**Comment by black-sliver** [comment]
The assumption that it can place all of item_pool before the to-be-swapped-out item may not be true. While this is fine for the reverse fill, because it'll swap later, I'm not sure that's always fine for swap, because swap is what should "fix" it.

Testing/comparing failures would be good and if we find issues with this, we can however filter item_pool based on reachable locations with the old swap_state (i.e. sweep without item_pool). Something like `any(location.can_fill(...) for ...)` or a simple `len()` for it to be able to continue swapping maybe.

**Comment by black-sliver** [comment]
Comparing my old set of yamls, I get
```json
{
    "success": {
      "github-com_ArchipelagoMW-Archipe_main/venv": 4920,
      "github-com_black-sliver-Archipelago_fill-swap-fix-2/venv": 4921
    },
    "failed": {
      "github-com_ArchipelagoMW-Archipe_main/venv": 80,
      "github-com_black-sliver-Archipelago_fill-swap-fix-2/venv": 79
    }
}
```

Mixing the [SM64EX yaml that fails every other seed](https://discord.com/channels/731205301247803413/731214280439103580/1109034856169611264) with others, I see a real improvement:
```json
{
    "success": {
      "github-com_ArchipelagoMW-Archipe_main/venv": 1236,
      "github-com_black-sliver-Archipelago_fill-swap-fix-2/venv": 1295
    },
    "failed": {
      "github-com_ArchipelagoMW-Archipe_main/venv": 164,
      "github-com_black-sliver-Archipelago_fill-swap-fix-2/venv": 105
    }
}
```

The failing yaml itself is not fixed by this though, only when combined with others.

**Pull request merged**
