### PR TITLE
typing, mostly in AutoWorld.py

### PR DESCRIPTION
**Pull request by beauxq**
typing, mostly in `AutoWorld.py`
includes a bug fix (that was found by static type checking)
in `get_filler_item_name`

### CODE REVIEW

**Comment by Berserker66** [comment]
this contains a bit of a stylistic choice of including `-> None`, which personally I find to be more clutter than useful. Do we want to start adding that everywhere?

**Comment by beauxq** [comment]
mypy, which is one of the most popular static type checkers, requires `-> None` in order for the function definition to be typed.

It is incapable of giving the same quality of analysis without it. So it is not just a stylistic choice.

**Comment by beauxq** [comment]
pyright also, with its most strict settings, will not emit that a return type annotation is missing when something besides `None` is returned.

**Review by Berserker66 — APPROVED** [review]

**Comment by beauxq** [comment]
I agree that it adds a lot of clutter. So I made this feature request on mypy.

https://github.com/python/mypy/issues/12695

But I don't expect it will be implemented any time soon, or maybe ever. I might anticipate the response "Explicit is better than implicit."

**Pull request merged**
