### PR TITLE
LADX: Rework in-game hints (owl statues, books)

### PR DESCRIPTION
**Pull request by threeandthreee**
## What is this fixing or adding?

This reworks the in-game hints from owl statues and books. 

Currently, the hints only target items for the LADX player and give the exact location anywhere in the multiworld. Since this doesn't tie into the Archipelago hint system, this creates a somewhat annoying need to communicate and keep track of these hints manually. These messages are also often too long and get truncated. Additionally, a full third of these hints are forced to be completely useless joke hints. Many players stop interacting with the hints entirely.

This PR changes the hint system to be closer to the upstream randomizer. The hints are now for any progression item of the multiworld, filtered to the ones located in the current world. Instead of giving the exact location of items, the general region in LADX is given instead (such as Tal Tal Heights or Bottle Grotto). In practice this creates a fun balance of useful and vague that makes the hints fun to interact with but not essential.

I found it unnecessary to force any junk hints because there tends to be more than enough undesirable progression items in the pool. Just from LADX there are a lot of rupees and seashells.

## How was this tested?

Tested in a few multiworlds to see that the hints generated as intended.

### CODE REVIEW

**Comment by ScipioWright** [comment]
Have you discussed this change with other LADX players in the AP community?

**Comment by threeandthreee** [comment]
I havent yet, got a little ahead of myself :)

I'll bring it up.

**Comment by NewSoupVi** [comment]
This might be jumping the gun slightly, as a PR to allow creating hints for off world items is currently open: https://github.com/ArchipelagoMW/Archipelago/pull/3523

Not sure when that will be in tho, so it makes sense to change this world work around the current limitations rather than making you wait for that PR to make it in.

I would definitely "keep the old code around" as well though, if that makes sense

**Comment by threeandthreee** [comment]
This was the wrong approach, closing

**Pull request closed without merging**
