### PR TITLE
WebHost: Add a summary row to the Multiworld Tracker

### PR DESCRIPTION
**Pull request by remyjette**
## What is this fixing or adding?

Implements suggestions from the generation-suggestions channel to add a summary row to the Multiworld tracker, so games that aren't the big async can see total number of checks/worlds completed easily.
- https://discord.com/channels/731205301247803413/1124186131911688262
- https://discord.com/channels/731205301247803413/1109513647274856518

## How was this tested?

Generated a one player game, made sure the footer matched exactly. Waited a few minutes to ensure it updated with the main row. Generated a two player game, made sure things added up, made sure that the footer row continued to update as items were found.

### CODE REVIEW

**Comment by ThePhar** [comment]
Requested a review from Farrak for front end changes, but back end changes look fine. I give my approval for those.

**Comment by remyjette** [comment]
I just noticed in a game I'm running on my own webhost that the summary row is still there on the multiFactorioTracker, and is mis-aligned due to the additional columns in that tracker.

Presumably it's similarly off for the lttp multi tracker, so I need to look into this.

**Review by LegendaryLinux — CHANGES_REQUESTED** [review]
I updated the JS to include a docblock and remove as much jQuery as possible. I really hate jQuery.

Let me know when you get the factorio tracker sorted.

**Comment by remyjette** [comment]
> I updated the JS to include a docblock and remove as much jQuery as possible. I really hate jQuery.
> 
> Let me know when you get the factorio tracker sorted.

Thanks!!

And I just updated it to not render the summary row for game-specific multi trackers.

**Review by LegendaryLinux — APPROVED** [review]

**Pull request merged**
