### PR TITLE
Ror2: Add progressive stages option

### PR DESCRIPTION
**Pull request by kindasneaki**
## What is this fixing or adding?

This creates progressive items for the Stage items to help with confusion on which one is needed to progress to the next set of environments. This also adds an options to toggle stages off for the people that don't like the feature.

## How was this tested?

Tested with looking at a few logs to make sure the items showed up and did a run with the new client to make sure they work correctly.

### CODE REVIEW

**Review by benny-dreamly — APPROVED** [review]

**Review by nicholassaylor — CHANGES_REQUESTED** [review]
Looks like this PR has merge conflicts now, should probably handle that

**Comment by kindasneaki** [comment]
> Looks like this PR has merge conflicts now, should probably handle that

Thanks for letting me know. I don't really check these very often.

**Review by remyjette — APPROVED** [review]
Code changes look good to me. I tested generating with
* `require_stages: false`,
* `require_stages: true` and `progressive_stages: false`
* `require_stages: true` and `progressive_stages: true`

All generated fine and looking at the spoiler log they created the right items.

I tested each of those slots since the client 1.3.5 states it supports progressive stages. The first two worked properly. The third allowed me to continue to the next stage even without a `Progressive Stage` item. However given that that would be a client bug and any fix wouldn't go in this repo, marking approve here

**Comment by kindasneaki** [comment]
> Code changes look good to me. I tested generating with
> 
> * `require_stages: false`,
> * `require_stages: true` and `progressive_stages: false`
> * `require_stages: true` and `progressive_stages: true`
> 
> All generated fine and looking at the spoiler log they created the right items.
> 
> I tested each of those slots since the client 1.3.5 states it supports progressive stages. The first two worked properly. The third allowed me to continue to the next stage even without a `Progressive Stage` item. However given that that would be a client bug and any fix wouldn't go in this repo, marking approve here

I am not getting this result in the client for progressive items. Did you perhaps accidentally have a progressive stage somehow?

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
