### PR TITLE
Tests: modern PEP8-ify core test modules and methods

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
makes core test modules and methods `snake_case`. also adds docstrings to most of the general tests

### CODE REVIEW

**Comment by alwaysintreble** [comment]
> * Should the "TestBase.py" module somehow be marked as deprecated?

I'm not sure how to do this. Using `Utils.deprecated` causes test imports to be seen as failures (as does warnings.warn). logging.warning works but it's an incredibly easy to miss output when running tests.

**Comment by black-sliver** [comment]
The proper way is to `warning.warn("TestBase was renamed to bases", DeprecationWarning)` on Module level. In PyCharm this shows up as
> import test.~~TestBase~~

and if you hover that, it'll show the message.

Then with the next release we write the name change into release notes (and/or ping world maintainers), then with the release after that we'll remove the old name and get test failures.

**Comment by alwaysintreble** [comment]
> The proper way is to `warnings.warn("TestBase was renamed to bases", DeprecationWarning)` on Module level. In PyCharm this shows up as
> 
> > import test.~TestBase~
> 
> and if you hover that, it'll show the message.
> 
> Then with the next release we write the name change into release notes (and/or ping world maintainers), then with the release after that we'll remove the old name and get test failures.

**Review by black-sliver — APPROVED** [review]
Thanks!
Gotta merge this before we break it again :sweat_drops:

**Pull request merged**
