### PR TITLE
SC2 Documentation: Fix the page titles

### PR DESCRIPTION
**Pull request by Ziktofel**
## What is this fixing or adding?
Fix documentation title

## How was this tested?
Documentation-only

## If this makes graphical changes, please attach screenshots.
nothing important, just text changes

### CODE REVIEW

**Comment by MaxTousss** [comment]
PR #3031 also proposes these modifications. However, it is true that it is technically outside of its scope XD

**Comment by neocerber** [comment]
PR #3031 also proposes these modifications. However, it is true that it is technically outside of its scope XD

**Review by Exempt-Medic — APPROVED** [review]
LGTM

**Review by MatthewMarinets — APPROVED** [review]
Looks solid, would slightly reduce the scope of #3031

**Review by silasary — APPROVED** [review]

**Review by nicholassaylor — APPROVED** [review]
LGTM, seconding on reducing scope on other PR

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
