### PR TITLE
MultiServer: add create_as_hint silent mode

### PR DESCRIPTION
**Pull request by Berserker66**
This might be useful to @dewiniaid and @ThePhar especially.

### CODE REVIEW

**Review by black-sliver — COMMENTED** [review]
Have not tested yet, but

**Comment by dewiniaid** [comment]
The latest HK client has largely mitigated this by now only hinting items after you leave the scene, and only if the items are not obtained and are progression or useful.  This cuts down on hints for where to find 5 rupees, as well as hints for the check you are literally about to get 5 seconds after it is hinted.

The problematic bit here isn't when the shops are initially visited (though hiding the initial hint output _may_ be useful here) but is when a player much later on does !hint and gets a long list of hints that aren't really unimportant.

**Comment by Berserker66** [comment]
well, you can now do the filtering and prevent all printing to chat. Eventually I want to look into ways to make !hint for the text client and derivates obsolete with a Hint tab or such, but that's a topic for another PR.

**Comment by Berserker66** [comment]
Well, if no client/world wants to actually use it, then better not clutter the server with unused code. Unless someone wants this this should then be closed.

**Comment by Ijwu** [comment]
> Well, if no client/world wants to actually use it, then better not clutter the server with unused code. Unless someone wants this this should then be closed.

Ok.

**Pull request closed without merging**
