### PR TITLE
Pokemon Emerald: Add some warnings to option descriptions

### PR DESCRIPTION
**Pull request by Zunawe**
## What is this fixing or adding?

Adds some notes to a few option descriptions to help clarify player expectations.

Addresses #3945

## How was this tested?

Reading

### CODE REVIEW

**Review by ScipioWright — APPROVED** [review]
Consider stating how many locations they add in the description -- it's helpful in decision making for stuff like this.

**Comment by Zunawe** [comment]
Yeah, I was considering that when doing this, but figured it's not the point of this particular PR. I'll have to settle on the specific format I find most appealing. But it is on my mind as something that's probably helpful.

**Review by NewSoupVi — APPROVED** [review]

**Comment by nicholassaylor** [comment]
Is this meant to close #3945 ?

**Comment by Zunawe** [comment]
Yeah, I edited the original post a couple seconds after creating it to include it

**Pull request merged**
