### PR TITLE
Various Worlds: use / explicitly for pkgutil

### PR DESCRIPTION
**Pull request by qwint**
## What is this fixing or adding?
patches various worlds to use "/" explicitly instead of os.path.join for pkgutil

to any world dev who wants to pr this change yourself just suggest removing your world's change / say so and I will remove

## How was this tested?
wasn't

### CODE REVIEW

**Review by Silvris — APPROVED** [review]

**Comment by Zannick** [comment]
What's the benefit of this?

**Comment by qwint** [comment]
https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data
```
The resource argument should be in the form of a relative filename, using / as the path separator.
```

black sliver pointed out the docs are very explicit that it is joined by a forward slash and not expected to change per OS

**Comment by beauxq** [comment]
I think I've seen a situation where `os.path.join` breaks things for `pkgutil.get_data`
I don't remember the exact circumstances.

**Comment by qwint** [comment]
FYI @hatkirby @KonoTyran @GodlFire this touches your world(s)

**Comment by hatkirby** [comment]
LGTM for Lingo

**Comment by GodlFire** [comment]
LGTM for Shivers

**Comment by KonoTyran** [comment]
LGTM minecraft

**Comment by threeandthreee** [comment]
lgtm for ladx

**Comment by qwint** [comment]
that's affirmation from all world maintainers for worlds this touches

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
