### PR TITLE
Adjusts Whitespaces in the Plando Doc to be able to be copied directly

### PR DESCRIPTION
**Pull request by palex00**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
This is adding whitespaces to the example block of the Plando Guide so copying the textblock makes the Plando work correctly. Right now when this is copied, it will silently not work. After the update, it will work.

Also removed whitespaces from the first codeblock because Exempt-medic said it's actually wrong how it is right now. https://discord.com/channels/731205301247803413/731205301818359821/1282065216590581792

## How was this tested?
-

## If this makes graphical changes, please attach screenshots.
-

### CODE REVIEW

**Comment by Exempt-Medic** [comment]
Should probably indent the final example while you're at it

**Comment by palex00** [comment]
accidentally undid the first change with the 2nd. So "Uggh" (I didn't think it'd show up here) has both changes in it.

**Review by Exempt-Medic — APPROVED** [review]
LGTM!

**Review by ArchooD2 — APPROVED** [review]
`LGTM`

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
