### PR TITLE
Stardew Valley: Fix Crimsonfish region

### PR DESCRIPTION
**Pull request by agilbert1412**
## What is this fixing or adding?
This has apparently been overlooked ever since 3.x.x (update that added fishsanity). Not sure how nobody noticed it until now lol.

The crimsonfish must be caught from the east pier on the beach (the region is called "Tide Pools), which requires the bridge repair to reach. It was in the "Beach" region instead.

## How was this tested?
I added a test for the fish that are behind a "not-always-reachable" region, including the crimsonfish, and saw it failing, before simply moving the fish to the correct region.
Ran the other tests too of course

### CODE REVIEW

**Comment by Exempt-Medic** [comment]
Would son of crimsonfish not require the same changes?

**Comment by agilbert1412** [comment]
Test failure is OC2 and unrelated to the PR

**Review by Exempt-Medic — APPROVED** [review]
Changes LGTM and make sense. The unit test passes and plando'ing the Beach Bridge onto Crimsonfish now properly causes a generation failure.

**Comment by Berserker66** [comment]
apparently this has conflicts now.

**Comment by agilbert1412** [comment]
I have clearly messed up something with git trying to fix the conflict.... But I think it's fixed now. Not sure what to do about the 700 commits and authors that are now in the history of the PR, but they aren't in the files changed at least...

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
