### PR TITLE
Core: add layer for patches that don't use `Patch.py`

### PR DESCRIPTION
**Pull request by beauxq**
## What is this fixing or adding?

as discussed https://github.com/black-sliver/apbpatch/pull/2 and various other places

This adds a layer in the patch heirarchy for a patch file that is not applied with our `Patch.py`

I think Mystic Quest falls into this category, I'm not sure what else.

- `APContainer`: something that is not necessarily a patch
- `APPatch`: a patch that is not necessarily applied with `Patch.py`
- `CreateRomInterface`: an `APPatch` that is is applied with `Patch.py` (previously `APPatch`)
- (APPP to be inserted here)
- `APDeltaPatch`: all the things

## How was this tested?

~~none yet~~
generated, patched, played through a game of Zillion

### CODE REVIEW

**Comment by beauxq** [comment]
I'm not sure about the name `CreateRomInterface`...
Should it change `APPatchInterface`?

**Comment by black-sliver** [comment]
Any reason not to call it APAutoPatch if it's supposed to be picked up automatically by patch?

**Comment by beauxq** [comment]
I like `Interface` because it is abstract and users will need to implement that `patch` function.

**Comment by beauxq** [comment]
`AutoPatchInterface`?

**Comment by black-sliver** [comment]
~~`Archipelago.abc.AutoPatch`~~ Of the suggest ones, I think I prefer AutoPatchInterface. While some libs use the `I` prefix, it doesn't really look pythonic to me.

**Comment by beauxq** [comment]
@Alchav FFMQ This should just add a key to your manifest to indicate that this is a patch file.

**Comment by beauxq** [comment]
What other games have a patch file that isn't `APDeltaPatch`?

**Comment by Silvris** [comment]
> What other games have a patch file that isn't `APDeltaPatch`?

FFMQ, OoT (which I think is already accounted for here), Adventure (which is also on APContainer).

**Comment by beauxq** [comment]
@JusticePS @espeon65536 Adventure and OoT
same small change to review

**Comment by beauxq** [comment]
I'm not sure why Adventure uses `metaclass=AutoPatchRegister`. It doesn't look like it would work where that registry is used. (It doesn't define the `patch` method.)

**Comment by JusticePS** [comment]
> Adventure and OoT same small change to review
No problems here

**Comment by black-sliver** [comment]
While maybe a bit confusing to people that are not sure which one to ~~copy~~ inherit from, I think the code looks good. I really would like to get this in soon(and ProcedurePatch soon after). Hopefully espeon can test OoT, lordlou can test ffmq, and then I'll also compare output files to "my" expectations. Testing basically just means rolling a seed and starting it.

**Comment by beauxq** [comment]
@Alchav and @espeon65536 
In addition to looking at the small changes to your world code,
make sure that this sounds right for your situations:
(from the docstring of `APPatch`)

> Your implementation should inherit from this if your output file
    represents a patch file, but will not be applied with AP's `Patch.py`

**Comment by black-sliver** [comment]
Hm, couple of things:
* Factorio says `compatible_version: 5`, `version: 6`, `procedure: None/absent`. I think this is correct, but compatible 6 would also be valid here.
* As it is now, Alttp (and all other Delta) are wrong. They say `procedure: "custom"`, but should either be `procedure: None` to enforce old behaviour, or `procedure: [["apply_bsdiff4", ["delta.bsdiff4"]]]` (which will be part of PP) to enforce new behaviour. I think this PR should set it to None and then PP should replace that.
* Zillion sets `compatible_version: 5`, `version: 6`, `procedure: "custom"`, which is not correct, I think. It should set `compatible_version` to 6, because `custom` is required, but did not exist in 5.

**Review by black-sliver — APPROVED** [review]
Thanks, I think this looks good now.

With a v5 Patcher:
- Factorio now gives: "could not open patch file" (i.e. not a valid (delta) patch)
- Lttp still works (falls back to detecting delta.bsdiff4)
- Zillion gives "Incompatible version 6"

Per proposed v6 Spec
- Factorio would be detected as non-patch by not having procedure nor bsdiff file
- Lttp would use the fall-back code path using bsdiff by detecting the bsdiff file
- Zillion either needs "custom" implementation, or has "custom not supported"

**Comment by black-sliver** [comment]
Espeon posted in discord and OoT seems to still work in AP, I don't think we broke that now (but read at the very end), and I don't think there is an alternative patcher for OoT implemented unless you unpack it and apply zpf by "hand".

Applying patch from this branch with Patch.py in this branch:
- Factorio gives "No Handler for ..."
- Alttp works
- Zillion works

Applying patch from this branch with Patch.py in main:
- Factorio as above
- Alttp works
- Zillion gives File (version: 6) too new for this handler (version: 5), which is correct
- Adventure and OoT probably also give that error now, which should be fine, I hope

**Pull request merged**
