### PR TITLE
OSRS: Add missing indirect conditions

### PR DESCRIPTION
**Pull request by Mysteryem**
## What is this fixing or adding?

All entrances to Cooks_Guild and Crafting_Guild and all entrances using special logic for canoes were missing indirect conditions for the regions that the cooking, crafting and woodcutting skill rules require access to.

## How was this tested?

Ran the spheres test in #3924 multiple times and ran many generations with my own implementation of a missing indirect condition checker (prints a stacktrace on a recursive can_reach(region) call if the indirect condition is missing).

### CODE REVIEW

**Comment by Mysteryem** [comment]
@digiholic 

The alternative would be removing all the existing registrations of indirect conditions and setting `explicit_indirect_conditions = False` on the world class.

**Review by Exempt-Medic — APPROVED** [review]
Changes LGTM and my own checking for missing indirect conditions didn't show any more

**Review by digiholic — APPROVED** [review]
Man I can never fully wrap my head around these indirect connections, I always feel like I miss something. I didn't think of all of these training regions being indirect connections! Thanks for sorting all of these out.

**Review by NewSoupVi — APPROVED** [review]

**Comment by NewSoupVi** [comment]
Really wonder if this specific implementation might not have so many indirect conditions at this point that `explicit_indirect_conditions: False` might just be *faster*. It's worth a shot I think. Anyway, merging this for now

**Pull request merged**
