### PR TITLE
Shivers: Renaming for clarity and consistency

### PR DESCRIPTION
**Pull request by korydondzila**
## What is this fixing or adding?
This is strictly naming and clarity updates, no logic.
There is a companion [Shivers randomizer client PR](https://github.com/GodlFire/Shivers-Randomizer-CSharp/pull/31).

@GodlFire needs to review

### CODE REVIEW

**Comment by GodlFire** [comment]
I have reviewed the code of this PR as well as the companion Shivers Randomizer Client PR. The changes look correct.

I have also generated and played through a seed, everything appears to be functioning correct: https://archipelago.gg/room/6MWN4d_sSxORc5CMvxe3pw

**Review by GodlFire — APPROVED** [review]
World Maintainer:

I have reviewed the code of this PR as well as the companion Shivers Randomizer Client PR. The changes look correct.

I have also generated and played through a seed, everything appears to be functioning correct: https://archipelago.gg/room/6MWN4d_sSxORc5CMvxe3pw

**Review by agilbert1412 — APPROVED** [review]
Looks like this is all naming. If the world maintainer confirmed that the client app will be fine with that, then LGTM

**Review by black-sliver — APPROVED** [review]
Approved and tested by the world maintainer.

**Pull request merged**
