### PR TITLE
HK: speed up collect (a bit)

### PR DESCRIPTION
**Pull request by qwint**
## What is this fixing or adding?
speed up collect, will be obsolete after #3786

considered just indenting it instead but whitespace changes are annoying

## How was this tested?
ran some tests (i haven't committed yet) and they ran faster

### CODE REVIEW

**Review by Exempt-Medic — APPROVED** [review]
This is correct, for now.

**Review by ScipioWright — APPROVED** [review]
I'd rather the indent too but you've addressed that so lgtm

**Comment by NewSoupVi** [comment]
Ok so yes please indent that, otherwise this is good of course

**Review by NewSoupVi — APPROVED** [review]
<3

**Pull request merged**
