### PR TITLE
WebHost: Fix setup guide link not working for games with special characters

### PR DESCRIPTION
**Pull request by NewSoupVi**
"Mario & Luigi - Superstar Saga" contains the character `&`.

The DOM element for it on the "Archipelago Guides" page has the id `Mario%20%26%20Luigi%20Superstar%20Saga`. This is because tutorialLanding.js line 26 uses `encodeURIComponent(game.gameTitle)`, which escapes special uri characters.
image

However, the link on the supported games page goes to `/tutorial/#Mario%20&%20Luigi%20Superstar%20Saga`.
image

This is because `supportedGames.html` just directly uses `#{{ game_name }}`.

This causes the autoscroll down to the correct setup guide not to work when clicking on this link.

Using `#{{ game_name|urlencode }}` makes it work as expected.

### CODE REVIEW

**Comment by NewSoupVi** [comment]
Not actually sure whether this is the best way to do this, but it does work.

**Review by remyjette — APPROVED** [review]
Looks good to me! Tested and it works as expected

**Comment by black-sliver** [comment]
I think 
`url_for("tutorial_landing", _anchor=game_name)`
would be the proper way to do this

**Comment by remyjette** [comment]
`url_for` doesn't encode the url, so that would give the same bug as we have today.

To use `_anchor` we would have to do something like
```
            {% set anchor = game_name|urlencode %}
            <a href="{{ url_for("tutorial_landing", _anchor=anchor) }}">Setup Guides</a>
```

or call urllib.parse.quote in Python, before sending it to jinja

**Comment by NewSoupVi** [comment]
> > `url_for` doesn't encode the url, so that would give the same bug as we have today.
> 
> To use `_anchor` we would have to do something like
> 
> ```
>             {% set anchor = game_name|urlencode %}
>             <a href="{{ url_for("tutorial_landing", _anchor=anchor) }}">Setup Guides</a>
> ```

Confirmed that this is correct, in which case I would rather keep this PR as is.

**Comment by black-sliver** [comment]
`url_for(..., _anchor = game_name | urlencode)`

**Comment by remyjette** [comment]
Huh. For some reason I didn't think you could use filters inside an argument list. TIL. Yeah, that works. Do that.

**Comment by NewSoupVi** [comment]
> `url_for(..., _anchor = game_name | urlencode)`

Sure, I guess I didn't care to mess with the structure of the code but I can do that if you think it's better

**Review by black-sliver — APPROVED** [review]
Yeah, imo moving the anchor to url_for is a lot better than mixing "plain text" in.

I have not tested the final version here, but I suspect you did.

**Pull request merged**
