### PR TITLE
Core: add generic interface to add ER data to hints

### PR DESCRIPTION
**Pull request by Berserker66**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
add generic interface to add ER data to hints

## How was this tested?
a few LttP generation runs

### CODE REVIEW

**Comment by black-sliver** [comment]
This conflicts with the removal of RegionType, which is something i was looking forward to :sweat_smile: see #814

Would you like to take a look @alwaysintreble ?

I would suggest
* changing
  `outside_region_types: typing.Set[RegionType] = frozenset((RegionType.DarkWorld, RegionType.LightWorld, RegionType.Generic),)`
  to
  `region_types: typing.Optional[typing.Set[Any]] = None`,
* passing in the RegionTypes explicitely from alttp
* changing
  `if entrance.parent_region.type in outside_region_types:`
  to
  `if not region_types or getattr(entrance.parent_region, "type", None) in region_types:`

**Comment by Berserker66** [comment]
Why are we removing RegionTypes? Is it truely only useful for LttP? If not, maybe we want to offer an API to expand on it instead?

**Comment by black-sliver** [comment]
I think the idea is to have "AlttpRegions" and "SoERegions" similar to how we have "AlttpItems" and "SoEItems", with the default Region not having a type, because type is undefined without a game, cleaning up BasesClasses in the process.

We could leave type in and simply set it to `: Optional(Any) = None` (or `: Optional(Enum) = None`, which would be nicer for auto-complete and your use-case (i.e. no getattr), but wastes some memory.

**Comment by Berserker66** [comment]
Changed the method to no longer use .type as requested, at the cost of another LttP import in Main as the related systems aren't generic yet.

**Review by black-sliver — APPROVED** [review]
~~we'll see what breaks in production~~

Code looks fine, tested Alttp generation and `/hint` in the server console. Did not play an actual game.

I get a ton of
> Could not access required locations for accessibility check.

but I don't think that happened before as well.

**Comment by Berserker66** [comment]
Yeah that doesn't sound related but should probably be handled too.

**Pull request merged**
