### PR TITLE
Launcher: Allow opening patches for clients without an exe

### PR DESCRIPTION
**Pull request by Zunawe**
## What is this fixing or adding?

Right now the "Open Patch" button in the launcher is restricted to only recognize file extensions associated with root-level clients. So the only way for an apworld with a bespoke internal client to open a patch file is to open it directly with the launcher.

This removes the exe requirement, and if no exe is found after the file is identified, the file is given directly to the launcher, which should identify the patch file and run `component.func` in `run_component`.

## How was this tested?

Dropped a Pokemon Emerald apworld into `worlds/` and was able to open an `apemerald` patch file to launch the Emerald client that's inside the apworld. Also verified that an `apz5` file still opened and patched correctly. All tested on source only.

### CODE REVIEW

**Comment by black-sliver** [comment]
hm, the `isfile(get_exe(c)[-1])` was because you can skip installation of clients during the setup. Those won't show up in the open_patch then - this is probably still relevant for clients that live outside of their worlds?

**Comment by Zunawe** [comment]
Ahh, right. Maybe something like
```py
        if c.type == Type.CLIENT and \
                isinstance(c.file_identifier, SuffixIdentifier) and \
                (c.script_name is None or isfile(get_exe(c)[-1])):
            suffixes += c.file_identifier.suffixes
```
If you have a "script name", assume that means you require a root level client to be installed. Otherwise, assume you won't have a root level client and need to whitelist your suffixes here so the launcher can handle them.

**Comment by black-sliver** [comment]
Yeah, something like that should work

**Comment by Zunawe** [comment]
Updated. Tested a frozen 3.11 build this time and everything worked as expected. Deleting a couple root-level clients resulted in their suffixes being removed from the Open Patch window.

**Review by black-sliver — APPROVED** [review]
lgtm

**Pull request merged**
