### PR TITLE
Core: add panic_method setting

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
adds a Setting:
```
What to do if the current item placements appear unsolvable.
raise -> Raise an exception and abort.
swap -> Attempt to fix it by swapping prior placements around. (Default)
start_inventory -> Move remaining items to start_inventory, generate additional filler items to fill locations.
```

## How was this tested?
https://discord.com/channels/731205301247803413/1214608557077700720/1236015401494773812
verified that swap gives the same result as it currently does, raise gives a fillerror and start_inventory seems to be doing what it is supposed to, by adding 2 items to precollected for this seed.

### CODE REVIEW

**Comment by Berserker66** [comment]
They default to swap.

**Comment by ScipioWright** [comment]
Could there be a way for a game that knows they get a random swap failure under default settings to specifically choose to have their tests run with panic mode?

**Comment by NewSoupVi** [comment]
Hmm. How do we feel about "Do safe swap only, then if *that* fails, throw the item into starting inventory"?

**Comment by beauxq** [comment]
> Hmm. How do we feel about "Do safe swap only, then if _that_ fails, throw the item into starting inventory"?
> 
> Not even trying swap at all seems a bit overkill for some applications of this that I could think of

This is what I thought.
What about trying to swap first, and if that fails, then go to starting inventory?

**Comment by Alchav** [comment]
> Hmm. How do we feel about "Do safe swap only, then if _that_ fails, throw the item into starting inventory"?
> 
> Not even trying swap at all seems a bit overkill for some applications of this that I could think of

Some form of this would be good. I have, however, seen it go into a swap loop for a *very* long time. As in one time I went to sleep while it was swapping and woke up 8 hours later and it was still trying to swap items. Some way of deciding it has taken too long and to just give up would be nice

**Comment by Alchav** [comment]
There are some games with some options that make swapping very likely. Super Metroid / SMMR with no early morph, for example. Any games with an extremely small sphere one where it's easy to fill it with the wrong items.

**Comment by Berserker66** [comment]
Not entirely sure why this discussion is on this PR, but my 2 cents on the topic  is that we should automate early items; in such a way that it builds a state with starting state + already declared early items, identify worlds with let's say <3% of reachable locations, then add some random items to state that fix this problem, then declare those as early items.

**Review by silasary — APPROVED** [review]

**Review by ThePhar — APPROVED** [review]
Other than a minor style-preference nitpick, this works as advertised and was instrumental in big async gens.

Any further discussion of enhancements that can be added on top of this can be made in a different discussion/PR, in my opinion. Otherwise, LGTM.

**Pull request merged**
