### PR TITLE
Core: make early_items internal only

### PR DESCRIPTION
**Pull request by espeon65536**
## What is this fixing or adding?
Makes the `early_items` option available only internally. It also changes it from a dict of `OptionDict`s to a dict of dicts, since it no longer needs the extra option-like handling.

## How was this tested?
Generated three games with Subnautica included, since it is currently the only game to use `early_items`. In each game, two Seaglide Fragments were available in sphere 1, as recorded by the playthrough.

### CODE REVIEW

**Comment by espeon65536** [comment]
@ThePhar @lordlou can I get your permission to move the early-item functionality of your games over to this system?

**Comment by black-sliver** [comment]
You are completely ignoring this:
https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/zillion/docs/setup_en.md#advanced-settings

**Comment by espeon65536** [comment]
forgot that zillion was using it. @beauxq I can make an `early_scope` option, if that's ok with you?

**Comment by beauxq** [comment]
> forgot that zillion was using it. @beauxq I can make an `early_scope` option, if that's ok with you?

I'm ok with that.

**Comment by Berserker66** [comment]
Then I once again request that people look at Subnautica's implementation before early_items was introduced, instead of the current method that affects multiple fill stages.

**Comment by CaitSith2** [comment]
Not really a fan of not being able to specify items I would like to guarantee I get early, provided the sphere one checks are done.  (sure, I could use plando, but that sort of only works when I know a location is going to definitely be a sphere one location.)  From my testing,  this does go into any sphere one location, not necessarily your own.  The few times I have played zillion,  I was doing 1 scope and 2 zillions for my early items.

I also would like for this option to actually stick around as an actual yaml option, rather than be something that is exclusively internal.

**Comment by Alchav** [comment]
> Not really a fan of not being able to specify items I would like to guarantee I get early, provided the sphere one checks are done. (sure, I could use plando, but that sort of only works when I know a location is going to definitely be a sphere one location.) From my testing, this does go into any sphere one location, not necessarily your own. The few times I have played zillion, I was doing 1 scope and 2 zillions for my early items.
> 
> I also would like for this option to actually stick around as an actual yaml option, rather than be something that is exclusively internal.

If early_items is removed as an option, I will work on adding a way to specify sphere 1 locations as a group into item plando.

**Comment by beauxq** [comment]
> that affects multiple fill stages

I don't understand what is meant by this. I see 1 block of code in 1 function that is called in 1 place.
Am I missing something?

**Comment by Berserker66** [comment]
> > that affects multiple fill stages
> 
> I don't understand what is meant by this. I see 1 block of code in 1 function that is called in 1 place. Am I missing something?

Ok, it was changed since I last looked at it, but it is still slow:
```
        for item in reversed(itempool):
            if (item.name, item.player) in early_items_count:
                if item.advancement:
                    early_prog_items.append(item)
                else:
                    early_rest_items.append(item)
                itempool.remove(item)
```
This has to scan through the entire itempool to find each item, then scan again to remove it, which is why in other places we iterate with index and remove by index, making it a single iteration.

**Comment by beauxq** [comment]
@espeon65536 I don't know if you got a notification for this:
https://github.com/espeon65536/Archipelago/pull/1

**Comment by espeon65536** [comment]
Turns out SMZ3 cannot be cleanly moved to the new system because it fills only one copy of an item locally. This system can't handle that because it's either all local or nothing. Updating the locality system for this nuance is outside the scope of this PR, so I'm leaving SMZ3 alone.

**Comment by Berserker66** [comment]
Subnautica is also meant to be local-only though?

**Comment by espeon65536** [comment]
That's not how this system was originally implemented, so Subnautica using early_items didn't localize them. We need a consensus on how it should work, then: do we want the specified items local or not?

**Comment by ThePhar** [comment]
> Subnautica is also meant to be local-only though? Specifically there are at least 4 instances of the item, 2 of which are local sphere 1, 2+ are anywhere.

Rogue Legacy early vendors/architect should be local only as well.

**Comment by Berserker66** [comment]
If it becomes local-only are there still opponents to making this a public option? It only affects the player's world at that point.

**Comment by beauxq** [comment]
I like the ability to be non-local (and am indifferent about whether it's public or internal).

**Comment by espeon65536** [comment]
I basically just generated a bunch of times with extra worlds thrown in to see whether the relevant items were ever placed nonlocally. I'm comfortable with saying that it's working correctly given the very low probability of observing the results I did with the number of worlds.

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
