### PR TITLE
SNIClient: fix /snes command if tree

### PR DESCRIPTION
**Pull request by Berserker66**

### CODE REVIEW

**Comment by black-sliver** [comment]
Looks like when using `/snes addr:port 1` now, it will still try to connect to the default address:port (in addition to the new one), because `ctx.snes_reconnect_address` is set to the old one from the initial connect attempt

**Review by Ijwu — APPROVED** [review]

**Review by Ijwu — CHANGES_REQUESTED** [review]
Whoops. See @black-sliver's comment.

**Comment by black-sliver** [comment]
maybe to show what i mean:
> /snes localhost:8080 1
Connecting to SNI at ws://localhost:8080 ...
Connecting to SNI at ws://localhost:23074 ...
Attaching to fxpakpro://./dev/ttyACM1
Attached to fxpakpro://./dev/ttyACM1

I believe the old "reconnect loop" remembers what it initially used and does not get cancelled.

**Comment by Berserker66** [comment]
is this still the case after the /main merge?

**Comment by black-sliver** [comment]
yes, unless i screwed up the merging, that's what i did for the output above

**Comment by black-sliver** [comment]
> /snes localhost:8080 1
Already connected to SNES. Disconnecting first.
Connecting to SNI at ws://localhost:8080 ...
Error connecting to SNI (Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080))
Attempt to start SNI was aborted as path SNI was not found, please start it yourself if it is not running
**[starting SNI here manually]**
Connecting to SNI at ws://localhost:23074 ...

ant then another

> /snes localhost:8080 1
Already connected to SNES. Disconnecting first.
Already connected to SNI, likely awaiting a device.

But it never connects to 8080 afaict, and is effectively stuck at the "wrong" SNI

**Comment by Berserker66** [comment]
> > /snes localhost:8080 1
> > Already connected to SNES. Disconnecting first.
> > Connecting to SNI at ws://localhost:8080 ...
> > Error connecting to SNI (Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080))
> > Attempt to start SNI was aborted as path SNI was not found, please start it yourself if it is not running
> > **[starting SNI here manually]**
> > Connecting to SNI at ws://localhost:23074 ...
> 
> ant then another
> 
> > /snes localhost:8080 1
> > Already connected to SNES. Disconnecting first.
> > Already connected to SNI, likely awaiting a device.
> 
> But it never connects to 8080 afaict, and is effectively stuck at the "wrong" SNI

Assuming this is still an issue, it might be time to move this to an Issue, as it doesn't seem related to the PRs change

**Review by black-sliver — APPROVED** [review]
I wasted another hour on the connect code. I think I will write it here and stop caring now.

Basically,
1. snes_device_number gets thrown away for reconnect (i.e. user has to start SNI first)
2. connect address gets thrown away for reconnect (fixed by el-u's change)
3. i believe the use of snes_reconnect_address in combination with /snes is unexpected. 
4. connect will get stuck if there are no snes devices on the connected SNI - so /snes to switch hosts requires the user to exit the SNI that SNIClient is already connected to
5. duplicate logger line (because we have two connections to SNI)

Here is the text on Discord for reference:
https://discord.com/channels/731205301247803413/731214280439103580/1131490109703852062

**Pull request merged**
