### PR TITLE
rename rogue legacy

### PR DESCRIPTION
**Pull request by beauxq**
"`rogue-legacy` is not a valid python module name"

My IDE keeps complaining about this.

### CODE REVIEW

**Review by Ijwu — APPROVED** [review]
I have no clue what considerations need to be taken when renaming packages, so I'll let Berserker/someone else make the final merge. LGTM for what it's worth.

**Comment by beauxq** [comment]
It would be safer if someone tests generating a seed for the game, and make sure it still works.

I couldn't test that because I don't have the game.

**Comment by Ijwu** [comment]
@ThePhar Thoughts?

**Comment by Ijwu** [comment]
> Should be fine. Not 100% sure of the python naming conventions so if underscores are how it should be, I'm on board. Stuck in my TS ways.

Are you capable of testing to ensure no incompatibility is introduced by this? <3

**Comment by Berserker66** [comment]
Has testing occured @ThePhar ?

**Comment by ThePhar** [comment]
Just tested now and it works fine. Good to merge.

**Comment by Berserker66** [comment]
well by now there's a merge conflict.

**Comment by alwaysintreble** [comment]
The documentation automation is fully agnostic of directory names it uses the names of the games

**Comment by beauxq** [comment]
> The documentation automation is fully agnostic of directory names it uses the names of the games

Well it did involve this filename:

`worlds/rogue_legacy/docs/rogue-legacy_en.md`
to
`worlds/rogue_legacy/docs/rogue_legacy_en.md`

That's one thing that I saw that I was thinking you would check. I don't know if there's anything else like that that I missed.

**Comment by beauxq** [comment]
It might be better for the documentation automation to use something like
`worlds/<game>/docs/setup_en.md`
for every game,
so that the directory name wouldn't matter (or look like it matters).

(but not until after this is merged, so I don't have another conflict to resolve 😆)

**Comment by alwaysintreble** [comment]
The documentation automation cycle checks for all existing world modules and checks for its relevant `/docs/` directory then just copies everything. the game_info pages are then generated using a file named `{lang}_{Game Name}`. if something is broken from there that i didn't catch that's just an error on my side. all other tutorial files are referenced in the world's webworld so if you change file names you have to change the reference.

**Comment by beauxq** [comment]
I was wondering specifically about `rogue-legacy_en.md`

Does it need to change to `rogue_legacy_en.md`?
or stay `rogue-legacy_en.md`?
or does it matter either way?

**Comment by alwaysintreble** [comment]
the name doesn't matter as long as it's referenced correctly in the webworld init

**Comment by beauxq** [comment]
"as long as..." means that it does matter.
That's the information that I was looking for.

**Comment by beauxq** [comment]
```
"rogue-legacy_en.md",
"rogue-legacy/en",
```
What is that second line referencing? Does that need to change?

**Comment by ThePhar** [comment]
Honestly at this point, it may just be better to hold off on my 0.9 update. I can just make the folder name change then. It's going to completely override everything in this directory anyway.

**Comment by Ijwu** [comment]
@beauxq @ThePhar So what's the deal here? Can we close this and await RL changes from @ThePhar or do we move forward here?

**Comment by beauxq** [comment]
Just merged to resolve conflicts. My guess is that it's ok like this, but still I don't have this game to test generating a seed.

**Comment by ThePhar** [comment]
@beauxq Once you have the conflicts resolved, I'll confirm the changes still work with RL and merge it.

**Pull request merged**
