### PR TITLE
Pokemon RB: Rename launcher entry to 'Pokémon Red and Blue Client', rename client to PokemonRedBlueClient

### PR DESCRIPTION
**Pull request by remyjette**
## What is this fixing or adding?

Now that Emerald has merged, I anticipate #tech-support threads where people try to play Emerald and click the button labelled "Pokemon Client". This PR renames it to the "Pokémon Red and Blue Client" for clarity.

Also removed the "(select `Pokemon Client` during installation)" line in the setup docs as that's no longer necessary with #2268.

## How was this tested?

Built the executables, ran the installer, then opened the launcher. Now shows up as "Pokémon Red and Blue Client". Executable in ProgramData\Archipelago is now "PokemonRedBlueClient.exe"

One weirdness is that when installing over an old installation (as opposed to uninstalling and reinstalling), the installer doesn't remove the old ArchipelagoPokemonClient.exe. It also doesn't clean up any start menu shortcuts even though in new installs only the "Archipelago Launcher" shortcut is created. This means if someone installs with this change on top of a 0.4.3 install, they'll still have an "Archipelago Pokemon Client" link in their start menu that doesn't work.

That doesn't affect new installs or (uninstall/reinstall), but I still wanted to call it out. If it's a concern I can revert all of the changes other the `base_title` and `display_name` so it would still be PokemonClient.exe and just renamed in the launcher.

### CODE REVIEW

**Comment by ThePhar** [comment]
@Alchav

**Comment by ThePhar** [comment]
Gonna add release blocker tag, since this might want to be addressed before release. Thanks.

**Comment by black-sliver** [comment]
The client should be moved from core to the world and the LauncherComponents entry should be removed and dynamically added from the world's `__init__.py`.

**Comment by Alchav** [comment]
> @Alchav

I'm working on adding Pokémon Red and Blue to the Bizhawk Client, and will delete the Pokémon Client. This PR can be merged if my addition isn't finished and merged in time for next release, but otherwise this will be moot.

**Comment by remyjette** [comment]
> > @Alchav
> 
> I'm working on adding Pokémon Red and Blue to the Bizhawk Client, and will delete the Pokémon Client. This PR can be merged if my addition isn't finished and merged in time for next release, but otherwise this will be moot.

Yep, I saw today in #pkmn-red-blue that you were working on switching to the Bizhawk client (I'm purin). I'll abandon this if that merges.

**Comment by black-sliver** [comment]
superseded by #2466

**Pull request closed without merging**
