### PR TITLE
Adventure: Fix KeyError on Retrieved

### PR DESCRIPTION
**Pull request by Silvris**
## What is this fixing or adding?
As a side effect of #2392, all clients are now receiving extra "Received" packets. This would cause errors in AdventureClient and ZillionClient as they did not properly check if their keys were in `args["keys"]`. This renders the two clients unusable.

## How was this tested?
Connected into a multiworld with both games with the client changes.

### CODE REVIEW

**Comment by Silvris** [comment]
Since I can't request reviews, @JusticePS @beauxq will need your approvals.

**Review by beauxq — APPROVED** [review]
Zillion change LGTM.

I might find time to test it soon, but if I don't, I think it's ok since it's a simple change.

update: tested a game on this branch, and it worked

**Review by Berserker66 — APPROVED** [review]

**Comment by beauxq** [comment]
Zillion was fixed in a different PR, so you could change the title in this one.

**Comment by Berserker66** [comment]
I gave Justice time to make sure this is the fix they want, or lodge complaints, but since it's breaking the client I'll merge this for now without approval :(

**Pull request merged**
