### PR TITLE
Docs: Network protocol package -> packet where appropriate

### PR DESCRIPTION
**Pull request by ScipioWright**
## What is this fixing or adding?
Changes the term "package" to "packet" where appropriate.

## How was this tested?
Rigorously.

## If this makes graphical changes, please attach screenshots.
image

### CODE REVIEW

**Review by nicholassaylor — APPROVED** [review]
PR does exactly what it says. Any instance that refers to a packet and says "package" has been replaced with "packet". Nothing in the changes appears to be wrong to me.

Someone with write access might want to take a cursory look over to confirm.

**Comment by ScipioWright** [comment]
If there's issues here, please leave a review or comment of some sort so we can sort them out. In its current state, the doc is inaccurate as far as I'm aware.

**Review by silasary — APPROVED** [review]

**Comment by black-sliver** [comment]
This has been discussed in Discord multiple times, and no core maintainer stepped up to agree with this change to the extend where they approved this PR. Imo `packet` is the wrong term here.

Most recent Discord discussion was here: https://discord.com/channels/731205301247803413/731214280439103580/1176895901667692595

**Comment by ScipioWright** [comment]
Do you think it's fine as is then? Or do you have any suggestions as to what it should be changed to?

**Comment by black-sliver** [comment]
Sadly, I haven't come up with a better suggestion that I'm really happy with. "Command", "Sequence", "Record" would all be options (of entries inside a packet), but those all sound somewhat alien to me in this context.

**Pull request closed without merging**
