### PR TITLE
Rogue Legacy: Remove item/location id overlap rejection code.

### PR DESCRIPTION
**Pull request by ThePhar**
## What is this fixing or adding?
RL has been updated to support id overlaps. This removes that code that rejects.

## How was this tested?
It wasn't.

## If this makes graphical changes, please attach screenshots.
image

### CODE REVIEW

**Comment by Berserker66** [comment]
Should probably also increase minimum client version to force people to update?

**Comment by NewSoupVi** [comment]
> Should probably also increase minimum client version to force people to update?

Ppl are kind of forced to update by the instant crash when loading the game lol

**Comment by Berserker66** [comment]
> > Should probably also increase minimum client version to force people to update?
> 
> Ppl are kind of forced to update by the instant crash after connecting lol

Order of operations can matter, assuming the client displays the version warning before it tries to eat and choke on the new datapackage.

**Review by NewSoupVi — APPROVED** [review]

**Comment by black-sliver** [comment]
Fully agree with berserker. Forcing the update on the user is lot better than having them crash and having to figure it out on their own and minimum client version exists exactly for that

**Comment by ThePhar** [comment]
I will not be posting another update for legacy RLR at this point. If that's not worth merging this, then I guess RL players will have to wait until 2.0 is released and I push new apworld changes then.

**Pull request merged**
