### PR TITLE
Fill: don't crash before debug output in case of unfilled locations

### PR DESCRIPTION
**Pull request by Berserker66**

### CODE REVIEW

**Comment by Ijwu** [comment]
If I'm understanding correctly, the purpose of this is to offset a crash so it doesn't occur in the spot you edited but later instead? Can that have unforeseen consequences? Should there not be specific handling for the issue at the place you edited rather than crash mitigation?

**Comment by Berserker66** [comment]
That if tree is already "on no, we are gonna die". It then collects info and prints it out to find the issue and the culprit world. However, due to an oversight it only works for more items than locations, not the other way around. This fixes that oversight.

**Comment by Ijwu** [comment]
Makes sense. Is a null check not required on location itself?

**Comment by Berserker66** [comment]
No, world.get_locations() gets all Locations attached to Regions. They can't be None.

**Comment by Ijwu** [comment]
Sounds good, thanks!

**Pull request merged**
