### PR TITLE
The Witness: Add more panels to the "doors: panels" mode

### PR DESCRIPTION
**Pull request by NewSoupVi**
There were more door panels that were kinda weird not to have items.
This adds those to both the individual panels and regional panels modes.

New client: https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/releases/tag/v5.0.0p16

Tested:
A little

### CODE REVIEW

**Comment by NewSoupVi** [comment]
A weird edge case was found where two door items will exist for the same door (not in a buggy way, but in a confusing way). I'll fix that

**Review by Exempt-Medic — APPROVED** [review]
The changes all LGTM code-wise. I checked that the correct panel items were created under all twenty-four option-combinations and generated 1000 random games just to be safe.

**Comment by NewSoupVi** [comment]
Drafting because I want to add a unit test for this

**Comment by NewSoupVi** [comment]
Unit test has been added, this is ready for review again

**Comment by Exempt-Medic** [comment]
Conflicts

**Comment by NewSoupVi** [comment]
Conflict resolved

**Pull request merged**
