### PR TITLE
CI: build: create setup

### PR DESCRIPTION
**Pull request by black-sliver**
## What is this fixing or adding?

Build the inno setup as part of our build CI and upload-artifact the result
also add /DNO_SIGNTOOL to inno_setup.iss

This is used to test changes that may break building the setup.

I updated only the actions in the changed job. Updating all (other) actions should be a separate PR imo.

## How was this tested?

CI and trying to run the resulting installer in wine.

### CODE REVIEW

**Review by alwaysintreble — APPROVED** [review]
changes LGTM and I don't see any reason we wouldn't want this

**Comment by black-sliver** [comment]
The `#ifdef` should be correct, but I think berserker needs to make sure that I didn't break the signtool step since I have no way of testing that (unless someones writes instructions how to test that with a self-signed cert, assuming signtool works in wine).

**Review by Berserker66 — APPROVED** [review]
I see no  way to trigger/modify the ifndef constants via the inno setup UI though.

**Comment by black-sliver** [comment]
I believe you have to put the `#define` either in the (define section up top of the) iss file or in an include.

See this example: https://github.com/jrsoftware/issrc/blob/main/Examples/ISPPExample1.iss

**Pull request merged**
