### PR TITLE
Setup: auto download SNI

### PR DESCRIPTION
**Pull request by Berserker66**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
downloads SNI as part of the build process

## How was this tested?
only on windows-amd64

### CODE REVIEW

**Comment by black-sliver** [comment]
Hm, I see two issues
1. the linux build we (want to) integrate, as long as there are no error reports, is the `manylinux2014-amd64`, not the `linux-amd64`, so `sni_platform_name` would match the wrong one.
2. this would bundle "unvalidated" SNI: if jsd were to release something between RC and Release we'd end up with an untested SNI

**Comment by Berserker66** [comment]
1. could dlook for contains both platform name and "many", if so, prefer it?
2. yeah, but I don't really see any good ways to avoid that, unless we want to state an explicit version somewhere and then run into the same issue of potentially forgetting

**Comment by black-sliver** [comment]
1. sounds like a reasonable way. you want to write it up and i test?
2. the only suggestion i have is using a command line argument, like `--update_sni` or `--keep_sni` and integrate the switch into the release workflow (either --update_sni for RC, or --keep_sni for release)

**Comment by Berserker66** [comment]
1. should now be done
2. I don't really have a difference in how the two are made currently. Though it is now logging what it downloaded which includes the version number. Which admittedly only helps if one remembers the version number from the RC phase.

**Comment by black-sliver** [comment]
```python
>>> platform.machine()
'x86_64'
```
but SNI's download is called ...amd64...

**Comment by Berserker66** [comment]
F
image

**Comment by black-sliver** [comment]
`windows` + `64bit` should now match `sni-v0.0.86-windows-arm64.zip` :S

**Comment by Berserker66** [comment]
Hm, any good idea on how to determine if we're on ARM?

**Comment by black-sliver** [comment]
i think the only generic solution is to have aliases for platforms.
i.e. x86_64 == x64 == amd64

```python
def download_SNI():
    common_machine_aliases = [["amd64", "x86_64", "x64"]]
    os_name = platform.system().lower()
    machine_name = platform.machine().lower()
    machine_names: list[str]
    for aliases in common_machine_aliases:
        if machine_name in aliases:
            machine_names = aliases
            break
    else:
        machine_names = [machine_name]

    # ...

        for machine_name in machine_names:
            if os_name in download_url and machine_name in download_url.lower():
                ...
```
maybe?

**Comment by black-sliver** [comment]
This should work on linux and mac now. Can you test on windows @Berserker66 ?
You'll probably have to rebase or frankenstein the branch to get away with cx_freeze changes.

**Review by black-sliver — APPROVED** [review]

**Pull request merged**
