### PR TITLE
Docs, OOT: Update YAML Creation Instructions for OoT

### PR DESCRIPTION
**Pull request by ArashiKurobara**
## What is this fixing or adding?
Per a tech support thread in Discord, the OoT guide turned out to have had a 0.1.7 yaml hard-coded in as a suggested example. I borrowed the verbiage from the SMZ3 setup guide, as that seemed like a particularly good sample.

Only covers the English version of the setup guide; Spanish and French appear to have the same issue but I would not be able to translate the instructions.

## How was this tested?
This only changes a documentation .md file and as such was tested with the preview on the GitHub web editor.

### CODE REVIEW

**Comment by alwaysintreble** [comment]
I'd prefer this just got completely removed as we have general guides that explain how to create yaml files and manually edit them.

**Comment by ArashiKurobara** [comment]
Yeah, I certainly don't have any strong feelings either way on that, just figured most of the other setup guides have it and either way the ancient one's gotta go.

**Comment by Berserker66** [comment]
@espeon65536

**Comment by espeon65536** [comment]
I would like if we could ping the authors of the non-English guides to see if we can get those updated. Other than that, the update is fine.

**Comment by black-sliver** [comment]
@TheLynk @Edos512

**Comment by TheLynk** [comment]
I would update the text after merging the text

**Review by BootsinSoots — APPROVED** [review]
Removes what it needs to. I think I like calling the file a config file and specifying the file extension, that's a little easier for the average user to understand what they are doing. It makes more intuitive sense

**Review by espeon65536 — APPROVED** [review]

**Review by black-sliver — APPROVED** [review]
Thanks!

**Pull request merged**
