### PR TITLE
LTTP yaml update

### PR DESCRIPTION
**Pull request by t3hf1gm3nt**
removes vendor option from hints, adds scam setting, and adds P option to shop shuffle.

### CODE REVIEW

**Comment by t3hf1gm3nt** [comment]
I probably want to hold on this getting merged until the pyramid hole update PR goes through so i can update that option as well

**Comment by alwaysintreble** [comment]
pyramid hole changes are backwards compatible.

**Comment by t3hf1gm3nt** [comment]
so i should leave the auto option in the template yaml then?

**Comment by alwaysintreble** [comment]
even if nobody uses it i don't really see a reason to remove options tbh

**Comment by t3hf1gm3nt** [comment]
well if the option does literally nothing anymore i would remove it, like the vendor option im removing from hints here. i thought you were possibly removing the auto option from they pyramid setting. if you aren't, then i wont remove it.

**Comment by ThePhar** [comment]
Open Pyramid keeps the same option name and choices, so there should be no need to change it. The functionality is still there.

**Comment by t3hf1gm3nt** [comment]
Ok. i think i was getting confused with some talk we were also having on discord, but going over that PR I see that auto is remaining so thats cool. going to go ahead and release this for review.

**Review by Joethepic — APPROVED** [review]

**Review by alwaysintreble — APPROVED** [review]

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
