### PR TITLE
Tests: Add a test that worlds can create filler without generation steps

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
Item Link filler replacement creates a new world and then creates filler with that world, if that new world can't actually create filler, generation will crash so this is a test for that.

## How was this tested?
📄 ✍️

### CODE REVIEW

**Comment by Berserker66** [comment]
This will need to check that the world even has items defined, so it doesn't fail on bk sodoku

**Comment by Berserker66** [comment]
@espeon65536 for OoT and @lordlou for SMZ3
PoryGone said it will be fixed in the next SA2 update, which is unfortunate as I'd prefer it fixed in this AP update.

**Comment by kindasneaki** [comment]
I’m surprised RoR2 isn’t failing as it doesn’t have `get_filler_item_name`.  Either way I’ll try to get it added as soon as I can

**Comment by alwaysintreble** [comment]
Closing this as #2081 does the same thing but tests more things at the same time.

**Pull request closed without merging**
