### PR TITLE
LttpClient reliability improvements

### PR DESCRIPTION
**Pull request by black-sliver**

### CODE REVIEW

**Comment by black-sliver** [comment]
The first commit tries to validate the bits read for locations by ensuring gamemode is still valid after the bits have been read.

I would like to either make the goal check more strict, or validate the goal by doing an additional read as well. Does anyone know for which `gamemode` values `gameend` is supposed to be valid in? At the moment `gameend[0]` results in `ClientStatus.CLIENT_GOAL` for all 5 `gamemode`s in https://github.com/ArchipelagoMW/Archipelago/blob/7a9f6e2a8e999c7c01bf79ec29a23893469f578c/LttPClient.py#L831-L834

**Comment by Berserker66** [comment]
Is this what you were looking for http://alttp.run/hacking/index.php?title=RAM:_Bank_0x7E:_Page_0x00?

**Comment by black-sliver** [comment]
Hm, yes and no.

I think that `ENDGAME_MODES` already has the game modes in which you normally complete the game, but what i really want to know is - say if you hit reset too quickly or lose SNI connection without noticing, will it still trigger the goal at some point currently? If so at what point (game mode) would that trigger?

Sorry for not following up on that until now, but talk about maybe getting more games into 0.2.0 made me focus on evermore.

**Comment by Berserker66** [comment]
Ever since switching to SNI ssuch problems have vanished. We used to have wrong data when:
1. Switching roms
2. Going to fxpak menu
Both of these appear to be fixed with SNI and every time we've had a report of this since was when someone was still using qusb2snes.

**Comment by black-sliver** [comment]
As I understand it SNI somewhat reliably detects a reset, but it is still a data race in some circumstances (SNI running your query before noticing the game swap) as last time i heard luabridge / `connector.lua` does not detect a game swap.

By re-reading `mode` you can verify consistency of the entire read block (i.e. all flags were read in a legal state). If you were to change the Game after `mode` verification but before the last flag is read, the flags may be inconsistent. This is why I still want to make the change, even if SNI's reset detection is working in most cases.

**Comment by black-sliver** [comment]
Oh, that may have been a bad description above. Let me clarify. It is not "not detecting a game swap", but there is no out-of-band signalling for when the game was changed or the console was reset, so there may be a time window where SNI does not know that the game was changed. If that happened on the last flag you read, you will have bad data.

**Comment by Berserker66** [comment]
I don't mind adding a layer of protection for that; if that's what your question is?

Though I feel it makes most sense to put that into SNI itself, to guard other applications as well.

**Comment by black-sliver** [comment]
SNI does not know which block of reads is supposed to be somewhat-atomic, so this can't be done in SNI.
Back-ends do not guarantee atomic reads beyond a certain size or across memory domains, so we can only check if it was "atomic enough" to use the data.

**Comment by Berserker66** [comment]
I wonder if it would make sense to add such commands to SNI then; something like "StartBlock" "EndBlock".

**Comment by black-sliver** [comment]
For that you would probably collect all reads (there is a size limit of 255 bytes in the original protocol though). And instead of doing individual reads, you schedule a single read with all memory regions. SNI could detect a changed ROM header after such a read, before returning values, but it could not detect a soft reset (WRAM inconsistent), since there is no atomic read on the back-end. So you'd still need to add a re-read of one byte (`mode`) and check it for consistency.

**Comment by Ijwu** [comment]
What is the status of this? Are we waiting for something here? Can this be closed until a period in time when work is ready for review?

**Comment by black-sliver** [comment]
I actually planned on adding the other one-liner and test it during holidays, but did not get to it :S.
If anyone feels like they have time, the one commit could be tested as is already. I still plan on finishing this at some point.

**Pull request closed without merging**
