### PR TITLE
[Docs] Added links to client implementations

### PR DESCRIPTION
**Pull request by JarnoWesthof**
to hopefully prevent people from creating their own clients

### CODE REVIEW

**Comment by Berserker66** [comment]
Mh, we might need to list "SuperNintendoClient" seperately. Saying it's for Super Nintendo like that is incorrect, since the included SNIClient handles the same games. It runs on Node however, which isn't available as a seperate library however. So Z5Client and SuperNintendoClient would need to be mentioned differently as they don't quite fit that list.

**Comment by Berserker66** [comment]
So, as per the discussion in discord, it might be best to say that no Library exists for Node, but the following two clients do, or leave it out entirely but that'd be bad if it leads to duplicate work.

**Comment by JarnoWesthof** [comment]
@Berserker66 is this what you meant?

**Comment by Berserker66** [comment]
CommonClient.py is technically a "library". In Python we don't really use that word, we use module (for single-file libraries) or package (for folder libraries). So I think that should be added and then I think we're good.

**Comment by JarnoWesthof** [comment]
Updated

**Comment by Berserker66** [comment]
Thank you!

**Pull request merged**
