### PR TITLE
Docs: remove another remote_items leftover

### PR DESCRIPTION
**Pull request by Berserker66**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
remove another remote_items leftover

## How was this tested?
no

### CODE REVIEW

**Comment by black-sliver** [comment]
if you need local starter inventory for whatever reason, don't we have to apply the stuff to the mod/patch/rom? so i'd rather put a word of caution there, telling that remote starter inventory is preferred, than removing a useful snippet.

**Comment by Berserker66** [comment]
slot_data would be the wrong place then still though, should probably be in generate_output

**Comment by black-sliver** [comment]
i agree
yes

**Comment by Berserker66** [comment]
mh yes, reading might help.

**Review by black-sliver — APPROVED** [review]

**Pull request merged**
