### PR TITLE
SNIClient data slot fix

### PR DESCRIPTION
**Pull request by lordlou**
## What is this fixing or adding?
Adds slot_data to SNIContext when want_slot_data is set (as the documentation states).

I need this for sm_map_rando world so the client can exclude Nothing items from being received (which cant be prevented from the ROM side anymore).

## How was this tested?
I was getting `AttributeError: 'SNIContext' object has no attribute 'slot_data'` in the client before the fix. I get the intented behavior (slot_data is populated and Nothing items are filtered out) after the fix.

### CODE REVIEW

**Review by qwint — APPROVED** [review]
code looks good, i use something similar in my own client
but should probably have the self.slot_data typed with something like `slot_data: dict[str, any]`
and if you do, either change the None in args.get() to {} or make the typing optional

Also, should probably squash those commits

**Comment by Berserker66** [comment]
This will need a bit more revamping to do properly. Currently, SNIClient always sends want_slot_data, but all current games do not actually use it. In case of LttP there is tracker data that is needlessly transferred. Personally, I think want_slot_data should be transferred to be a core CommonClient responsibility, from which SNIClient can then inherit.

**Comment by qwint** [comment]
want_slot_data _is_ a CommonClient thing, it is defined and used in CommonClient (notably default True but set to False in run_as_textclient() so anyone who doesn't opt out will grab their slot data)
or do you mean that this update should be done in CommonClient so everything can inherit self.slot_data being set automatically?

**Comment by Berserker66** [comment]
yes to the second part.

**Comment by lordlou** [comment]
I found another way to do what I needed.

**Pull request closed without merging**
