### PR TITLE
SC2: Python 3.11 compatibility

### PR DESCRIPTION
**Pull request by Ziktofel**
## What is this fixing or adding?
SC2 Client Python 3.11 compatibility

## How was this tested?
The game launches

## If this makes graphical changes, please attach screenshots.
No

### CODE REVIEW

**Comment by Ziktofel** [comment]
According to @Them8 everything looks OK ingame

**Comment by Berserker66** [comment]
The bot folder should probably have at least a readme, detailing what it is, where it's from and where the documentation is.
The original bot also has a License file, the terms of which are not fulfilled here.

**Comment by Ziktofel** [comment]
done

**Comment by Berserker66** [comment]
ModuleNotFoundError: No module named 'loguru'
When I tried this on a fresh venv

**Comment by Ziktofel** [comment]
hm, weird

`loguru>=0.7.0` is in the module's `requirements.txt`

I'll dig into that later

**Comment by Berserker66** [comment]
It is in the subfolder's requirements.txt, however ModuleUpdate doesn't look that deep.

**Comment by Ziktofel** [comment]
Merged the Salz's fix for that

**Review by Berserker66 — APPROVED** [review]
Works for me now in a fresh venv

**Pull request merged**
