### PR TITLE
SC2: Option for random mission order

### PR DESCRIPTION
**Pull request by TheCondor07**
Now allows for players to choose to shuffle the mission order, with some cavets to make it beatable.  Random order logic will need more testing to see how playable this is.

### CODE REVIEW

**Comment by TheCondor07** [comment]
Don't approve yet, need to do some changes to make it more efficient and fix a few error.

**Comment by Alchav** [comment]
> Don't approve yet, need to do some changes to make it more efficient and fix a few error.

You can set it to a draft PR and it won't be mergable until you mark it ready for review

**Comment by TheCondor07** [comment]
Added quality of life features for playing random missions and did much more testing of the system.  The starting item is now successfully being generated at the end of a mission and missions can be hovered over to see what mission is unlocked next.

**Comment by TheCondor07** [comment]
The test last night when fine, submitting this as the last 3.2 feature update for Starcraft 2 Client.

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
