### PR TITLE
Core: change yaml_output to output a full csv

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
Changes the yaml_output arg to be a boolean instead of int arg and outputs all the player options as direct csv instead of needing an additional conversion step. The function could likely be reused to dump player options on gen failure, but setting up the failure hooks is out of scope here.

## How was this tested?
Generating various seeds with a weights file and using debug to verify the output csv matched the options during gen.

### CODE REVIEW

**Comment by Berserker66** [comment]
Just reading the title, this would be csv_output then.

**Comment by Exempt-Medic** [comment]
This probably should not include `Removed` options

**Comment by Exempt-Medic** [comment]
I think having this sorted by game would be best, so that all the options from each game are in one section

**Comment by Exempt-Medic** [comment]
Another thing worth considering is when worlds have options with the same display name. Currently, the option name is only listed once, even if those worlds have completely different possible values for it, I'm unsure if this is intended, but if you do end up sorting these by game, you'd want to have the same display name in both

**Comment by alwaysintreble** [comment]
> I think having this sorted by game would be best, so that all the options from each game are in one section.

it already does?

**Comment by alwaysintreble** [comment]
> Another thing worth considering is when worlds have options with the same display name. Currently, the option name is only listed once, even if those worlds have completely different possible values for it, I'm unsure if this is intended, but if you do end up sorting these by game, you'd want to have the same display name appear in both

i don't understand what you mean. since it's csv it has to show every possible option display name for every game per player so even if there are wildly varying options with the same display name they'll still show up.

**Comment by Exempt-Medic** [comment]
> > I think having this sorted by game would be best, so that all the options from each game are in one section.
> 
> it already does?

No, it's every option display name in alphabetical order

**Comment by alwaysintreble** [comment]
> This probably should not include `Removed` options. Could add something like this to `dump_player_options`:
> 
> ```python
>                 if option.visibility == Visibility.none:
>                     continue
> ```

went ahead and did this but i'm not sure if this is the desired behavior. not sure if any exist but it seems perfectly valid to me that an option could function and not be deprecated and just want to be hidden. i know kaito has options that he doesn't want displayed on the website for instance, though i'm unsure if those ones still show up in the default templates.

**Comment by Exempt-Medic** [comment]
I know Witness has an option that only exists for unit tests, though it functions outside of them. Unsure if Violet would want it showing up in the csv output

**Comment by NewSoupVi** [comment]
Don't have a strong preference but leaning towards "It should be output"

**Review by Exempt-Medic — APPROVED** [review]
There's still some weirdness when games share option display names, since they get listed together after the first game uses it, but I think that's mostly fine. This fixes two bugs in the previous implementation I knew about. I agree that changing it to `csv_output` would make sense, although it never occurred to me that it was called `yaml_output` because of the *format* and not where the information came from. Otherwise, I tested various methods of using this, with different numbers of games and types of yamls, and everything seemed to work well.

**Comment by alwaysintreble** [comment]
If I'm going to rename it I'd much rather rename it to something more generic like `dump_options` the problem with that is that we'd probably want the user to be able to specify output format though I don't know what output formats would actually be useful other than csv and json. Adding json support to this wouldn't be bad, but not sure if there's demand for it. It'd probably make more sense if we expanded this to also dump options if generation fails after `generate_early`, but that's very out of scope here.

**Comment by ScootyPuffJr1** [comment]
I haven't fully tested functionality for my use during a Big Async, but on the surface it appears to be giving me what I want. However, it adds a blank row between every row, which I would much rather not exist. In my ideal world, a column like Goal would show up once per game that has that option name, either fully filled with all games' info or not, but this is a limitation I can easily work around.

**Comment by alwaysintreble** [comment]
> However, it adds a blank row between every row, which I would much rather not exist.

oh whoops, it originally didn't do that and didn't realize i broke it. fixed

**Comment by ScootyPuffJr1** [comment]
I tested the latest commit to remove the extra rows and that works as expected now. We've lost the functionality of deleting columns where all worlds roll the same option, but I don't think that's a problem since displaying all options has clear benefit. For the purpose of generating and setting up the big async, this looks good to me.

**Comment by ScootyPuffJr1** [comment]
After using this to set up a big async, it would be tremendously better for my purpose to have duplicate columns if games share the same option name.

**Comment by alwaysintreble** [comment]
> After using this to set up a big async, it would be tremendously better for my purpose to have duplicate columns if games share the same option name.

should the per_game options that every game has to support be duplicated too?

**Comment by Exempt-Medic** [comment]
It does seem a little weird that repeated display names repeat the entire column, so like, if Lingo and Witness both have "Trap Weights" it gets displayed with both sets of values twice. Similarly "Death Link" gets displayed several times, but you can still easily slice or filter by row to get the information you want.

**Review by Exempt-Medic — APPROVED** [review]
Reaffirming approval from doing more testing with the current changes.

**Comment by alwaysintreble** [comment]
> It does seem a little weird that repeated display names repeat the entire column, so like, if Lingo and Witness both have "Trap Weights" it gets displayed with both sets of values twice. Similarly "Death Link" gets displayed several times, but you can still easily slice or filter by row to get the information you want.

yeah this is why i was worried about doing it that way. i think i do agree that filtering this way makes it easier to clean up though

**Comment by ScootyPuffJr1** [comment]
I created the September big async spreadsheet using the version from before the latest two commits and then compared to how it would have gone using this code as is and it would have saved me between 1 and 2 hours. This file is extremely helpful to me.

**Review by ScootyPuffJr1 — APPROVED** [review]

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
