### PR TITLE
Pokemon Emerald: Send current map to trackers

### PR DESCRIPTION
**Pull request by Zunawe**
## What is this fixing or adding?

Sends changes to the player's current map to trackers via bounce packets.

## How was this tested?

Watched the network logs while changing maps.

### CODE REVIEW

**Review by ScipioWright — APPROVED** [review]
Didn't test client. This looks simple enough not to break anything if it doesn't work.

**Review by Exempt-Medic — APPROVED** [review]
The changes LGTM and I confirmed that they showed up properly with network logging

**Review by NewSoupVi — APPROVED** [review]

**Comment by Mysteryem** [comment]
I think this might not quite work as intended.

The Bounce message sends to all clients that match any of the provided `slots`, `tags` or `games`, so this will send a Bounced message to any clients connected to the players' slot and any clients with the `"Tracker"` tag.

There's probably not much point sending the Bounced message to every tracker connected to the multiworld. Only specifying to send to clients connected to the player's slot should suffice.

From the Bounce documentation:
> Send this message to the server, tell it which clients should receive the message and 
**the server will forward the message to all those targets to which any one requirement applies**.

**Comment by NewSoupVi** [comment]
Oh, it's an **or** relationship? My bad, I remembered that wrong.

**Comment by NewSoupVi** [comment]
So it is.

**Comment by NewSoupVi** [comment]
Well, there should be a short term fix, but for a long term fix, I made this:
https://github.com/ArchipelagoMW/Archipelago/pull/3845/files

**Pull request merged**
