### PR TITLE
The Witness: Add Fast Travel Option

### PR DESCRIPTION
**Pull request by NewSoupVi**
It's just a toggle option that gets added to slot data (which happens automatically for my options :D).

The important stuff is in the client. This is the new release that supports this feature:
https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/releases/tag/v7.0.0p5

Also rename "Swamp Near Platform" to "Swamp Platform" because that's a better name for where the warp goes

### CODE REVIEW

**Review by Exempt-Medic — APPROVED** [review]
It's one option and a single region rename. The change LGTM and functions in generations and with the client. The list of warps is accurate (this will need to be updated in Variety depending on the order those get merged, but that's fine)

**Review by Zunawe — APPROVED** [review]
Changes look fine. Don't see any leftover instances of the old location name, and the option does what it needs to.

**Comment by NewSoupVi** [comment]
This needs to be updated for Variety

**Comment by NewSoupVi** [comment]
Has been updated for Variety rando

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
