### PR TITLE
Launcher: Adding Unrated mention to the launcher

### PR DESCRIPTION
**Pull request by ReverM**
## What is this fixing or adding?

Replacing "18+ Discord Server" with "Unrated/18+ Discord Server"

## How was this tested?
I ran the Launcher locally.

## If this makes graphical changes, please attach screenshots.
Gonna add comment

### CODE REVIEW

**Comment by ReverM** [comment]
Capture d’écran 2024-04-05 002615

**Review by Exempt-Medic — APPROVED** [review]
imho, it's a good change. It's small and looks just fine

**Review by nicholassaylor — APPROVED** [review]
LGTM

**Review by eudaimonistic — APPROVED** [review]
This change better mirrors more recent policy discussions and best practices in the two Discord servers.  Some users have brought up concerns that a purely "18+" tag may imply only one kind of content (to some), and this change better emphasizes that it's basically a matter of Discord itself as a platform rather than one specific category of games.

**Review by silasary — APPROVED** [review]

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
