### PR TITLE
ALTTP: Bomb Walls Logic Fixes

### PR DESCRIPTION
**Pull request by Alchav**
## What is this fixing or adding?
- Splits the Turtle Rock bomb walls into their own regions, logically requiring bombs in both directions.
- Adds missing rules to Hookshot Cave bomb walls. I had split Hookshot Cave into multiple regions in order to add these rules but never actually added the rules, apparently. Oops.

## How was this tested?
Turtle Rock:
- Ensured generation succeeds normally on open and inverted.
- Created a yaml with Bomb Upgrade (50) and Lamp plando'd into laser bridge, with entrance shuffle on, which succeeded on main but failed this branch with same seed number.
Hookshot Cave:
- Ensured generation succeeds normally.
- Created a yaml with Bomb Upgrade (50) and both gloves plando'd into Hookshot Cave on inverted, which succeeded on main but fails on this branch.

### CODE REVIEW

**Comment by Berserker66** [comment]
from what I gathered, some of these walls are supposed to be open, but since 0.4.5  aren't, so we should find why this is no longer written to the rom first.

**Comment by Alchav** [comment]
> from what I gathered, some of these walls are supposed to be open, but since 0.4.5 aren't, so we should find why this is no longer written to the rom first.

What I saw mentioned in Discord was that they are open in the *Doors* randomizer

**Comment by Berserker66** [comment]
No, it's talking about crosskeys, which means full keyshuffle with crossed ER.

**Comment by Alchav** [comment]
> No, it's talking about crosskeys, which means full keyshuffle with crossed ER.

Okay I see the problem. I'll get it fixed tonight or tomorrow

**Comment by Alchav** [comment]
The door and exit fix variables are fixed to check the correct option variable names, moved into the alttp world, changed to simple booleans. The bomb wall logic in TR is now only added if the fix is not applied. 

AP 20777137877808592492 P1 AlchavZ3 2024-04-14 10 21 20

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
