### PR TITLE
Webhost: Add popover menus

### PR DESCRIPTION
**Pull request by kindasneaki**
## How was this tested?
Desktop and Iphone

## If this makes graphical changes, please attach screenshots.
removed image as it is no longer relevent

### CODE REVIEW

**Comment by LegendaryLinux** [comment]
As the logo text over the ocean scales down in size, the size of the text below it should also scale down proportionally. In practice, this is probably the difference of `0.25rem` across the full range of scaling.

**Comment by kindasneaki** [comment]
After looking at good ways to change the text under the logo. I ended up using `vw` with it falling back to different font-sizes if the browser doesn't support it.
Also I noticed that the footer text needed adjusting so it wouldn't stack on top of each other.

**Review by LegendaryLinux — CHANGES_REQUESTED** [review]
I just got a chance to test this on my local system.

What was the original problem you were trying to solve? Were you concerned the hamburger menu was appearing at the same time the clouds vanished? If so, that was intentional.

Your PR has introduced some bugs.
1. The links in the header wrap and exceed the vertical size of the header while shrinking the window on Firefox.
2. The hamburger menu does not also scale down in size with the header logo, and looks too large by comparison.
3. In Chrome, the header logo abruptly changes size while no other elements change while shrinking the window.

As I am not at home and do not have access to my router, I was unable to test on mobile devices.

There are also some design problems.
1. The site logo in the header should not resize itself.
2. Due to the changed max-width for displaying the hamburger menu, you have a created a third layout for the main page. One in which only the island is visible, and the header links are also visible. This leaves a lot of empty space in a non-mobile view. A new layout like that would require a pass by the designer, but I'm pretty sure this wasn't your intention and is probably way outside the scope of this PR.

Because this PR affects the look and feel of the site, and especially because it affects the landing page, it has a much steeper hill to climb than other PRs. Do not be discouraged, however. If you believe some improvement can be made, I want to hear your thoughts.

**Comment by kindasneaki** [comment]
No worries on the criticism other then most of the stuff pointed out was already in the site and is now just getting exposed. My main goal when starting this was mainly I didn't agree with the hamburger menu showing up at 1500px on desktop as I think the buttons in the hamburger menu are too large.

Some things to note:
1.  I can remove the header logo from changing size.
2. the header resizing wasn't my doing but I agree it shouldn't be there.
3. The third layout was already there but I guess was removed when it switches to mobile view so that is not intentional.
4. I'm totally fine if none of this gets in but I think adding the hamburger menu needs a second look through.

**Pull request closed without merging**
