### PR TITLE
Pokémon Red and Blue: Adding Spanish Setup Guide

### PR DESCRIPTION
**Pull request by ShinyNT**
## What is this fixing or adding?
Adding a spanish setup guide for Pokémon Red and Blue, based off the current english guide.

## How was this tested?
Translations don't get tested, but I proofchecked it a few times to ensure everything is correct. I also asked advice in #archipelago-dev discord channel to clear up doubts and whatnot, especially the reference format in the init.py file, which I think I got it right (and someone in the channel said it was fine too)

### CODE REVIEW

**Comment by ShinyNT** [comment]
ok I didn't mean to do that, I messed up sorry (not sure if it actually affects something though)
image

**Review by eudaimonistic — APPROVED** [review]
While I'm not a native speaker, I have an intermediate level of Spanish reading and comprehension.  This entire translation reads naturally and contains the original information faithfully.  Lines 73/74 could use 'por' instead of 'for', but that's the largest nitpick I could find.  Looks good!

**Comment by ShinyNT** [comment]
> While I'm not a native speaker, I have an intermediate level of Spanish reading and comprehension. This entire translation reads naturally and contains the original information faithfully. Lines 73/74 could use 'por' instead of 'for', but that's the largest nitpick I could find. Looks good!

just realized it looks like I actually forgot to translate those lines at all lmao, I'm sorry
can I still make a new commit while the pr is open?

**Review by LegendaryLinux — APPROVED** [review]
Just ran the whole thing through an auto translator to make sure it looked reasonable. Looks good to me.

**Pull request merged**
