### PR TITLE
WebHost: save datatables state

### PR DESCRIPTION
**Pull request by Berserker66**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
enables https://datatables.net/reference/option/stateSave so that our tables remember the user preferred sorting order on the tables.

## How was this tested?
A little on user content

### CODE REVIEW

**Review by recklesscoder — COMMENTED** [review]
Tested it and it seems to work. To my surprise, separate preferences are stored per tracker page (per URL).

As a result, every visited tracker page stores ~884 bytes of data, which means a Firefox's 5 MB local storage limit would be full after visiting ~5800 different tracker pages. However, if nothing else uses local storage, only this feature should break, and users can fix it by clearing cookies or specifically clearing local storage. Not sure what the best stance on this is.

**Comment by black-sliver** [comment]
> As a result, every visited tracker page stores ~884 bytes of data, which means a Firefox's 5 MB local storage limit would be full after visiting ~5800 different tracker pages.

Pretty sure that 5MB limit is not correct anymore. However browsers are free to pick any limit, so trashing local storage is not too good.

> However, if nothing else uses local storage, only this feature should break, and users can fix it by clearing cookies or specifically clearing local storage. Not sure what the best stance on this is.

Cache for the settings pages is also in local storage, so those two compete for space.

Datatables record a timestamp, so we could evict old data from the local storage. I would say it's up to berserker if we want to implement that right away, or open a TODO in issues and hope we'll get around to it one day.

**Comment by Berserker66** [comment]
I wonder if we can make the trackers share state

**Comment by recklesscoder** [comment]
> > As a result, every visited tracker page stores ~884 bytes of data, which means a Firefox's 5 MB local storage limit would be full after visiting ~5800 different tracker pages.
> 
> Pretty sure that 5MB limit is not correct anymore.

It turns out local storage always stores UTF-16 encoded strings, and I should correct my statement to this: Every visited tracker page stores ~884 characters = ~1768 bytes of data. which means the 10 MB local storage limit used by most current browsers would be full after visiting ~5800 different tracker pages. ([Here](https://arty.name/localstorage.html) is a simple page to check your browser's local storage limit.)


> I wonder if we can make the trackers share state

The [documentation for stateSave](https://datatables.net/reference/option/stateSave) has a simple example that shows how to do that.

**Comment by Berserker66** [comment]
What would a table's "DOM ID" be? What would one look like for our trackers vs. say user content?

**Comment by recklesscoder** [comment]
The DOM ID of a table is what's in the id attribute of the table HTML element. Most of the tables on the AP site don't specify any DOM ID, but it seems DataTables auto-generates IDs so it can differentiate them. Since those IDs are based only on where a table appears in the document (`DataTables_Table_0`, `DataTables_Table_1`, etc), if a page has tables that only appear sometimes, we should manually assign meaningful IDs to avoid DataTables mixing up their settings storage.

Anyhow, independent of the automatic ID question, it seems by default DataTables uses a local storage item named `DataTables_${settings.sInstance}_${location.pathname}` for each table, where `settings.sInstance` is the table's DOM ID and `location.pathname` is the current page (e.g., `/tracker/lQlr6mkKQ8qH6091TNOzfQ/0/1`).
So, for example, to make all the tracker pages share state, you could add the following lines after the `stateSave: true,` you inserted in `tracker.js`:
```js
stateSaveCallback: function(settings,data) {
    localStorage.setItem(`DataTables_${settings.sInstance}_/tracker`, JSON.stringify(data));
},
stateLoadCallback: function(settings) {
    return JSON.parse(localStorage.getItem(`DataTables_${settings.sInstance}_/tracker`));
},
```
Considering this would mix the MultiWorld tracker page and per-slot tracker page, which have completely different tables, it would be best to also add DOM IDs to all affected tables. (An uglier, less future-proof alternative would be to make the above snippet figure out what kind of page it is on and add that to the storage item name.)

**Comment by recklesscoder** [comment]
Here's a patch that should make this PR ready to go. It adds DOM IDs to all relevant tables and adds the above snippet for unifying the settings of all tracker pages.

[0001-WebHost-Fix-DataTables-local-storage-keys.zip](https://github.com/ArchipelagoMW/Archipelago/files/9951269/0001-WebHost-Fix-DataTables-local-storage-keys.zip)

**Comment by Berserker66** [comment]
Yeah if you make a PR that targets the branch this PR originates from, we can sqash/rebase your PR into that branch and then rebase into main from there.

**Comment by Berserker66** [comment]
@ThePhar or @LegendaryLinux might have to review it from here

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
