### PR TITLE
Noita: Add more location groups, capitalize existing ones

### PR DESCRIPTION
**Pull request by ScipioWright**
## What is this fixing or adding?
Adds location groups for each of the biomes to the game, to make it easier to exclude biomes that the player does not like. Also capitalizes the existing location groups since that looks like it's more standard.

## How was this tested?
Generating, doing /location_groups or whatever the command is in text client, hinting some of them

## If this makes graphical changes, please attach screenshots.
N/A

### CODE REVIEW

**Review by hatkirby — APPROVED** [review]
Code LGTM.

**Comment by heinermann** [comment]
ltype isn't referenced elsewhere correct? Otherwise looks fine I guess.

**Review by heinermann — APPROVED** [review]

**Review by heinermann — APPROVED** [review]
Thought so

**Review by NewSoupVi — APPROVED** [review]
Looks correct

**Pull request merged**
