### PR TITLE
[Timespinner] Rename flag and add tiered loot settings

### PR DESCRIPTION
**Pull request by TriumphantBass**
Companion PR to https://github.com/JarnoWesthof/TsRandomizer/pull/91 and https://github.com/JarnoWesthof/TsRandomizer/pull/92

- Renames Facebook Mode to reduce player confusion
- Adds settings related to loot rarity for local enemy drops

CC @JarnoWesthof

### CODE REVIEW

**Comment by JarnoWesthof** [comment]
I am ok with this, I guess I'll release a client tomorrow that supports these settings

**Comment by black-sliver** [comment]
Wondering if changing the option name is a good idea. I think the description is what was unclear? I'm on board with whatever Jarno decides though.

**Comment by TriumphantBass** [comment]
Internally within the Timespinner discord there was a conversation about it (sparked by community comments about the name being a bit confusing), that essentially boiled down to "the tenuous link from Oculus Ring -> Oculus Rift -> Facebook mode was made even more tenuous by the product now being Meta Rift", and this name came out of this as a more succint name (i.e. using the eye orb's ring to sleuth)

**Comment by black-sliver** [comment]
I'm not at all saying that the old name is good or the new name is bad, but it makes old yamls fail and I think the new client should be compatible to both names to allow a smooth transition.

What's missing from the PR is setting required_client_version to avoid connection with an old client (that does not know the new name), but for that we first need that client from jarno

**Comment by JarnoWesthof** [comment]
Meh Timespinner isnt so strickt on versions, wurse case is that you enable it but its not enabled. like not a massive deal right

**Comment by CaitSith2** [comment]
From a racing point of view though, one using the old client would have a competitive edge by being able to sequence break the secret passage checks because the client wasn't aware that it was supposed to lock you out of those checks.

**Review by Ijwu — APPROVED** [review]

**Comment by Ijwu** [comment]
I didn't read the discussion, I don't really care. I approve of the code as-is.

**Comment by Berserker66** [comment]
> I am ok with this, I guess I'll release a client tomorrow that supports these settings

Did this occur? Is this usable?

**Comment by Jarno458** [comment]
Yes it's in the 1.8 release

**Pull request merged**
