### PR TITLE
Update swedish minecraft set up guide version of mod 

### PR DESCRIPTION
**Pull request by Joethepic**

### CODE REVIEW

**Comment by Joethepic** [comment]
that is kinda what i saw as well but unfortunately i don't know Swedish that's why i only changed the version name. i could try to do it with something like google translate but that might not be the most accurate

**Comment by Ijwu** [comment]
I am of the opinion that we should either remove the guide if it is outdated, or find a swede. If we can improve this and bring it up to date with latest client info, we absolutely should. Otherwise it's in a halfway point of incorrect and correct.

**Comment by KonoTyran** [comment]
@Berserker66 you were the original one to add this file, with credit to someone named "Albinum", I don't see anyone in the discord with this name, is it possible to reach out to them to get an updated version? If not I'm in favor of just removing it.

**Comment by Berserker66** [comment]
Sorry, I do not remember.

**Comment by KonoTyran** [comment]
then @Joethepic I'm going to say just remove the tutorial for now. as we don't have any way to keep it up to date.

**Comment by Joethepic** [comment]
Understood makes sense

**Comment by KonoTyran** [comment]
You still have a conflict with a deleted file that needs to be fixed. Once that is solved we can merge it.

**Comment by Joethepic** [comment]
I will fix that tomorrow thanks for looking it over

**Pull request closed without merging**
