### PR TITLE
Pokemon Emerald: Add event ticket locations to client data store flags

### PR DESCRIPTION
**Pull request by Zunawe**
## What is this fixing or adding?

Adds the event ticket locations to the `pokemon_emerald_keys_` data storage key so that they can be autotracked even if they're not randomized.

This pushes the key over 32 bits, but that's probably not an issue for anyone.

## How was this tested?

It wasn't except to run the launcher, which should verify that these keys have location data. I'll hand this PR over to the tracker devs to verify.

### CODE REVIEW

**Comment by Zunawe** [comment]
Added an event flag for the `pokemon_emerald_events_` key, since it's a small, related change.

**Review by Exempt-Medic — APPROVED** [review]
Merged into main, generated and connected.

**Comment by Zunawe** [comment]
Added a few more flags at the request of the tracker devs

**Comment by vyneras** [comment]
Tracker dev here, I have verified that that these changes worked for autotracking the new events and key items

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
