### PR TITLE
Core: Let location name groups work with /hint_location

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
location name groups didn't work with /hint_location. now they do

## How was this tested?
ran the command with a group and with a location name

## If this makes graphical changes, please attach screenshots.
Screenshot_10

### CODE REVIEW

**Review by qwint — APPROVED** [review]
will ctx.all_location_and_group_names[game] always be populated if ctx.all_location_and_group_names is populated?
or was the previous elif passing in 'game' just to get some result back from the method?
it seems like from the subsequent 'else' that we would want to confirm the game exists.


Else, the handling of location groups looks good, and did some testing on Doom 1993 hinting using the text client (ex. `!hint_location Tower of Babel (E2M8)`) and it
* hinted a random location in the group and deducted hint points for one hint
* prompted me that there were more hintables
* on repeat hints gave me new hints until i ran out of points
* and then with more points hinted until i ran out of locations in the group, and then repeated the relevant hints while deducting no hint points

as expected.

**Comment by alwaysintreble** [comment]
> will ctx.all_location_and_group_names[game] always be populated if ctx.all_location_and_group_names is populated? or was the previous elif passing in 'game' just to get some result back from the method? it seems like from the subsequent 'else' that we would want to confirm the game exists.

the previous behavior was only looking at the location names of the game and didn't include the groups. the second elif checking for the game first is because of older multidata that might not have location_name_groups. the game will always be in the "all" group,


> Else, the handling of location groups looks good, and did some testing on Doom 1993 hinting using the text client (ex. `!hint_location Tower of Babel (E2M8)`) and it
> 
> * hinted a random location in the group and deducted hint points for one hint
> * prompted me that there were more hintables
> * on repeat hints gave me new hints until i ran out of points
> * and then with more points hinted until i ran out of locations in the group, and then repeated the relevant hints while deducting no hint points
> 
> as expected.

`!hint_location` already works on current release, this is specifically for `/hint_location` from the server/admin, which was missed when implementing `location_name_groups`

**Comment by qwint** [comment]
ah beans, will retest tomorrow sometime using the right commands

But I don't think you understood my first comment
`elif self.ctx.location_names_for_game(game) is not None:`
became
`elif self.ctx.all_location_and_group_names:`
so it is no longer checking that the game is a valid key for the lookup table (even though the lookup table changed), I'm not certain that is necessary, but the 'else' it falls back on mentions that the game is unknown and that the user should hint by ID instead.
```
            else:
                self.output("Can't look up location for unknown game. Hint for ID instead.")
                return False
```
this looks to me like the game _could_ be unknown to the server and could fail to lookup. and if that is true we'd want to fail on the right level to get the right error message.

**Comment by alwaysintreble** [comment]
> this looks to me like the game _could_ be unknown to the server and could fail to lookup. and if that is true we'd want to fail on the right level to get the right error message.

ah i see yeah i did misunderstand. i don't think that code path can actually be hit, since the client's game has to be in the current multiworld's games in order for them to even connect to a slot, but it's probably better to not remove fallback in case that changes.

**Review by qwint — APPROVED** [review]
properly retested with server-side `/hint_location Player1 {location_group}` hints, and all avaliable hintables in a group would be hinted and/or displayed as expected

**Review by Exempt-Medic — APPROVED** [review]
Merged into main and tested that hints now worked with location groups

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
