### PR TITLE
Pokemon Red and Blue: Flash and Silph Scope based logic additions

### PR DESCRIPTION
**Pull request by KamekoSkye**
## What is this fixing or adding?
Added an option to be able to pass the ghost in Pokemon Tower 6F with a purchasable Poke Doll.
Added an option to not require HM05 Flash to pass through Rock Tunnel. Also included in the option is the ability to also do checks without Flash (if any)

## How was this tested?
Multiple seeds generated with each potential option, making sure all possible cases are generated.

### CODE REVIEW

**Comment by Alchav** [comment]
I still think rock tunnel in the dark should be all or none

**Comment by SonicRPika** [comment]
I've made the change so that you either need Flash for everything, or for nothing

**Comment by Alchav** [comment]
> I've made the change so that you either need Flash for everything, or for nothing

The access rules on the individual locations should be unnecessary then

**Comment by SonicRPika** [comment]
Didn't think of that. It has been updated

**Comment by Berserker66** [comment]
@Alchav looks good?

**Comment by Alchav** [comment]
I've made substantial changes on my dev branch that would likely make a lot of this incompatible. I don't like how some of these options' descriptions are worded, and I'd like to just implement similar options for these myself for my next big update.

**Comment by KamekoSkye** [comment]
No worries, it has been a while.

**Pull request closed without merging**
