### PR TITLE
The Witness 0.3.4 features

### PR DESCRIPTION
**Pull request by NewSoupVi**
New options:

- Shuffle Doors: Many doors in the game will open on their own upon receiving an item ("key").
- Variant - Shuffle Door/Control Panels: Many panels in the game that open doors or control devices in the world will be off until receiving their respective item ("key").
- Shuffle Lasers: Lasers no longer activate by solving the laser panel, instead you will get an item that activates the laser.
- Shuffle Symbols: Now that there is something else to shuffle (doors / door panels), you can _turn off_ Symbol Rando.
- Shuffle Postgame (replaces "Shuffle Hard"): The randomizer will now determine by your settings which panels are in the "postgame" - Meaning they can only be accessed after you can complete your win condition anyway.

### CODE REVIEW

**Comment by NewSoupVi** [comment]
There is currently nothing that prevents a player from shuffling nothing and getting a game that is beatable from the start without any progression items. Should I avoid this somehow? What would be a good way?

**Comment by black-sliver** [comment]
> With symbol rando being something you can turn off now, there is nothing that prevents a player from shuffling nothing and getting a game that is beatable from the start without any progression items. Should I avoid this somehow? What would be a good way?

(SoE has a high chance of low sphere count.) I personally think that should be solved in core, but there was no real effort to implement "reverse progression balancing" yet. The only way to solve it currently is by locking items that are definitely required into locations that are definitely not accessible from the start. I would say the course of action depends on the likelihood of such a "free" seed being rolled.

**Comment by NewSoupVi** [comment]
> This is a case of 0 Items and 0 Locations, correct? Since it wouldn't interact with a multiworld at all, I'd propose to throw an explaining exception if such a setting is attempted with playercount>1

It'd be X locations at only junk.

**Comment by NewSoupVi** [comment]
Essentially, there is no "base randomization" in this game that I'd always want to force on. I can totally see someone playing with symbol rando and not door rando, and I can totally see someone playing with door rando and no symbol rando. But that means having **neither** is an option, which then means there are no progression items & nothing is locked

**Comment by NewSoupVi** [comment]
If I throw an exception, where would that be? Just, anywhere?

**Comment by black-sliver** [comment]
> If I throw an exception, where would that be? Just, anywhere?
in generate_early all the options are set up

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
