### PR TITLE
LADX: enable upstream options

### PR DESCRIPTION
**Pull request by threeandthreee**
## What is this fixing or adding?
There are some upstream settings that just needed options entries. This should come after the logic updates (https://github.com/ArchipelagoMW/Archipelago/pull/3963) because of hard mode, not sure if current logic has all the correct handling of it, and not much point in checking.

### Hard Mode
- **[None]**
- [Oracle] Less iframes and health from drops. Bombs damage yourself. Water damages you without flippers. No piece of power or acorn.
- [Hero] Switch version hero mode, double damage, no heart/fairy drops.
- [One hit KO] You die on a single hit, always.

### Quickswap
Adds that the select buttons swaps with either A or B. The item is swapped with the top inventory slot. The map is not available when quickswap is enabled.

### Text Mode
- [Normal]
- **[Fast]** Makes text appear twice as fast
- [No-Text] Removes all text from the game
This one has been defaulted to **Fast**, as upstream does. Also opted to make this a hidden option but will be getting community feedback on that. No-text might be problematic, will need to test directly and possibly disable.

### Low HP Beep
Slows or disables the low health beeping sound.

### No Flash
Remove the flashing light effects from Mamu, shopkeeper and MadBatter. Useful for capture cards and people that are sensitive for these things.

This has been defaulted on (matching upstream) and hidden, community feedback pending.

## How was this tested?
Tested that the settings work and don't break anything, but not every arrangement. No-text needs to be tested specifically.

### CODE REVIEW

**Comment by Exempt-Medic** [comment]
What's the reason for the visibility values?

**Review by SushiKishi — APPROVED** [review]
Been able to generate successfully with this option in place. It's not something I'd take advantage of, but the additional options are nice for those who want them.

OHKO in particular changes routing and difficulty options on its own, as LADX has a fair amount of damage boosting and hit-this-trick-or-you-fall-and-die-now tricks, but I've seen plenty of discussion in the Discord around logic changes that need to be made.

I was thinking of suggesting certain tricks or paths needed to be bumped up a difficulty rank (Normal > Hard > Hell). It's not a great example, but for example, getting into the area behind Richard's house "backwards" requires crossing the pit, and now failure doesn't just cost you a few seconds, but it just straight up kills you.  But the difficulty change is baked into selecting OHKO -- you know what you're getting into there. Hard is, well, hard, and Hell is frustrating, so OHKO Hard is frustrating and OHKO Hell is not for the faint of heart.

**Review by palex00 — APPROVED** [review]
This PR was tested as part of a Beta apworld that was used in three dedicated Test Asyncs, as well as dozen of normal Syncs. I have also personally run 200 test generations which succeeded.

We have also done polling on what users want, etc. which [can be found here](https://docs.google.com/forms/d/e/1FAIpQLSdLJ_j9RiS5TRjtovV_O-HwPEJMygLTAFotw3AdlUxfMCByPQ/viewanalytics)

The new feature has worked as expected and other stuff does not seem impacted.
This is also such a QOL change. Ugh, yes.

**Comment by threeandthreee** [comment]
the PR this was waiting on has been merged, `waiting-on: other` can be removed

**Comment by Exempt-Medic** [comment]
I feel like TextMode and NoFlash would make sense in the "visuals & sound" option group. I also wonder if Low HP Beep should be in that group instead?

**Review by Exempt-Medic — APPROVED** [review]

**Pull request merged**
