### PR TITLE
SDV: Use the pre-existing cache in location creation

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
Fixes SDV failures. should also speed it up since it uses the pre-existing cache instead of just pretending it doesn't exist.

## How was this tested?
unit tests succeed now.

### CODE REVIEW

**Comment by agilbert1412** [comment]
What kind of failures?

**Review by agilbert1412 — APPROVED** [review]
Could you elaborate on what were the failures that this fixes?

**Comment by alwaysintreble** [comment]
The failures were for a specific branch that berserker is currently working on. This doesn't fix any failures in regards to main but it does offer ~5% speed increase

**Review by black-sliver — APPROVED** [review]
lgtm

**Pull request merged**
