### PR TITLE
WebHost: Fixed warning ".gitignore dropped, as it has no valid sprite data."

### PR DESCRIPTION
**Pull request by Jarno458**
## What is this fixing or adding?
Fixed the warning ".gitignore dropped, as it has no valid sprite data." that is logged when starting up the WebHost

## How was this tested?
Just starting the WebHost with the line changed

### CODE REVIEW

**Comment by Berserker66** [comment]
This is kind of my code, so I shouldn't approve this.

**Comment by ThePhar** [comment]
Would it be better to be more general and just ignore anything that doesn't end in `.zspr`? Should prevent OS files from causing an issue too. (*cough* MacOS .DS_Store *cough*)

**Comment by Berserker66** [comment]
startswith "." might be good

**Comment by black-sliver** [comment]
i mentioned it already wrt /worlds/: ignoring files starting with `.` is expected by Linux users - probably also mac users - because they are hidden. So +1 for startwith

**Comment by Jarno458** [comment]
Oke ill update it

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
