### PR TITLE
Core: Change generic "random" to "mystery"

### PR DESCRIPTION
**Pull request by t3hf1gm3nt**
## What is this fixing or adding?
This changes the generic "random" option used for all game settings, and it's associated triangle distribution and range options, to "mystery" instead. This seems to be a better defined word to use for the typical use case for these options and allows for games to define "random" options (mostly will help implementing existing randomizers into AP in the future).

## How was this tested?
Passed all tests and generated several games with one yaml of each game (minus FF) with most if not all options set to "mystery", with a few tests of the different triangle distribution and range options (used in the Hollow Knight yaml in particular) with no errors.

### CODE REVIEW

**Comment by t3hf1gm3nt** [comment]
Did want to note: the main thing I couldn't confirm myself is that I properly changed how the mystery option is displayed on the webhost's settings pages (as I still haven't been able to successfully start a local webhost), but pretty sure the edits I made to WebHostLib/options.py (lines 121 and 122) should be what I needed to do to change that?

**Comment by t3hf1gm3nt** [comment]
I had asked black-sliver previously about that change. Think they said upstream that difficulty option is still called random. Didn't break any of my tests and even did a few more test generations soley with SoE and they genned fine. And i can't find any old usage of "mystery" in regards to SoE (or anywhere else for that matter) when looking through the updated code. But I'll trust black-silver finding what i missed if I did miss something.

**Comment by alwaysintreble** [comment]
haven't tested WebHost yet so that still needs to be done. Make sure you also update world api with this change.

**Comment by t3hf1gm3nt** [comment]
you're talking about line 227-228 right? guess i did overlook that one
i'll push a commit to change that one SOONtm

**Comment by t3hf1gm3nt** [comment]
*sigh* tried updating and think all the new game tests are using random or something, so now i gotta go find where they all did that

**Comment by ThePhar** [comment]
Congrats, I now broke this in merged PR #944. :)

**Comment by t3hf1gm3nt** [comment]
thankfully it was an easy fix? lol

**Comment by t3hf1gm3nt** [comment]
closed because (supposedly) the random button on the website makes this meaningless. im opening this again as soon as i see one report about people not understanding what "random" actually does though.

**Pull request closed without merging**
