### PR TITLE
Core: Add ability to disable some tags

### PR DESCRIPTION
**Pull request by Jarno458**
## What is this fixing or adding?
A new server option in the host.yaml: `disabled_client_tags` a list of clients tags that the server will refuse

This can be used to for example block DeathLink from being used:
```
  disabled_client_tags:
    - Deathlink
```

Example of tags that can be disabled:

- **DeathLink**
- **Tracker**
- <sup>BK_Sudoku<sup>
- **MC35**

## How was this tested?
Tested locally with both the **DeathLink** and <sub>BK_Sudoku</sub> with two different clients, tested both from host.yaml aswel as commandline. There where no tests done on the perservation of this setting when you reload an multiworld save

## Breaking Change
A new Error code was added to the ConnectionRefused, and ConnectUpdate can now yield an InvallidPacket in an additional case. However, neither of this breaks anything unless you specifically start to disable certain tags

### CODE REVIEW

**Comment by Berserker66** [comment]
@t3hf1gm3nt is this what you want?

**Comment by t3hf1gm3nt** [comment]
This does what I wanted for my concerns about being able to connect to certain games with BK Sudoku. However, there is a theoretical problem that could arise using this system, specifically by using this to block the DeathLink tag and having a game that has no way of toggling DeathLink, if said game had a yaml submitted with it turned on. I think this is an issue only with SM64, but is also an issue that could only be fixed outside of this PR and even this repo, as SM64 would need a different way of handling DeathLink (I always thought it should be a launch parameter for that anyway) . This PR is probably fine as is and if people happen to run into this exact situation, they could just make sure the SM64 player turns off DeathLink in their yaml and reroll.

**Comment by Jarno458** [comment]
The same issue also exist for Timespinner that always connects as DeathLink even if its off. but oh well, i can fix that in timespinner someday

Tags are also the only way to identify bk sudoku as well it never connects under game Sudoku

**Comment by t3hf1gm3nt** [comment]
Yeah I get that. As I said, this PR is probably fine as is because people could just reroll if these niche situations arise. However if people did want to use this to block DeathLink, those games would need to be updated on how it handles the DeathLink tag

**Comment by Berserker66** [comment]
Personally I'd still prefer at least one round of async where we ban connecting it to worlds not owned by you and see if the community behaves.

**Comment by t3hf1gm3nt** [comment]
We've been doing this for how long? You know they will not. I'll admit though that I am a bit biased as I don't see much point to BK Sudoku in the first place, but it is very much in opposition to what an async is supposed to be about.

**Comment by Jarno458** [comment]
Well we could explicitly state people not to use bk_sudoku on the next async, just like it's also explicitly stated not to use archipidle

**Comment by t3hf1gm3nt** [comment]
We can stop people using Archipidle by refusing Archipidle yamls during submission time. However, we can't stop people from connecting with BK Sudoku currently. That's the issue that brought about this PR in the first place.

**Comment by Jarno458** [comment]
Yes but it seems Beserker still beleives in the good of this community and id like to beleive in that aswel

**Comment by t3hf1gm3nt** [comment]
I would love to believe in the good of the community as well but there have been enough bad eggs doing bad things even in the most recent one for me to believe. But you know what? Maybe its better we get the community's opinion itself. I'll make a post in the discord asking what people want.
I still think this PR is perfectly fine as is though. And when it comes to the big async, in the end Berserker has full control on whether this functionality is even used or not anyway since it needs to be activated by the roller.

**Comment by t3hf1gm3nt** [comment]
Im fine with closing this. The concerns I had that brought this about seem to have been wrong.

**Comment by Berserker66** [comment]
> Personally I'd still prefer at least one round of async where we ban connecting it to worlds not owned by you and see if the community behaves.

My sentiment stands.

**Pull request closed without merging**
