### PR TITLE
The Witness: Fix potential caching issue

### PR DESCRIPTION
**Pull request by NewSoupVi**
Today I learned that lru_cache does *not* take `self` into account for an instance method.

This might lead to weird slot bleed issues with Witness seeds.
Don't have any reports, but should still be fixed

### CODE REVIEW

**Comment by NewSoupVi** [comment]
`Utils.cache_self1` has been considered, but https://github.com/ArchipelagoMW/Archipelago/pull/2698 changes that function to have an extra arg, so it'd just be changed back again anyway.

**Comment by Berserker66** [comment]
I have no idea if your approach works, but we have cache_self1 in  Utils for this.

**Comment by NewSoupVi** [comment]
Decided to use `cache_self1` after all and just deal with the consequences on the other PR somehow

**Comment by NewSoupVi** [comment]
I have a better solution to the issue in https://github.com/ArchipelagoMW/Archipelago/pull/2698.

**Pull request closed without merging**
