### PR TITLE
Docs: Revise all docs mentioning Lua in EmuHawk (which are in English), and other misc. corrections

### PR DESCRIPTION
**Pull request by YoshiRulz**
## What is this fixing or adding?

- https://github.com/ArchipelagoMW/Archipelago/commit/e183e166b1b7b65bf24dda67d91bd90a6183c1c7: Updates old links to TASVideos.org (`http://tasvideos.org`, `*.html`).
	- There are many other HTTP links in docs still. I suggest you update those where possible.
- https://github.com/ArchipelagoMW/Archipelago/commit/939e163bb86cf71daac5b397b44b4fdd418416a2: Changes wording of tutorials for loading Lua scripts in EmuHawk to prioritise the drag+drop method over launching a file picker from the Lua Console.
	- Should reduce troubleshooting as noted in TASEmulators/BizHawk#3650.
	- This would have taken much less time if there wasn't so much duplication. The site seems to use Flask? Consider using Jinja includes for blocks of text duplicated across multiple pages.
- https://github.com/ArchipelagoMW/Archipelago/commit/6d1f0b7c8bfc6b8c3f01997d3dc9d6abfd207e9f and https://github.com/ArchipelagoMW/Archipelago/commit/5877618a5eadd9279326d8afd8eb8b9182ea2a21: Minor branding nitpicks.

## How was this tested?

N/A (URIs and error messages were untouched, identifiers were replaced across the whole codebase).

### CODE REVIEW

**Comment by black-sliver** [comment]
Thanks for the PR!

Re duplication/jinja. Markdown was a deliberate choice back in the day to allow easier modification by less tech-savvy people. Jinja requires a local webhost while markdown can be pasted into a live preview and rendered on github.
The solution for duplicate text would be to put common text into a common markdown, but nobody found the time to do so yet.

Can you maybe elaborate here on where to use "EmuHawk" and where to use "BizHawk"? I would prefer to put "BizHawk" everywhere to avoid confusion, but if this is incorrect, I'd like to know exactly why.

Re branding nitpicks
branding

**Comment by black-sliver** [comment]
By the way

> CBB

is on the same scale of F U as your #NotOurProblem tag. If you don't think it's necessary to post a screenshot, just don't.

**Review by shananas — APPROVED** [review]
Changes LGTM. most of it being BizHawk Capitalization and changing references to use EmuHawk . Other big change preferring the user to drag and drop the script instead of loading through the BizHawk file picker.

**Review by t3hf1gm3nt — APPROVED** [review]
While i think the capitalization and references to EmuHawk are unecessary, I'm not gonna argue with one of the BizHawk devs about that. The rest of the changes to the guide are what I'm approving and desire to have added, as it adds the second method of loading scripts and, more importantly IMO, adds an update we forgot to do when we added support for 2.9+ about the lua core switching only being required in older BizHawk versions.

**Review by black-sliver — APPROVED** [review]
Changes render correctly on webhost. This was posted to our Discord for public review and no concerns were raised. Relaying the approval of shananas and figment (I personally don't use BizHawk) and merging before we get more conflicts.

**Pull request merged**
