### PR TITLE
WebHost: add Status to MultiTracker

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
add Status to MultiTracker
currently the only way to see if a slot is actually completed is to have at least one LttP world and see if those worlds have a triforce.

## How was this tested?
locally

## If this makes graphical changes, please attach screenshots.
image
image

### CODE REVIEW

**Comment by Berserker66** [comment]
I was considering that, but the code text makes for bad user facing text.

**Comment by alwaysintreble** [comment]
This will also show incorrect data without #1358. i.e. if two people co-op a slot and someone disconnects it'll show disconnected.

**Comment by black-sliver** [comment]
> I was considering that, but the code text makes for bad user facing text.

The filter could substr and capitalize, but "Goal" would still need to be hard-coded to show up as intended.

**Review by black-sliver — APPROVED** [review]
Did not test, code looks good. I still very much think the dict should not be hard-coded in a template since it will haunt us to the end of our days

**Pull request merged**
