### PR TITLE
Lua: Deduplicate Lua connector dependencies

### PR DESCRIPTION
**Pull request by wbsch**
In data/lua:

```
$ sha1sum */core.dll
518bd23ab095bfb4cf8577d8f216281199b57c55  FF1/core.dll
518bd23ab095bfb4cf8577d8f216281199b57c55  OOT/core.dll
518bd23ab095bfb4cf8577d8f216281199b57c55  PKMN_RB/core.dll
518bd23ab095bfb4cf8577d8f216281199b57c55  TLoZ/core.dll
```

```
$ sha1sum */socket.lua
0c65a5d3745b002dec6137f36b1a785a14a85de4  ADVENTURE/socket.lua
0c65a5d3745b002dec6137f36b1a785a14a85de4  FF1/socket.lua
0c65a5d3745b002dec6137f36b1a785a14a85de4  OOT/socket.lua
0c65a5d3745b002dec6137f36b1a785a14a85de4  PKMN_RB/socket.lua
0c65a5d3745b002dec6137f36b1a785a14a85de4  TLoZ/socket.lua
```

```
$ sha1sum */json.lua
62709d8adf44e0a2e02f4171915860f40c6fffc5  ADVENTURE/json.lua
62709d8adf44e0a2e02f4171915860f40c6fffc5  FF1/json.lua
62709d8adf44e0a2e02f4171915860f40c6fffc5  OOT/json.lua
181bf123666eb4eb3196bb32a825b8ae0af2e5d0  PKMN_RB/json.lua
62709d8adf44e0a2e02f4171915860f40c6fffc5  TLoZ/json.lua
```

```
$ diff -u OOT/json.lua PKMN_RB/json.lua
--- OOT/json.lua	2023-03-23 21:46:18.306433303 +0100
+++ PKMN_RB/json.lua	2023-03-23 21:46:18.306433303 +0100 @@ -15,6 +15,10 @@

 local encode

+function error(err)
+	print(err) +end
+
 local escape_char_map = {
   [ "\\" ] = "\\\\",
   [ "\"" ] = "\\\"",
@@ -60,7 +64,12 @@
       n = n + 1
     end
     if n ~= #val then
-      error("invalid table: sparse array")
+      print("invalid table: sparse array")
+	  print(n)
+	  print("VAL:")
+	  print(val)
+	  print("STACK:")
+	  print(stack)
     end
     -- Encode
     for i, v in ipairs(val) do
```

All libraries used by the connectors are exact copies; the only exception to this is Pokemon, where debugging info was left in json.lua.

Assuming this is not intended, move all dependencies to the base folder and adjust docs accordingly.

While at it, rename connectors to connector_* in order to keep readability of the folder high.

## How was this tested?
It wasn't; I checked for hardcoded paths to these files and adjusted the docs, but it is entirely possible I might have missed something.

### CODE REVIEW

**Comment by Alchav** [comment]
I brought this up while I was working on Pokémon R/B and based on the responses I got, I decided not to touch them

Screenshot_20230323-182016_Discord

**Comment by black-sliver** [comment]
What berserker said. Our goal was to go through SNI to abstract away any bizhawkiness.
Given @Berserker66 's statement above, I'll let him decide if the move to SNI is taking too long or not. Would've been nice to push that before adding more clients.

**Comment by wbsch** [comment]
This is why i renamed the files to connector_*.lua - it's easier to quickly skim the folder this way.

Not breaking user workflow twice, as Berserker mentioned regarding the SNI change, is a valid concern obviously.

I'd posit that the SNI change might be further out than expected, and that this PR still leads to a cleaner layout in the meantime. I'm fine with re-basing #1579 on the old folder structure and adding the 6th copy of core.dll, socket.lua and json.lua though.

**Comment by Berserker66** [comment]
I'd defer to the maintainers of the affected worlds here. As I said, I'd like to keep the amount of workflow breakage low, but if world maintainers want this cleanup now then I won't say no either.

**Comment by t3hf1gm3nt** [comment]
Rosalie should also chime in for TLOZ, but I'm ok with this and did a quick test that it didn't break anything in TLOZ at least

**Comment by Alchav** [comment]
I'm fine with whatever

**Comment by Rosalie-A** [comment]
> @Rosalie-A should also chime in for TLOZ, but I'm ok with this and did a quick test that it didn't break anything in TLOZ at least

Haven't gotten a chance to test anything myself, but if Figment says it works I trust them, and anyway this seems to be just cleaning things up as opposed to a functional change, so I'm down with that.

**Comment by wbsch** [comment]
This was included and merged in #1685, so I'm closing this PR.

**Pull request closed without merging**
