### PR TITLE
WebHost: Expose name groups through the weighted-settings UI

### PR DESCRIPTION
**Pull request by nex3**
## What is this fixing or adding?

It's already possible for worlds to define `location_name_groups` and
`item_name_groups` that users can use in their YAML files anywhere
that takes a location or item list, respectively. This PR exposes this
capability in the web UI as well, including the name groups as a
separate section at the beginning of item and location lists.

## How was this tested?

Manually tested by defining groups in the Dark Souls III world,
generating YAML files, and so on.

## If this makes graphical changes, please attach screenshots.

image

### CODE REVIEW

**Comment by LegendaryLinux** [comment]
So you manually created a group in the Dark Souls 3 `world` to test this? I checked out this PR and that group does not exist for me. I presume your manually created group was just for testing on your end, then?

**Comment by nex3** [comment]
There's already one item group defined [here](https://github.com/ArchipelagoMW/Archipelago/blob/e3112e5d51abff42e2eae0e1102d2f60fcebae9f/worlds/dark_souls_3/__init__.py#L56-L61), but I also merged in https://github.com/ArchipelagoMW/Archipelago/pull/2309 and tested with those groups as well.

**Comment by LegendaryLinux** [comment]
Maybe I'm missing something. I've checked out your branch and confirmed the Dark Souls 3 item group exists in the branch in the world file, but the item group does not appear in my weighted-options page.

image

**Comment by nex3** [comment]
That's so odd! I see it right here, running against an unmodified checkout of [this commit](https://github.com/ArchipelagoMW/Archipelago/pull/2327/commits/da6b82ef5b490330adfc654a324791132b0a0541): 

image

Let me try merging the latest `main`.

**Comment by nex3** [comment]
Well, it looks like the latest `main` broke the weighted settings page, but #2408 should fix that. I've verified in a clean Codespace that this works as expected with that fix. Is there anything else you need from me here?

**Review by LegendaryLinux — APPROVED** [review]
Was finally able to verify this. Approved.

**Pull request merged**
