### PR TITLE
variable-progression-balancing

### PR DESCRIPTION
**Pull request by beauxq**
Recently, someone in our game thought the progression balancing was too heavy, so they turned it off...

...and then spent 2.5 hours in BK mode, from the very beginning.

We need more options for different amounts of progression balancing.

The option is now a range from ~0 to 20 with 10~ 0 to 99 with 50 being the default.
It tries to make sure you have this percentage of the max player's percentage of items available.

~It should be backwards compatible so all the old options that people have in their yamls for progression balancing still work.~
~(`true` or `on` set it to the default 50)~

### CODE REVIEW

**Comment by Berserker66** [comment]
Too heavy on which version? It was already reduced in strength recently, not released yet. 
Just mentioning as it might change the intended changes.
Also @espeon65536

**Comment by beauxq** [comment]
I guess the judgments that it was too heavy would have come from 0.2.5 and earlier.

Either way, this keeps the default that you had in the recent code (subtracting 0.1 from max), and also makes it configurable to be heavier or lighter.

**Comment by beauxq** [comment]
What was the threshold in 0.2.5?

**Comment by beauxq** [comment]
I see now the change in https://github.com/ArchipelagoMW/Archipelago/pull/300

That isn't a change from heavier to lighter. That's a change from a number of items to a percentage of items.

For Super Metroid (where the judgements that I heard came from, of "too heavy"), which has 100 items, this change would actually make it even heavier.
For example: If the max items available for a player is 36,
with the old system of 36 - 20 = 16, someone with less than 16 items available would get items moved to an earlier sphere.
With the new (before this PR) system of 0.36 - 0.10 = 0.26, then someone with less than 26 items available would get items moved.
That means players are even more likely to get items moved, making it more heavy.

I think this confirms the worry I had that even the range in this PR still can't get light enough.
The lightest possible (non-zero) progression balancing in this patch would just go back to what it was before this change from a flat 20 items, to a percentage.

**Comment by beauxq** [comment]
Did you consider taking a percentage of the max percentage, instead of of subtracting 0.1 from the max percentage?
I wondered whether that might be better.

**Comment by beauxq** [comment]
I think a percentage of the max percentage is what I might want to change this PR to.
It would be a range from 0 to 99. That would be the percentage of the max percentage.

I think 50 would be a good default.
If someone has access to 20% of their items, try to make sure I have at least 10% of my items.
If someone has access to 60% of their items, try to make sure I have at least 30% of my items.
I think that won't be a problem that it gets further away later, because I think most BK mode problems are near the beginning.

What do you think?

**Comment by espeon65536** [comment]
The actual purpose of switching to a percentage-based system is to reduce the effect that games of various sizes have on progression balancing. Under the old system, games with many locations such as Ocarina of Time combined with games with fewer locations such as Super Metroid would cause extreme frontloading of progression in SM, because OoT would always have more available locations than SM. Changing to a percentage-based system makes that no longer happen. 

The reason you would get "too heavy" judgements in SM is because of this reason. Consider a game with one ALttP player (216 locations) and one SM player (100 locations) for a simple example. After every sphere is processed, the ALttP player is very likely to have at least 20 more locations checked than the SM player, which would cause movement of SM progression -- but the ALttP player may not be much farther ahead, it's just that ALttP has more locations than SM. Since this happens for nearly every sphere, this is why progression balancing feels so frontloaded in smaller games. Your example assumes that the threshold value stays the same, but this would very likely not happen; since the threshold is now based on a percentage instead of absolute number of items, the larger games no longer hold an advantage in determining the threshold. 

The core problem here is that the progression balancing algorithm is fundamentally not very smart. It blindly moves items earlier in the progression without really caring about *which* ones it's moving, which is why progression balancing feels so strong -- it doesn't move only the items it needs to move to open locations. I changed it to use percentages as a simple temporary improvement while I think about algorithms that balance more intelligently.

All that being said, the variable progression balancing intensity is something I was planning on implementing at some point, so I think this is fine. This isn't going to perfectly solve the problem you want it to solve, though; percentage-based progression balancing solves it for the reasons I outlined above, and in addition SM's extremely linear structure at the start of the game is going to hinder attempts to improve the flow no matter what we do. The metroidvania games seem to suffer pretty heavily from this problem since they tend to not provide a large initial set of checks, so a new progression balancing algorithm might want to handle certain games in a special way. If you want to work on developing a new algorithm, that might be worth keeping in mind.

**Comment by beauxq** [comment]
Yeah, I was forgetting to consider different sized games together with my example.
But it still looks to me like a percentage of the max percentage is the better way to go.
I'm imagining someone with access to 45% of their items (in any sized game), and someone else is not ok with having only 2% of their items, but is ok with having 10% of their items. There's just no good way to configure it for that person if subtracting from the max percentage, because the amount we would want to subtract depends too much on the specific example.

**Comment by beauxq** [comment]
We played a few multi seeds tonight with this. The numbers we put in the settings matched the progression balance that we saw pretty well.

**Comment by beauxq** [comment]
I think I should point out here about the changes I made in `Options.py`

I ran into a bug that came from some of the `Option` classes inheriting from `int`
The issue comes from the fact that, in Python, `int` is immutable. So if we inherit from `int`, there is a hidden part of the object that is immutable.

```python3
class Option(int):
    value: int

    def __int__(self) -> int:
        return self.value


o = Option(3)

o.value = 5

for _ in range(o):
    print("hello")
```

Many people would expect that this code would print "hello" 5 times. But it does not.

I wouldn't be surprised if this has been causing some obscure bugs in Archipelago for a long time.

This is why I removed the inheritance from `int` and replaced it with the base class `NumericOption`

But some code in Python requires `int` objects. That's why this pull request has the changes in:
`worlds/alttp/Rom.py`
`worlds/ff1/__init__.py`
`worlds/rogue-legacy/Rules.py`

There may be more places that are broken by this change from inheriting from `int` that I have missed.
We should make sure we test creating patches for all of the games from YAMLs.
I couldn't test this because I don't have and am not familiar with all of the games.

**Comment by black-sliver** [comment]
Hm, changing the option base type and then still using int (and having to do explicit int()) does not sound like the best solution.

If you use numbers.Integral instead of int, and implement all the magic methods, you can get away without explicit int().

**Comment by black-sliver** [comment]
as a side node, assigning a numbers.Integral to a bytearray will call its __int__ and verify that's in range(0, 256). So Rom.write_byte could be changed to take a numbers.Integral instead of int to get rid of that explicit int() as well.

**Comment by beauxq** [comment]
Yeah, I think that's better. I'll get to the rest of those `NotImplementedError` later to be safe.

**Comment by black-sliver** [comment]
Re: Any - could use `Integral = typing.Union[int, numbers.Integral]` to work around it, but if it's a bug i would not bother.

Assuming this works as expected and defaults to espeon's (new) balancing behaviour, I'm all for it. Evermore is one of those games that are harder to prog balance with, so fine tuning between SM and SoE would not hurt. Berserker, Ijwu and/or espeon obviously need to give the OK.

Some documentation would be good (what to expect from which value), maybe in /WebHostLib/static/assets/tutorial/Archipelago/advanced_settings_en.md

The one thing I'm hesitant about is using floats anywhere in a rando, but that's not on you.

**Comment by beauxq** [comment]
> Re: Any - could use `Integral = typing.Union[int, numbers.Integral]` to work around it, but if it's a bug i would not bother.

I tried `Integral = typing.Union[int, numbers.Integral]`
Type checker still doesn't like it.
"overrides class in an incompatible manner"

**Comment by Berserker66** [comment]
So, the new progression balancing is now out with 0.3.0 and people can get a feel for that. I wanted to allow for that to gain some feedback before already changing it again. I also like good defaults.

I'm keeping my hear to various multiworlds to see how prog balancing and its changes are received to better evaluate this PR then.

**Comment by Berserker66** [comment]
This has a conflict in WebHostLib/static/assets/tutorial/Archipelago/advanced_settings_en.md
As for feedback, I've gathered that people say it's either fine or too strong still, mostly depending on game. Most people I've asked indicated too strong.
So would like to merge this to allow fine-tuning it.

**Comment by beauxq** [comment]
conflict resolved

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
