### PR TITLE
Wargroove: Switched to options API.

### PR DESCRIPTION
**Pull request by FlySniper**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

## What is this fixing or adding?
Switched Wargroove to use the new options API

## How was this tested?
I generated a game, ran the server on it, connected the Wargroove client to it, did a /release, verified that the client showed the correct multipliers for the various options. I ran this test multiple times for different option values.

### CODE REVIEW

**Comment by Exempt-Medic** [comment]
You'll probably want to also remove your one use of per_slot_randoms, change your `fill_slot_data` to use [`as_dict`](https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/world%20api.md#player-options), and also change your options to a dataclass instead of a dictionary

**Comment by FlySniper** [comment]
This PR has been updated with Exempt-Medic's fixes, plus some of my own fixes to their fixes.
I tested these new changes by running several generations with different options, especially since commander_choice has changed. These generations were run on a local server and connected to by the client, which displayed the proper values.

**Review by Exempt-Medic — APPROVED** [review]
Changed LGTM, tested 100 generations

**Review by ScipioWright — APPROVED** [review]
LGTM, code looks fine, test gens succeeded, unit tests passed

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
