### PR TITLE
ladx: shuffle instruments

### PR DESCRIPTION
**Pull request by panicbit**
## What is this fixing or adding?
This allows LADX instruments to be shuffled, similar to the other dungeon items. The ability to keep instruments in their vanilla location is retained and is still the default behaviour.

## How was this tested?
Dozens of rounds of playing with this patch without any issues 🤷 

## If this makes graphical changes, please attach screenshots.
n/a

## Aditional remarks
I don't quite like that that the instruments are special cased. Ideally I would love to give the other dungeon items the `vanilla` placement option as well and get rid of the subclassing, however, that seems to be more involved than I am willing to get into at this point.

### CODE REVIEW

**Review by agilbert1412 — APPROVED** [review]
Looks reasonable to me, still need review from the world maintainer to know if they even want this feature though

**Comment by panicbit** [comment]
I've receivet a report about an issue with this patch.
My assumption that `alias_false` is the default option was wrong. The default seems to be `0` for numerical options, which translates to `option_original_dungeon`. This is not the expected default behaviour for instruments.

**Comment by panicbit** [comment]
I've pushed a fix for the issue described above.

**Comment by zig-for** [comment]
this looked fine to me

**Review by zig-for — APPROVED** [review]

**Review by black-sliver — APPROVED** [review]
Code changes look good. I have not tested anything (i.e. if instruments in non-vanilla spots actually always work and logic considers everything), but from the comments it looks like this was also tested as an APWorld or something.

**Pull request merged**
