### PR TITLE
The Witness: Shuffle Dog

### PR DESCRIPTION
**Pull request by NewSoupVi**
There has been an Easter Egg in this randomizer for a while that would give you a Puzzle Skip if you go to the Dog Statue at the shore of Town and "pet it" using your mouse cursor.

With option groups, I am finally happy to add "Shuffle Dog" as an official option. Petting the dog can now have a randomized item for the multiworld.

The client does not need to be updated, it has supported this for a while.

### CODE REVIEW

**Comment by NewSoupVi** [comment]
For the record, while the option class has existed for a while, it was not actually accessible. Thus, no aliasing is necessary.

**Review by Exempt-Medic — APPROVED** [review]
The code LGTM. Tested the changes through hundreds of generations, tested the most restrictive option set to ensure the correct number of early locations were still be counted. Checked that the location existed when it was supposed to and had a puzzle skip when it was supposed to. Viewed changes through WebHost to confirm the presets and new option group both worked.

**Review by ScipioWright — APPROVED** [review]
Code changes look good, gens fine, shows up in the spoiler log correctly.

**Comment by NewSoupVi** [comment]
This PR now has a "soft conflict" with main that I need to solve. (I believe it should fail unit tests now as well)

**Review by Exempt-Medic — APPROVED** [review]
Reaffirming approval after the recent changes

**Review by Berserker66 — APPROVED** [review]
dog

**Pull request merged**
