### PR TITLE
docs: Add @BrandenEK as codeowner

### PR DESCRIPTION
**Pull request by BrandenEK**
Since Chandler is unavailable, I can be the maintainer since I designed the client, as Chandler and I were a team

### CODE REVIEW

**Comment by BrandenEK** [comment]
This is preferable to #4176

**Comment by Exempt-Medic** [comment]
Why still list Chandler?

**Comment by BrandenEK** [comment]
They will probably be back at some point.  Although not for at least 2 years.  Should I remove them ?

**Comment by Exempt-Medic** [comment]
Hmm, I guess it's up to core. I'll move this to them

**Review by Exempt-Medic — APPROVED** [review]
LGTM. But it's up to core how exactly this should update given the circumstances

**Comment by NewSoupVi** [comment]
All core cares about is approval from @chandler05 or a link to a statement he made in an official channel saying that they're good with this change

**Comment by BrandenEK** [comment]
@NewSoupVi Chandler left without appointing a maintainer.  That is why I am volunteering to be the maintainer, since I collaborated with Chandler to create the client, while they created the server part.  In their absence, I can be the maintainer.

**Comment by NewSoupVi** [comment]
As per https://discord.com/channels/731205301247803413/1224389725922787389/1271116862230364190 and Chandler's bio on Discord, a response to this ping is probably unlikely. Alright, in that case, I will quickly confirm that your claim is valid

**Comment by NewSoupVi** [comment]
Confirmed that https://github.com/BrandenEK/AShortHike.Randomizer is owned by BrandenEK and Chandler05 confirmed as much in the original New Game PR. https://github.com/ArchipelagoMW/Archipelago/pull/2577#issue-2033401539

**Review by NewSoupVi — APPROVED** [review]

**Comment by BrandenEK** [comment]
Thank you

**Pull request merged**
