### PR TITLE
Stardew Valley: Make sure number of month in time logic is a int to improve performance by ~20%

### PR DESCRIPTION
**Pull request by Jouramie**
## What is this fixing or adding?
The improves performances when generating with museum sanity. Here is why:
- Museum sanity rules make a heavy usage of `Count` rule, which is not very efficient at short-circuiting. 
- The `Count` rule was improved in #2984 (which ended up being merged with the 6.x.x branch). This improvement consist of grouping the equal rules. They are then only evaluated once, but count multiple times in the total.
- With 6.x.x, time logic was added to the museum rules, so museum locations are spread through spheres. However, the months were calculated as `float` and not as `int`. That slowed down the generation by a lot.  See benchmarks below for more visual details on that.
- `HasProgressionPercent` are only equal when they have the exact same number, which never happen with the months calculated as `float`. This is really relevant when the rules are being used in `Count`, because they don't get grouped.

So, by making sure the number of month is a `int`, rules in `Count` are more often equals, so they are grouped, so fewer sub-rules are evaluated, which improves performances. 

I also improved the `explain` so it says how the rules are grouped.

## How was this tested?
Run the performance tests that generate ~80 seeds. This on average improve performances by around 20%.

<details><summary>Global benchmark for different options</summary>
<p>

image

</p>
</details> 

<details><summary>Benchmark of `Museumsanity: 20 Artifacts` before</summary>
<p>

Notice that rules are nearly never not grouped. 

image

</p>
</details> 

<details><summary>Benchmark of `Museumsanity: 20 Artifacts` after</summary>
<p>

Now rules are grouped. Evaluation time divided by ~3 with all state for this specific rule.

image

</p>
</details> 

## If this makes graphical changes, please attach screenshots.
N/A

### CODE REVIEW

**Review by agilbert1412 — APPROVED** [review]
Small change, big gains! It's like swapping soda for water in your diet!

**Comment by black-sliver** [comment]
Maybe as a side note, `def has_lived_months` is `@cache_self1`, so passing a float 1 and a float 1.1 and an int 1 into it will calculate and cache 3 times. The `<= 0` case mentioned above bypasses the cache completely, which also sounds unintentional.

**Comment by Jouramie** [comment]
> Hm, why not fix the calculation in `def can_find_museum_item`, changing `/2` to `//2` as you do everywhere else? This would save the call to `int()` and integer division is also possibly faster.

That is the first thing I tried, but then I realized there might be other places where the same fix would be needed, and that Albrekka or Kaito might use a `/` instead of a `//`... So I think this permanent solution is better. I don't think the time 
is measurable considering how many times is method is called.

> Looking further into calls to `can_kill`, `goal_index` in `set_monstersanity_progressive_category_rule` is missing a type annotation.

That is absolutely true, but there are a lot of type annotations missing in that file for some reason... Kind of out of scope for this PR. I'll get to it eventually when reworking monstersanity to use the feature system, like in #3662, for skill progression.

> Also `can_complete_bundle` does `time_rule = True_() if time_to_grind <= 0 else self.logic.time.has_lived_months(time_to_grind)` where the `... if ... <= 0` is redundant.

Fixed.

> Maybe as a side note, `def has_lived_months` is `@cache_self1`, so passing a float 1 and a float 1.1 and an int 1 into it will calculate and cache 3 times. The `<= 0` case mentioned above bypasses the cache completely, which also sounds unintentional.

That is absolutely unintentional, good catch.

**Comment by black-sliver** [comment]
Even if you keep the int(), I'd suggest to add integer division where possible for the caching.

Alternatively you could `assert isinstance` ~~or tell people to no ignore warnings.~~

**Comment by Jouramie** [comment]
Yes, that's exactly the solution where I landed... Still need the `int()` in museum logic because difficulty is a float for some reason.

> ~or tell people to no ignore warnings.~

That's a big demand 🤣

**Review by black-sliver — APPROVED** [review]
I have not checked the explain stuff, but I am assuming that was tested by beta testers already. Other change looks good now.

**Pull request merged**
