### PR TITLE
Generate: convert plando settings to an IntFlag with error reporting for unknown plando names

### PR DESCRIPTION
**Pull request by Berserker66**

### CODE REVIEW

**Review by black-sliver — CHANGES_REQUESTED** [review]
This fails If you put `requires: plando:` in a yaml. We may want more yaml tests if that's the case :D
```
Generate.py", line 506, in roll_settings
    required_plando_options -= plando_options
TypeError: unsupported operand type(s) for -=: 'set' and 'PlandoSettings'
```
Otherwise lgtm

@alwaysintreble you like this for you PR https://github.com/ArchipelagoMW/Archipelago/pull/728 ?

**Comment by alwaysintreble** [comment]
The way I'm handling boss plando atm is just passing it as a bool for the world to validate and this doesn't change that though I still haven't thought of a better validation method yet.

**Comment by black-sliver** [comment]
Noticed two things
* if i put requires: plando: in the yaml and roll on webhost it does not fail generation if checkbox is not set - not sure if that happened before?
* the error message we now get is not super readable: `Exception: Settings reports required plando module 15, which is not enabled.`

**Comment by Berserker66** [comment]
Looks good on my end now at least:
image

**Review by black-sliver — APPROVED** [review]
Looks good now

**Pull request merged**
