### PR TITLE
kivy: allow user-defined text colors in data/client.kv

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
allow user-defined text colors in data/client.kv

## How was this tested?
image

## If this makes graphical changes, please attach screenshots.
image

### CODE REVIEW

**Comment by Jarno458** [comment]
Seems your "white" is not respecting the #000000

**Comment by Berserker66** [comment]
yeah, technically the white is just "no color" and not definable currently. Don't see an easy way to make that happen either, which doesn't involve wrapping it all in another color tag.

**Comment by Jarno458** [comment]
Inst there like a default text_color or foreground_color

**Comment by black-sliver** [comment]
Any update? I believe jarno's comment should be addressed, and also a way to set the background color would be good. Besides avoiding some color combinations for some people, there may also be the need for to configure the UI to be high contrast for others.
(If overriding those is already possible somehow, I believe that should be documented.)

**Comment by Berserker66** [comment]
I looked into it and it is possible by doing this:
image
The canvas color allows setting the background as well:
image
Though that one seems to have to be a tuple of floats.

**Comment by Berserker66** [comment]
Doing this for now:
image

**Review by black-sliver — APPROVED** [review]

**Pull request merged**
