### PR TITLE
Aquaria: Add entrance rule and fix start_inventory_from_pool

### PR DESCRIPTION
**Pull request by tioui**
## What is this fixing or adding?

After a run, I discover that the Sun form ability was needed to enter the Sunken city boss area. So I added the rule.

Also, the `start_inventory_from_pool` option was not working because I was manually removing the precollected item from the itempool. So when Archipelago tries to do the work, it could not find the item to remove in the itempool.

## How was this tested?

I test it by generating games with different options (including `start_inventory_from_pool` and `start_inventory` options) and by using unit testing.

### CODE REVIEW

**Review by ScipioWright — APPROVED** [review]
Code changes look good

**Review by Jouramie — APPROVED** [review]
Tested one generation with `start_inventory_from_pool`, it works like a charm!

**Comment by NewSoupVi** [comment]
Would like someone (1 person is enough) to now confirm the correctness of the location name change

**Review by ScipioWright — APPROVED** [review]
Location name change is correct

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
