### PR TITLE
Core, WebHost: lazy-load worlds in unpickler, WebHost and WebHostLib

### PR DESCRIPTION
**Pull request by black-sliver**
## What is this fixing or adding?

this should hopefully fix customserver's memory consumption

## How was this tested?

haven't tested it yet

### CODE REVIEW

**Review by Berserker66 — APPROVED** [review]
Looks like it should work as advertised.

**Comment by black-sliver** [comment]
customserver still uses 128MB on my machine, so the fix is incomplete :(

**Comment by black-sliver** [comment]
Current version saves ~6MB per idle process (generation queue, hosting queue)
And ~55MB per customserver instance.

The cython stuff eats ~20MB per MP. and the rest is also ~20MB more than expected (psutil reports 51MB before importing _speedups).

After investigating the cython memory overhead, I think splitting Utils and lazy-loading settings would be the next steps.

**Comment by black-sliver** [comment]
The majority of the _speedups memory allocation was due to `pyximport` (or its dependencies). After merging this, you can run `cythonize -b -i _speedups.pyx` on the server to pre-build the module and skip the pyximport. CustomServer is now down to 57MB for me (vs 73MB with pyximport vs 127MB on main).

Biggest fish is now probably `Utils.py` with ~10MB total and `WebHostLib/__init__.py` with ~16MB.

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
