### PR TITLE
Webhost: Add dropdown menus

### PR DESCRIPTION
**Pull request by kindasneaki**
## What is this fixing or adding? 
Adding in drop down menus

## How was this tested?
Tested using webhost

## Current links (Not finalized)

** Start Playing

    - Generate Randomized Game
    - Host Pre-Generated Game
    - Previously Generated Games

** Games

    - Supported Games
    - Setup Guides

** Support

    - f.a.q
    - yaml validator
    - developer docs

** Discord

## If this makes graphical changes, please attach screenshots.
Screenshot 2023-03-19 at 7 12 51 PM

### CODE REVIEW

**Comment by kindasneaki** [comment]
Just wanted to note that with the 7 links for mobile, if the phone is small enough the user will need to scroll and it will overlap the header by a little bit.

**Comment by kindasneaki** [comment]
Also I changed `Host Game` to `Upload Game` and `Generate` to `Generate Game`. Let me know if those should change back or to something else

**Comment by LegendaryLinux** [comment]
Is this PR ready for review? If so, I'll check it out on Saturday.

**Comment by kindasneaki** [comment]
I’ll be finishing it up tonight

**Comment by kindasneaki** [comment]
Everything should be good to go.
Screenshot 2023-03-23 at 7 10 25 PM
Screenshot 2023-03-23 at 7 12 37 PM

**Comment by LegendaryLinux** [comment]
Can we move that down arrow to the left of the Start Playing button and shift the popover to appear centered below the arrow?

**Comment by kindasneaki** [comment]
like so?

Screenshot 2023-03-23 at 11 01 11 PM

**Review by LegendaryLinux — APPROVED** [review]
Yep, like that. I'll get the style tweaks in this weekend. Thanks!

**Pull request merged**
