### PR TITLE
Launcher: add Discord links and generate yamls

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
adds 3 buttons to Launcher

## How was this tested?
by pushing the buttons on windows

## If this makes graphical changes, please attach screenshots.
image

https://cdn.discordapp.com/attachments/731214280439103580/1096936506351960165/GenerateTemplateSettings.gif

### CODE REVIEW

**Comment by Berserker66** [comment]
ah, forgot to update the unittests, apparently.

**Comment by black-sliver** [comment]
We recently had BOM issues over at poptracker. Fwiw BOM on UTF8 is a windows thing makes no sense because, because
The BOM bytes are valid western iso (and probably other) symbols
UTF8 always has the same byte order
When trying to auto-detect UTF8, the BOM does not help.
When tying to load UTF8 as ASCII (in case no symbols >127 are used), the BOM breaks it.

So what we should do imo is
* Save without BOM
* Load with utf8-sig since it support both BOM and no-BOM

**Comment by Berserker66** [comment]
utf-8 without BOM on Windows is liable to use the system default encoding instead, such as japanese special encoding tables.

**Comment by black-sliver** [comment]
That's a valid argument. Should then still only be explicitly used for files that are expected to be modified by users that possibly run Windows < 10 1903, since at that point even notepad changed to utf8 by default.

**Comment by Berserker66** [comment]
we do technically still support windows 7, yes

**Review by black-sliver — APPROVED** [review]
3 new buttons seem to work on linux

**Pull request merged**
