### PR TITLE
Docs: add Spanish guide for Muse Dash

### PR DESCRIPTION
**Pull request by ShinyNT**
## What is this fixing or adding?
This adds a spanish guide for Muse Dash, based off the current (from main) english guide.

## How was this tested?
By me, proofreading a couple of times.

### CODE REVIEW

**Comment by ShinyNT** [comment]
hopefully I edited the init.py code correctly (I did basically the same that I did with pokemon rb guide but just in case)

as a small note on the translation's side, not sure if whatever that throws the "No Support Module Loaded" error translates it to spanish if the system is set to, so leaving that part untraslated (of course it can be changed in the future is so)

**Review by nicholassaylor — APPROVED** [review]
Python code looks good! Ran it locally under WebHost and the guide appears as expected.
image

Concerning the "No Support Module Loaded" issue, I believe that as long as the mod does not provide the translation, then it is good to remain as is. If there is a Spanish translation for the mod, then I believe that having the section titled "No Support Module Loaded / <Spanish Translation>" or something similar would be preferable since a Spanish speaker could find themselves in the English translation either way.

**Comment by ShinyNT** [comment]
> Concerning the "No Support Module Loaded" issue, I believe that as long as the mod does not provide the translation, then it is good to remain as is. If there is a Spanish translation for the mod, then I believe that having the section titled "No Support Module Loaded / " or something similar would be preferable since a Spanish speaker could find themselves in the English translation either way.

yeah, since neither the game (muse dash) nor melon loader (the mod client) are translated I assumed the error wouldn't be translated (I never stumbled into this error myself either), but sometimes there's generic windows messages that get translated to the local language even if the software source isn't, so I wasn't sure myself
but yeah, can always be edited if needed

thanks for commenting once again!

**Review by KonoTyran — APPROVED** [review]

**Comment by LegendaryLinux** [comment]
A quick google translate of the content reveals no skullduggery is afoot.

**Comment by ShinyNT** [comment]
> A quick google translate of the content reveals no skullduggery is afoot.

thank you once again too 
image

> Just chiming in to confirm that yes [the error should still be `No Support Module Loaded!` even if the system language is changed.](https://github.com/LavaGang/MelonLoader/blob/41071711aa1b20d340196000b51f862118c736be/MelonLoader/SupportModule/SupportModule.cs#L62)
> 
> Thanks for creating the guide!

yay, thank you for the confirmation, and no problem!

**Pull request merged**
