### PR TITLE
some worlds: some typing in `LocalRom`

### PR DESCRIPTION
**Pull request by beauxq**
## What is this fixing or adding?

A few people have copied this code.
Maybe we can improve it before more people copy it.

I thought about putting it in `Utils.py`, but it has some SNES specific stuff, and other variations.
Also, I'm not sure how this landscape will change as people move towards not requiring roms for generation.

### `read_bytes`

It's not safe to return `bytearray` when we think it's `bytes`
```python
a = rom.read_bytes(8, 3)
hash(a)  # This won't crash, right?
```

I considered converting to `bytes` before `return`, but I think that would be a slow-down for no benefit.
It's already a slice, so there's no danger of mutating the source.
And some are likely to want `bytearray`, so they would make 2 conversions just to get back to where it started.

### `write_bytes`

Some have found that they can pass a `list[int]`, and it works.

`Iterable[SupportsIndex]` is what's required for `bytearray.__setitem__(slice, values)`
We need to add `__len__` for the `len(values)` in this function.

The reason I didn't add the `write_bytes` typing to dkc3 and smw, is that they both didn't have any `typing` imports in this file, so I thought it would be a little more invasive to add them.

## How was this tested?

unit tests and type checking

### CODE REVIEW

**Comment by beauxq** [comment]
world owners:
@Berserker66 @PoryGone @PinkSwitch

**Comment by PinkSwitch** [comment]
I approve

**Review by PinkSwitch — COMMENTED** [review]
I approve of this change

**Review by Berserker66 — APPROVED** [review]

**Comment by black-sliver** [comment]
If you are worried about people copying this. Should we maybe remove the inheritance of `object` from them as well?

Otherwise this looks good to me and should be safe since it only touches typing. I've never seen `Collection[SupportsIndex]`, but I believe you've done your research there :D

**Comment by beauxq** [comment]
removed the `object` inheritance

In practice, we'll probably never see any difference between `Collection[int]` and `Collection[SupportsIndex]` and `SupportsIndex` comes from something that is poorly named, so I'm kind of on the fence between `Collection[int]` and `Collection[SupportsIndex]`

**Review by black-sliver — APPROVED** [review]
While poorly named, if this is what our buffer calls it, we should use it and the world devs did not complain, so we good.

**Pull request merged**
