### PR TITLE
ChecksFinder: itempool naming/typing

### PR DESCRIPTION
**Pull request by Exempt-Medic**
## What is this fixing or adding?

Appeasing mypy
`itempool` did not have a consistent typing since it went from a list of strings to a list of ChecksFinderItems. This just changes the name to avoid this typing error.

## How was this tested?

A generation and connecting to a world.

### CODE REVIEW

**Review by nicholassaylor — APPROVED** [review]
New version is easier to read as well, might want to update the comments to reflect the changes made

**Comment by Exempt-Medic** [comment]
> New version is easier to read as well, might want to update the comments to reflect the changes made

I feel like the comments are still pretty much accurate? Any suggestions?

**Comment by nicholassaylor** [comment]
> I feel like the comments are still pretty much accurate? Any suggestions? Edit: Hmm yeah, I think you're right, this is better

You got everything I was going to suggest

**Review by qwint — APPROVED** [review]
small rename changes that make sense

solely a code review; did not run test/gen/etc.

**Comment by SunCatMC** [comment]
I approve of this change

**Review by SunCatMC — APPROVED** [review]

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
