### PR TITLE
Stardew Valley: Removed Walnutsanity and Filler buffs from the all random preset

### PR DESCRIPTION
**Pull request by agilbert1412**
## What is this fixing or adding?
It was brought to my attention that certain option types, notably OptionSet, don't support "random". But in the Stardew "all random" preset, I was using it. So this caused issues on webhost.

Related conversation: https://discord.com/channels/731205301247803413/731214280439103580/1306366651771388038

Thanks to @agilbert1412 for bringing this to my attention in https://github.com/ArchipelagoMW/Archipelago/pull/4205

## How was this tested?
Webhost and the tests from #4205

### CODE REVIEW

**Review by Exempt-Medic — APPROVED** [review]
Tested the same changes locally a couple days ago, they worked properly and fixed the bug

**Review by black-sliver — APPROVED** [review]
Not sure if we want to allow random for those in the future, but for now this fixes the errors in the javascript console

**Comment by agilbert1412** [comment]
> Not sure if we want to allow random for those in the future, but for now this fixes the errors in the javascript console

@black-sliver Just so you know, I proposed PRing the ability to use `random` for these types, optionally (opt-in, with a base class field that defaults to false, and the ability to override it in derived types written by worlds), and I was told by a couple people that this would not get approved and not worth doing.

I would still prefer the ability to use random on my options, but my understanding is that I'll get rejected so I didn't do it.

You can find this conversation if you follow the linked discord message in this PR, and read down a bit. It did not last very long

**Comment by Silvris** [comment]
> Not sure if we want to allow random for those in the future, but for now this fixes the errors in the javascript console

If we allow random for OptionSet, then we'd have to find a way to make it functional for Item/LocationSet (which isn't currently possible). Allowing it for OptionSets with defined valid_keys is easy (and requested by users), but Item/LocationSet don't define valid_keys, and can't find their valid_keys until `verify`.

**Pull request merged**
