### PR TITLE
Docs: add info to turn on github actions

### PR DESCRIPTION
**Pull request by kindasneaki**
## What is this fixing or adding?
title see https://discord.com/channels/731205301247803413/731214280439103580/1158657594181812304

## How was this tested?
didn't

### CODE REVIEW

**Comment by black-sliver** [comment]
Looks like you forgot to add the image?
Also I think the sentence is missing something at end - maybe "when pushing"

**Comment by nicholassaylor** [comment]
Like black sliver said, the image is not included in the PR.

I think that the automated workflows are also enabled when you accept and enable them on the Actions page since AP has them turned on already.

**Comment by kindasneaki** [comment]
making sure things are checked when pushing is hard apparently

**Comment by black-sliver** [comment]
maybe shrink the image? i think you can still make out the red circles at half height

**Pull request merged**
