### PR TITLE
OoT hint distribution switch

### PR DESCRIPTION
**Pull request by espeon65536**
for asyncs

### CODE REVIEW

**Comment by ThePhar** [comment]
How is this different than creating a meta.yaml where you overwrite the `hint_dist` variable? For large asyncs we'd still need to remember to change this.

**Comment by Berserker66** [comment]
the main difference is that the main async doesn't actually use a meta yaml, but yeah starting to use one should also work.

**Comment by Ijwu** [comment]
@Berserker66 You decide. We either use meta.yaml or approve and merge this. Flip a coin if you don't care. :P

**Comment by Berserker66** [comment]
@ThePhar want to add meta to your async tool revamp?

**Comment by Ijwu** [comment]
Sounds like we're going meta.yaml. Closing this PR.

**Pull request closed without merging**
