### PR TITLE
Docs: Add Spanish guide for Clique

### PR DESCRIPTION
**Pull request by ShinyNT**
## What is this fixing or adding?
this adds a spanish setup guide for Clique, the greatest game of all time

## How was this tested?
by me translating and proofreading it

### CODE REVIEW

**Comment by ShinyNT** [comment]
hopefully I did the init.py edit good, it seemed a bit different than the others

**Review by nicholassaylor — APPROVED** [review]
Init looks good and translation is accurate.
LGTM

**Comment by ThePhar** [comment]
I'm about to change a lot of stuff in Clique, so it'll be out dated soon. I would at least wait until I can get v2 finished. I can work with you later on updating the guides.

**Comment by ShinyNT** [comment]
ah, I see
sure, let's wait until v2 is released

**Comment by nicholassaylor** [comment]
Should this still wait for v2 or can this be put in place while v2 is still in development? Additionally, the branch now has conflicts that would need to be sorted before continuing.

**Comment by ShinyNT** [comment]
yeah not sure really, I expected v2 would come sooner by that Phar message
I guess I can just close it in the meantime if needed

**Comment by Exempt-Medic** [comment]
This has conflicts btw

**Comment by ShinyNT** [comment]
i'll close this for now, i'll just wait for clique 2.0 to be officially merged to even think about updating the guide again

**Pull request closed without merging**
