### PR TITLE
Pokemon R/B: Removing Floats from NamedRange

### PR DESCRIPTION
**Pull request by Exempt-Medic**
## What is this fixing or adding?

Title, also:
https://discord.com/channels/731205301247803413/1230990819217899550/1230990819217899550

## How was this tested?

Generations

### CODE REVIEW

**Comment by Exempt-Medic** [comment]
@Alchav

**Review by ScipioWright — APPROVED** [review]
Floats bad

**Comment by NewSoupVi** [comment]
Should this have explicit protection against it in the NamedRange class?

**Review by gaithern — APPROVED** [review]
Test generation with several different values that would have resulted to a float, including the "half" value.  Generation threw no errors despite doing so before the change and the output logs look correct to me.

**Review by Alchav — APPROVED** [review]

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
