### PR TITLE
Core, HK, ALTTP, OOT: Adds the notion of 'extra' hint details for e.g. reporting shop costs.

### PR DESCRIPTION
**Pull request by dewiniaid**
## What is this fixing or adding?

This adds an optional `str` field `details` on `Hint` that can store some additional unstructured information related to a hint.  The primary use case is listing shop costs on the hint (useful in OOT and HK in particular where access to a shop item may be logically blocked by a wallet and grubs/essence/rancid eggs, specifically), but the implementation is intentionally generic for other uses that might occur.

This field is populated from `extra_hint_data` in much the same way that `Hint.entrance` populates from `er_hint_data`.

HK, ALTTP and OOT worlds are updated to provide this data.

I opted not to repurpose the existing `er_hint_data` in favor of having a simpler path to backwards compatibility.

## How was this tested?

Primarily through generating a small multiworld including multiple HK, LTTP and OOT seeds (as well as Timespinner) and doing variations of `!hint` and `!hint_location` as well as `/hint_location`

### CODE REVIEW

**Comment by dewiniaid** [comment]
Taking this out of draft status, I've done a few private tests with it and they worked fine.

There's probably merit to add Factorio science costs in here too, but I'm unsure of how to best do that at this moment and it doesn't need to hold up the rest of the feature.

**Comment by dewiniaid** [comment]
Taking this out of draft status, I've done a few private tests with it and they worked fine.

There's probably merit to add Factorio science costs in here too, but I'm unsure of how to best do that at this moment and it doesn't need to hold up the rest of the feature.

**Comment by Berserker66** [comment]
@espeon65536

**Comment by Berserker66** [comment]
We're trying to move towards less tech debt and towards a 1.0 release. Adding another data point to hint that supercedes one of the old fields I will not accept, that leaves the old field dangling around for an unknown amount of time accruing more tech debt rather than clearing it.

**Comment by espeon65536** [comment]
I finally noticed this PR!

I agree with Berserker -- I would much rather see a full merge of both hint text pieces than adding an extra one. We do not need to retain compatibility for hosting a new game on an old server, which is what fully retaining `er_hint_data` seems to be aimed at. Instead, we should fully move all information to `extra_hint_data` but keep the server's ability to interpret old games using `er_hint_data`; then we can drop support for `er_hint_data` the version after.

**Comment by dewiniaid** [comment]
One idea I had was to store the hint data as a dictionary instead, so a
structure could be like:

```
{
  'at': 'Entrance',
  'cost': '137 Macguffins'
}
```

This would also allow the current highlighting scheme to work in printJson
(entrance hints don't highlight the word "at".

Any objections to this implementation, with the idea of phasing out
er_hint_data?

**Comment by Berserker66** [comment]
would this be "costing": "137 Macguffins" to construct the sentence or would keys like at and cost be handled seperately in some way?

**Comment by Berserker66** [comment]
Additionally, to construct text with markup we already have JSONMessagePart, so maybe it should just follow the established format, instead of inventing a new one.

**Comment by agilbert1412** [comment]
@dewiniaid Do you still intend to get this merged? It seems like, in its current state, it is rejected, and it's been over a year since last update. Are you planning on executing the changes requested, or should the PR be closed?

**Comment by NewSoupVi** [comment]
I'm going to close this PR. As far as I understand, Berserker wants to make a hint revamp himself as far as I understand, which would include "extra info" from my understanding as well. Furthermore, it seems like the author has not responded for several months.

**Pull request closed without merging**
