### PR TITLE
Launcher, Docs: Update UI and Set-Up Guide to Reference Options 

### PR DESCRIPTION
**Pull request by nicholassaylor**
## What is this fixing or adding?

Changes "Generate Template Settings" to "Generate Template Options" in the launcher to reflect recent change to options

## How was this tested?

Ran Launcher.py and ensured that it worked

## If this makes graphical changes, please attach screenshots.
image

### CODE REVIEW

**Comment by Exempt-Medic** [comment]
This should probably also change "Generate Template Settings" in [the Archipelago setup guide](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/generic/docs/setup_en.md).

**Comment by nicholassaylor** [comment]
Updated the set-up guide to reflect these changes as well as a few remaining references to player settings in the guide

**Review by Exempt-Medic — APPROVED** [review]
The changes all LGTM and it covers everything I could find that referred to "Generate Template Settings".

**Review by Ixrec — APPROVED** [review]
Confirmed I see the new button text when I run the Launcher on this branch.

Code and docs LGTM.

After quickly searching the repo for other uses of "settings", I did find a few others that I think are referring to options, but none of them look anywhere near as important as the setup guide, so up to you if we address these:
- Archipelago/playerSettings.yaml lines 155 and 304 (is this file even used?)
- Archipelago/settings.py line 3
- Archipelago/test/general/test_reachability.py, the `default_settings_unreachable_regions` variable

**Comment by nicholassaylor** [comment]
Once #2622 gets merged, I plan to do one last PR to get all of the remaining references to player settings since the majority of the site will be switched over to that terminology by then. To avoid scope creep for this PR, I'm going to keep everything as it is right now, but I will definitely take note of its uses elsewhere.

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
