### PR TITLE
The Witness: Change all option name comparisons to strings instead of numeric values

### PR DESCRIPTION
**Pull request by NewSoupVi**
Refactor all the options checking to do `world.options.shuffle_EPs == "individual"` instead of `world.options.shuffle_EPs == 1`

Also, do a refactor of the shuffle_postgame code, which is where most of the option checking happens. This part probably needs to be looked over by someone who understands the game. I'm gonna request a review from Exempt-Medic I think.

### CODE REVIEW

**Comment by NewSoupVi** [comment]
This will likely conflict with https://github.com/ArchipelagoMW/Archipelago/pull/2499 so I'll wait for that before un-drafting this one

**Comment by Exempt-Medic** [comment]
I used a regex search and found some other comparisons that could be strings and some simplify-able comparisons:
* [hints](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/hints.py#L241)
* [player_logic](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/player_logic.py#L258)
* [player_logic](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/player_logic.py#L259)
* [player_logic](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/player_logic.py#L335)
* [player_logic](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/player_logic.py#L356)
* [\_\_init\_\_](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/__init__.py#L172)
* [\_\_init\_\_](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/__init__.py#L246)
* [items](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/items.py#L201)
* [items](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/items.py#L204)
* [items](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/items.py#L208)
* [static_logic](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/static_logic.py#L235)
* [utils](https://github.com/NewSoupVi/Archipelago/blob/option_names/worlds/witness/utils.py#L24)

**Comment by alwaysintreble** [comment]
> Some of the code is not mine and I'm worried that removing "> 0" could cause some problem with negative values and it's outside of the scope of this PR anyway

just peeked at it and `.value` would be better/faster

**Review by Exempt-Medic — APPROVED** [review]
I read through the changes, primarily to the postgame section, to check that they lined up with my understanding of the game. I then ran 1500 fully-random, differently-seeded generations on `main` and `option_names` and compared the outputs. I also specifically checked all 96 reasonable combinations of postgame settings. The outputs were identical except when the one additional postgame consideration occurred ([lines 324-235](https://github.com/ArchipelagoMW/Archipelago/blob/d458820f023240acba8d4fb49c443826452d88f7/worlds/witness/player_logic.py#L321-L325) of `player_logic.py`), which is the expected behavior.

**Comment by NewSoupVi** [comment]
This PR is at the bottom of a pretty big dependency chain at this point, so it'd be epic if this could be prioritised over other Witness PRs 🙏

**Review by black-sliver — APPROVED** [review]
LGTM

Having any kind of unit test that verifies the options put the corresponding items/things into the pool/member variables, and that slot data has the correct output of the correct input wouldn't hurt going forward though. (It would make sure it behaves the same before and after, and save you from typos in strings)

**Pull request merged**
