### PR TITLE
WebHost: Align multitracker status column to the left

### PR DESCRIPTION
**Pull request by freyacodes**
## What is this fixing or adding?
Aligns the status column head in the multitracker to the left, to align with the column's content. Consistent with the rest of the design.

## How was this tested?
Accessing the multitracker

## If this makes graphical changes, please attach screenshots.
Before:
image

Now:
image

### CODE REVIEW

**Comment by LegendaryLinux** [comment]
Nearly all of the content in the MultiTracker is centered. Can we just center this column's data instead?

**Comment by freyacodes** [comment]
Half of the other columns in the generic table are aligned left
image

Keeping the content centered could work, but I still think aligning it left makes more sense since it is not numeral content

**Comment by LegendaryLinux** [comment]
Oh, I see what you mean. Okay, alternate solution since I think that columns containing primarily text should be left-aligned.

Move the `Status` column after the `Game` column, and keep everything in the `Status` column left-aligned. That should look good and still make sense as you read the table.

**Comment by freyacodes** [comment]
That's an excellent idea. I'll implement that when I get the time

**Comment by freyacodes** [comment]
Finally got around to doing this

image

I made sure to place the column before any custom multitracker columns
image

**Review by LegendaryLinux — APPROVED** [review]

**Pull request merged**
