### PR TITLE
Docs: Fix typos in Minecraft info page

### PR DESCRIPTION
**Pull request by ShineSyndrome**
## What is this fixing or adding?
Fixed typos in game page

## How was this tested?
NA

## If this makes graphical changes, please attach screenshots.
NA

### CODE REVIEW

**Review by ReverM — APPROVED** [review]
LGTM

**Review by nicholassaylor — APPROVED** [review]
LGTM as well

**Review by Exempt-Medic — APPROVED** [review]
LGTM

**Review by KonoTyran — APPROVED** [review]
I blame the keyboard.

**Pull request merged**
