### PR TITLE
Pokemon Red/Blue: Fixed Deprecated options system

### PR DESCRIPTION
**Pull request by agilbert1412**
## What is this fixing or adding?
I was tired of the infinity warnings, so I did something about it. Also took care of the per_slot_randoms while I was here.

## How was this tested?

Not much.

I ran the generic unit tests, but Pokemon Red/Blue does not have specific unit tests, so it is impossible to know if things are correct or not.

Plus, I don't play the game myself.

Overall, low confidence, but I figured that's better than leaving the options in limbo forever. I just recommend the reviewers pay close attention I guess.

### CODE REVIEW

**Comment by Exempt-Medic** [comment]
While you're fixing these, you may as well change `"half": default / 2` to `"half": default // 2` in `ExpModifier` since that has caused a few various bugs in the past

**Comment by Exempt-Medic** [comment]
Perhaps out of scope, but since you changed `per_slot_randoms`, you could change things to use `world.player_name` instead of `multiworld.player_name[world.player]`

**Comment by Exempt-Medic** [comment]
You missed at least two instances of the old option getters in `pokemon.py` on lines 367 and 378

**Review by Alchav — COMMENTED** [review]
These kinds of changes have already been made on a dev branch and this would likely lead to massive merge conflicts

**Comment by agilbert1412** [comment]
As the world maintainer, I'm pretty sure you're allowed to block the PR on these grounds, so if that's your stance, so be it.

I took initiative because I don't know the timeline on that dev branch, but what I do know is that it has been over 8 months since #993 was merged, and that these specific options not being fixed is a significant annoyance to a lot of people (myself included).

Do you have a rough timeline for the dev branch, so that we know what to expect?

**Comment by eudaimonistic** [comment]
> As the world maintainer, I'm pretty sure you're allowed to block the PR on these grounds, so if that's your stance, so be it.
> 
> I took initiative because I don't know the timeline on that dev branch, but what I do know is that it has been over 8 months since #993 was merged, and that these specific options not being fixed is a significant annoyance to a lot of people (myself included).
> 
> Do you have a rough timeline for the dev branch, so that we know what to expect?

Seemingly that's what the just posted #3566 is about.

**Comment by NewSoupVi** [comment]
Going to default to the PR by the world author, which has been opened now

**Pull request closed without merging**
