### PR TITLE
TUNIC: Change Tunic to TUNIC

### PR DESCRIPTION
**Pull request by ReverM**
Changed _init_.py so that the name of the game appears as TUNIC instead of Tunic for uniformity. 

## How was this tested?

Ran WebHost locally

### CODE REVIEW

**Comment by black-sliver** [comment]
This change would break existing yamls. So unless @silent-destroyer want's to absolutely do this, I would not recommend it.

**Comment by ReverM** [comment]
I have discussed this change with silent beforehand

**Comment by alwaysintreble** [comment]
not only does this break the yamls but it also requires a client change

**Comment by ReverM** [comment]
> not only does this break the yamls but it also requires a client change

This also has been discussed with Silent

**Comment by black-sliver** [comment]
I would like them to use the github feature to approve this PR then.

**Review by silent-destroyer — APPROVED** [review]

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
