### PR TITLE
core: allow game to be overridden by meta.yaml

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
title

## How was this tested?
tested by creating a meta file with 
```
meta_description: test
null:
  game: Hollow Knight
```

and a Factorio yaml

### CODE REVIEW

**Comment by Berserker66** [comment]
This is something that is desired?

**Comment by Jarno458** [comment]
Hmmz, if you force override a game, you will be missing the yaml game specific settings unless you also force those

**Comment by ThePhar** [comment]
Just so I document my thoughts, although you already made the change I asked about, I would prefer this kind of thing be a fail than implicitly roll all default settings for a user.

And you did do that, so I'm cool with it. I'm fine with this PR, but I'll wait for another maintainer to also check off on it, since it changes core functionality.

**Comment by black-sliver** [comment]
Any update on this?

Do we want it? It would make sense to allow this for completeness sake, even though the use case of this is very limited (a themed multi could make sure that no "wrong" game is rolled with this).

**Comment by ThePhar** [comment]
Going to close this since we haven't had any update since sliver's last post. Can be re-opened if we want to revisit this.

**Pull request closed without merging**
