### PR TITLE
Wargroove: Fixed Wargroove Client not removing communication files

### PR DESCRIPTION
**Pull request by FlySniper**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

## What is this fixing or adding?
The Wargroove client may not remove the communication files if shutdown by force. This fixes that by also removing the communication files on startup.

## How was this tested?
- I generated a Wargroove only game.
- Collected the first 4 checks.
- Deleted my campaign progress and made a backup of the communication files.
- Shutdown the client and replaced the now deleted communication files
- I generated a second Wargroove only game.
- Started the client and verified that the communication files were deleted.
- I connected to the second game.
- The first 4 checks should be collectable again.

### CODE REVIEW

**Comment by Berserker66** [comment]
Can I interest you in https://docs.python.org/3/library/atexit.html ?

**Comment by Berserker66** [comment]
The communication files all share a common file extension right? I'd suggest checking for that pattern (.endswith) to have a layer of protection against deleting other files, just to be safe.

**Comment by FlySniper** [comment]
Not all communication files have a file extension. I'm not concerned with protecting against deleting other files since:
- The Wargroove Client creates that directory.
- It verifies that \win64_bin\wargroove64.exe is a valid file, otherwise the client won't start.

**Review by Berserker66 — APPROVED** [review]

**Comment by Berserker66** [comment]
.. wrong button. Anyway, I suggest using os.path.join() instead of +"/"+ so it works on all operating systems.

**Pull request merged**
