### PR TITLE
Various: fix absolute imports in worlds

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
messenger, yugi and shorthike loading on 3.8 build

## How was this tested?
On cx freeze 7.0.0 on python 3.8 on win10

### CODE REVIEW

**Review by alwaysintreble — APPROVED** [review]
messenger change is good

**Comment by black-sliver** [comment]
I think writing the apworld analyzer :TM: script should move up on my list.
(While this specific problem would disappear once we drop py 3.8, I still think relative imports would be more correct for a world to have less impact on Core. I.e. there is potential to break absolute imports again in the future.)

**Comment by black-sliver** [comment]
@Rensen3 @chandler05

**Review by Jouramie — APPROVED** [review]

**Review by chandler05 — APPROVED** [review]

**Comment by Jouramie** [comment]
I noticed aventure, dkc3, ladx, sc2 and smw also have absolute imports. Those however could be fixed in another PR.

**Review by Rensen3 — APPROVED** [review]

**Pull request merged**
