### PR TITLE
Docs: Categorize Commands in Guide

### PR DESCRIPTION
**Pull request by nicholassaylor**
## What is this fixing or adding?
- Adds categories for commands
- Re-orders commands by relevance
- Swaps order of server commands and client commands
- Moves game-specific commands into the game page (This change only moves Final Fantasy 1 and Factorio commands)

The main purpose of this pull request is to help organize the commands better so that users can easily find the commands they need.
Server commands were put first since they tend to be the commands that are used the most often. Commands were then put into categories based on their function.
Local commands were updated to better reflect which clients allow the use of the common local commands.

> One reservation I have at this point is the inclusion of the client-specific commands, such as those from FF1Client and FactorioClient. In its current state, the local commands for specific clients are out of date. However, I forsee this section getting increasingly hard to maintain as more games are added and we migrate to apworlds. I think the best idea at this point is to remove the specific commands from this guide and instead move them to the guides of those games.

Addressed in af9237fb0577ba62f81081b0c193e672dbf24242
However, I would like to hear input on this matter.

## How was this tested?
Running webhost and viewing rendered changes

## If this makes graphical changes, please attach screenshots.
image
Server commands preview
image
Local commands preview

image
Example of commands in game page

### CODE REVIEW

**Comment by LegendaryLinux** [comment]
I'm torn. On the one hand, keeping all the information about individual client commands in one place is convenient. On the other hand, as we move into the APWorld format, each game will need to start documenting itself better anyway.

I think I'm in favor of removing game-specific commands from this page and moving them to the specific game guides.

**Comment by LegendaryLinux** [comment]
I do think SNI Client should remain on this page, as that is used in multiple games.

**Comment by eudaimonistic** [comment]
These changes seem to suit the generic commands far more than the game-specific commands.  I agree that the game-specific commands should probably end up moved into their setup guide counterparts instead.  I'm in favor of at least the Server Commands changes.

**Comment by nicholassaylor** [comment]
I definitely agree with keeping the SNI commands in this guide since so many games use it.

I suppose that if we wanted a central place for all game-specific commands, it could exist in its own separate guide. But in the end, it's just pushing the problem to a different part of the site without addressing the issue. 

I will move the specific commands into their respective game pages and leave the SNIClient commands as they are.

**Comment by LegendaryLinux** [comment]
I don't like the idea of a standalone guide to contain client specific commands. They should go in their own game's guide. A standalone page just de-centralizes information. All relevant information about a game and its client should be available in that game's guide.

**Review by LegendaryLinux — APPROVED** [review]

**Pull request merged**
