### PR TITLE
Increase contrast of SM tracker

### PR DESCRIPTION
**Pull request by Lincoded**
Improve accessibility by changing text to white and page background to black.

Original contrast ratio was 3.88, and new contrast ratio is 5.4

### CODE REVIEW

**Comment by Ijwu** [comment]
I'd love to see what this looks like now. I would host it myself and look but I'm indisposed this week. Could you post a screenshot as a favor? Thanks!

**Comment by Berserker66** [comment]
We'll actually need to check with the discord community. If you remember, the existing design was discussed and agreed upon there.

**Comment by Ijwu** [comment]
I don't think I particularly care about community favoritism over increased accessibility, to be very frank.

**Comment by Ijwu** [comment]
Since this change does not affect background color of the tracker itself and increases a11y, I suggest this is pushed through. The community had the most debate as to what the background color should be, not what the color of the text on top should be. If the text color remains black it fails a lighthouse audit on contrast ratio, but it passes with the change. @Berserker66 or @LegendaryLinux please agree or disagree so I'm not swinging my hammer around indiscriminately.

**Comment by Berserker66** [comment]
I suppose I'm indifferent, feel free to see it as agree

**Comment by Ijwu** [comment]
Thanks @Lincoded, a11y concerns have been an ongoing source of fixes. I love to see more a11y minded folks contributing. Thanks again!

**Pull request merged**
