### PR TITLE
The Witness: Rename "Town Windmill Entry" to "Windmill Entry"

### PR DESCRIPTION
**Pull request by NewSoupVi**
Windmill is no longer considered a part of Town since the area_hints PR. Also, all "Entry" doors have been renamed last update to only contain the place they are an Entry to. This one slipped through the cracks. Oh well, it happens

### CODE REVIEW

**Review by ScipioWright — APPROVED** [review]
It functions, and this review will hopefully not get my account suspended.

**Comment by Exempt-Medic** [comment]
Will fixing "Challenge Tunnels Entry (Door)" ( to remove `Challenge` ) and "Swamp Platform Shortcut Door" ( to use `(Door)` ) be another PR?

**Comment by NewSoupVi** [comment]
> Will fixing "Challenge Tunnels Entry (Door)" ( to remove `Challenge` ) and "Swamp Platform Shortcut Door" ( to use `(Door)` ) be another PR?

Yeah

**Review by Exempt-Medic — APPROVED** [review]
Tested the changes locally through generations and reading spoiler logs.

**Comment by NewSoupVi** [comment]
This PR will likely conflict with https://github.com/ArchipelagoMW/Archipelago/pull/3007, which I absolutely need to be merged before anything else, so I'm putting this one on "waiting on: other".

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
