### PR TITLE
Timespinner: Remove region lookups inside create_regions

### PR DESCRIPTION
**Pull request by Jarno458**
## What is this fixing or adding?
~For performance reasons, regions are now cached locally inside create_regions~
No-longer create extra lambda's for locations without rules
No-longer convert LocationData list to tuple

## How was this tested?
by running lots of local generations, with one or multiple players

### CODE REVIEW

**Comment by Berserker66** [comment]
Is this actually faster? Should the answer turn out no, would you still prefer this over the old method?

**Comment by Jarno458** [comment]
It most certainly was faster when i tested it, but that before you did all kinds of caching reworks
There are certainly improvement in this one that i like, for example nolonger creating extra nonstatic empty lamba's when an location had no rule. and also not force copying the LocationData list to an tuple

**Comment by Jarno458** [comment]
Drafted as latest tests shown some potentional issue

**Comment by Jarno458** [comment]
Back to ready. fixed bug
Performance testing compared to current main show basically no performance improvements anymore

**Comment by Jarno458** [comment]
Well if it doesnt make a difference, iv switched the region lookups back to multiworld lookups

**Comment by Jarno458** [comment]
well if it doesnt make much of a difference anymore these refactoring can just go live with #2090

**Pull request closed without merging**
