### PR TITLE
Tests: add test that option classes aren't reused

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
Prevents worlds from reusing the exact same option class in their available options. This becomes problematic when trying to use Option Groups since all the grouping happens via the actual class and not the dataclass's attributes. Namely #3393 

## How was this tested?
Ran tests a few times, added a duplicate option and removed it ensuring it behaved how I expected.

### CODE REVIEW

**Comment by Silvris** [comment]
Should this ignore Removed? Unsure if they go into Game options by default like other options, but it is the main use I can see of a duplicate class.

**Comment by alwaysintreble** [comment]
it ignores `Visibility.none` entirely

**Comment by Exempt-Medic** [comment]
This should work now btw

**Review by black-sliver — APPROVED** [review]
I agree with this because the display name for the option is per class, making it bad UX to reuse the class.

**Pull request merged**
