### PR TITLE
The Messenger: add race mode to slot_data

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
The Messenger has special client behavior for race mode now so I need this information and for some godforsaken reason we all have to do this instead of just adding this int to the networking protocol.

### CODE REVIEW

**Review by Exempt-Medic — APPROVED** [review]
LGTM (tested by printing)

**Comment by NewSoupVi** [comment]
Was there discussion on putting this in networking? If someone had PRed that I might've just merged it but it sounds like there's some history

**Comment by alwaysintreble** [comment]
> Was there discussion on putting this in networking? If someone had PRed that I might've just merged it but it sounds like there's some history

last time it came up berserker gave me the impression he's against adding this to the network protocol because "most worlds don't use it" and i'd rather not put in the effort for something that won't get merged

**Review by ScipioWright — APPROVED** [review]
LGTM, didn't test but it's literally 1 line that I've already basically written before myself so

**Comment by Berserker66** [comment]
> > Was there discussion on putting this in networking? If someone had PRed that I might've just merged it but it sounds like there's some history
> 
> last time it came up berserker gave me the impression he's against adding this to the network protocol because "most worlds don't use it" and i'd rather not put in the effort for something that won't get merged

That's not what was said. You argued it would safe memory, black sliver and I debunked that. I followed up with it probably still being a good idea, just not for that reason.

**Comment by NewSoupVi** [comment]
> > > Was there discussion on putting this in networking? If someone had PRed that I might've just merged it but it sounds like there's some history
> > 
> > 
> > last time it came up berserker gave me the impression he's against adding this to the network protocol because "most worlds don't use it" and i'd rather not put in the effort for something that won't get merged
> 
> That's not what was said. You argued it would safe memory, black sliver and I debunked that. I followed up with it probably still being a good idea, just not for that reason.

Well, Treble, since Berserker seems to be on board with it, if you just wanna open that as a PR instead, I can prioritize that if you ping me

**Comment by NewSoupVi** [comment]
So this is redundant now, yes? With the other PR being merged

**Pull request closed without merging**
