### PR TITLE
OoT: fix patching deltas when run from another folder

### PR DESCRIPTION
**Pull request by Berserker66**

### CODE REVIEW

**Comment by Berserker66** [comment]
fix was in https://discord.com/channels/731205301247803413/731215534619754526/959649934943092736

**Comment by black-sliver** [comment]
SM, Alttp and (since 0.3.0 also) SoE handle rom resolution as follows:
1. try path directly,
2. if that fails resolve through **user_path** (originally local_path)

That way you can
1. pass an absolute path in the yaml
2. have it fall back to a relative path to your writable directory (user_path)

**Comment by Berserker66** [comment]
There is a big if tree inside the OoT Rom object, maybe it should be moved to there instead. @black-sliver feel free to PR against this PR's branch if you have a good spot in mind.

**Comment by black-sliver** [comment]
Currently all worn out. Using user_path instead of local_path should add general AppImage compatibility.
I'll probably do a second round of linux-related stuff (mainly readme) when i feel up for it, and can then look over OoT as well.

**Review by Ijwu — APPROVED** [review]
Approving but not merging until the conversation as been properly resolved.

**Comment by Berserker66** [comment]
merging for now per PM from black sliver, but could be improved in the future.

**Pull request merged**
