### PR TITLE
Core: Making invalid Toggle options error properly/sooner

### PR DESCRIPTION
**Pull request by Exempt-Medic**
## What is this fixing or adding?
https://discord.com/channels/731205301247803413/1224562534753898647

## How was this tested?
Generations

### CODE REVIEW

**Review by alwaysintreble — CHANGES_REQUESTED** [review]
this should be a `ValueError`, not a bare exception. it should also be in from_any instead of the constructor. the assert can just be removed though so that's correct. something like
```py
data = int(data)
if data not in {0, 1}:
	raise ValueError()
```

**Comment by alwaysintreble** [comment]
alternative is to fix it behind the scenes instead of throwing. something like `value= int(bool(value))`

**Comment by Exempt-Medic** [comment]
> alternative is to fix it behind the scenes instead of throwing. something like `value= int(bool(value))`

Yeah, I said the same thing in the bug channel. Honestly, I _mostly_ opened this PR so that somebody else would fix it better

**Comment by Exempt-Medic** [comment]
I am not qualified to know the best way to solve this problem, closing the PR.

**Pull request closed without merging**
