### PR TITLE
HK: Stores shop costs in a generic structure in slot_data

### PR DESCRIPTION
**Pull request by dewiniaid**
This allows us to theoretically set costs on any location check, as well as opening up future options for scaling (or costs)

Also reworks the way shop rules are applied.

 - Extractor.py: Record the costs of vanilla shop items and vanilla locations.
 - Extractor.py: Send output rules to GeneratedRules.py rather than Rules.py.
 - Make Rules.py the more 'static' rules file, containing everything related to rules processing besides the actual generated data.  Some
   IDEs struggle to parse the entire rules file, so splitting the generated data into a seperate GeneratedRules.py helps with that.
 - Define assorted names for various cost terms (logic term, option key, singular and plural forms)
 - Allow the range of random Shop geo costs to be changed. 
 - Output the entirety of all cost data to a single dictionary structure.  Maintain the old structures as well for client backwards compatibility.
 - Shop geo costs are now generated serverside.
 - Shop items left vanilla (i.e. charms when not randomized) now retain their vanilla cost in compatible clients.

### CODE REVIEW

**Review by Ijwu — APPROVED** [review]
Assuming some changes to certain comments happen, I approve of this. I would still want @Berserker66 to check it out too as he wrote this initially.

**Comment by dewiniaid** [comment]
This (and #663) were both present in a beta test ~24 hours ago. While the beta test ran into some issues, they were mostly clientside DeathLink issues outside the purview of either PR.

**Comment by dewiniaid** [comment]
actually, sorting of shop costs might have broke the keep vanilla placements at vanilla shopcosts feature so I may look into fixing that.

**Review by Ijwu — APPROVED** [review]
Still seems good to me.

**Comment by dewiniaid** [comment]
Closing this in favor of the upcoming HK June 2022 combined feature update

**Pull request closed without merging**
