### PR TITLE
Generate: improve error message for missing game

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
When using a world that doesn't exist, such as when missing an apworld, the user would just get a KeyError: `<name of world>`

## How was this tested?
Exception: No world found to handle game fAcToRiO. Did you mean 'Factorio' (100% sure)? Check your spelling or installation of that world.

### CODE REVIEW

**Review by black-sliver — COMMENTED** [review]
`if ret.game in AutoWorldRegister.world_types:` in line 469 and `else` in line 493 can go now?

**Comment by black-sliver** [comment]
As a side note, the fuzzy matching is not very good:
> No world found to handle game The Binding of Isaac Repentance. Did you mean 'The Legend of Zelda' (35% sure)?

:D

**Comment by Berserker66** [comment]
> 



> As a side note, the fuzzy matching is not very good:
> 
> > No world found to handle game The Binding of Isaac Repentance. Did you mean 'The Legend of Zelda' (35% sure)?
> 
> :D

I mean, half the words are there!

**Review by black-sliver — APPROVED** [review]
The last commit looks super confusing in the github view, but I think it's fine

**Pull request merged**
