### PR TITLE
Add a means to allow a client to opt into seeing ALL hints.

### PR DESCRIPTION
**Pull request by CaitSith2**
This works by means of the tag "ShowAllHints".  The server notify_hints looks for this tag, and will only send all hints even those that don't concern the slot in any way to clients with the tag.

My main motivation for implementing this is so that AginahBot can specify the "ShowAllHints" tag, since only one player is allowed to connect aginahbot to the server anyways.

### CODE REVIEW

**Comment by JarnoWesthof** [comment]
Seems to me this could be added to the spectator slots,I dont know if need a new tag for this

**Comment by Ijwu** [comment]
I'm very wary to move forward with a change like this while possible changes to hinting as a whole are being discussed. I think we should put this on a short hold until we figure out which direction we want hinting to go.

**Comment by Alchav** [comment]
Will this send the hints every time someone uses !hint or only when the hint is created? Because I'd prefer to only get pinged by the bot once per hint

**Comment by Ijwu** [comment]
> Will this send the hints every time someone uses !hint or only when the hint is created? Because I'd prefer to only get pinged by the bot once per hint

Sounds like a bot problem and not a hinting API problem.

**Comment by Ijwu** [comment]
WRONG BUTTON SOZ.

**Comment by Jarno458** [comment]
so i think this is good for a spectator slot. but if you prefer to keep it a tag, than plz also include an update to the docs to specify and explain the tag

**Comment by Jarno458** [comment]
Clients can now view hints for all players using the data storage `Get` hints_team_slot, and a client can also stay up to date on all new hints using the data storage `SetNotify` on the same key(s)

**Comment by Berserker66** [comment]
@CaitSith2 is this still needed? As Jarno pointed out, the data is now available at least.

**Comment by ThePhar** [comment]
I'm gonna make the executive decision and close this PR since there's been a lot of changes to the API since without new updates. Can always re-open it later.

**Pull request closed without merging**
