### PR TITLE
Zillion: remove rom requirement for generation

### PR DESCRIPTION
**Pull request by beauxq**
## What is this fixing or adding?

Generating a Zillion game no longer requires the rom.
(Playing still requires it, of course.)

Summary: The data `generate_output` was accessing before (item placements, player names, other randomizations) is put into json and that json it zipped into the `APPatch`.
Then at patch time, it extracts that json and does what `generate_output` used to do.

also included in the zilliandomizer package update:
(worth putting in AP patch notes)
- hallway breads respawn infinitely for farming health

(not worth putting in AP patch notes)
- lots of cleaning and typing improvements
- minor movement logic fix
- a lot of work to be able to serialize data to json
- a minor determinism error fixed (something that doesn't affect logic so it wasn't caught in determinism tests)

the zilliandomizer package diff: https://github.com/beauxq/zilliandomizer/compare/v0.6.0...v0.7.0

## How was this tested?

- renamed rom (so generate wouldn't be able to find it)
- generated game
- started multiserver
- returned rom name to normal
- opened patch with ZillionClient
- played through game

### CODE REVIEW

**Comment by silasary** [comment]
Neat. Have you tested loading an existing patch with the new client? 
Does the possibility of breaking backwards compatibility with ongoing asyncs matter? 
I don't care either way, just want to ask if you've considered it.

**Comment by beauxq** [comment]
> Neat. Have you tested loading an existing patch with the new client? Does the possibility of breaking backwards compatibility with ongoing asyncs matter? I don't care either way, just want to ask if you've considered it.

I thought about the compatibility change, but the patch methods are so different that I didn't think it would be worth it to maintain both.

This will require the patcher to use the same version as the generator. (not the same version, but the same "before or after" this change)

But none of the "play-time" communication interfaces are changed.
So a player in the middle of an async, might already have the patched version of the rom, and can play it on the new client and server. Or they might have to use an older AP to get their patched rom, and then they can play on the newer client (or on the older client).

**Comment by black-sliver** [comment]
Can we add an extra field to the `*.apzl/archipelago.json`, bump the `version` field and if the new field is used, also bump the `compatible_version` field so that the error path is clean? For old patches you could then still use evermizer.com/apbpatch and new patches would get rejected by it until i implement the extra field that tells the user to use ZillionClient instead?

For the extra field, I think maybe we could even share that with procedure path and call it something like `"procedure": ["custom", []]`?

**Comment by beauxq** [comment]
> Can we add an extra field to the `*.apzl/archipelago.json`, bump the `version` field and if the new field is used, also bump the `compatible_version` field so that the error path is clean?

I'm not sure whether I understand all of what you're saying here.

It doesn't seem right to change the version number in core every time a game changes its patch method (keeping the vision of some day moving all games out of core).

Whatever the solution is, it should be something that works for games that have never been in core, and never will be in core.

What do you think of this? https://github.com/ArchipelagoMW/Archipelago/pull/2887

**Comment by black-sliver** [comment]
Oh, guess i was unclear.

The current spec of APBP (or APContainer) did not expect for worlds to provide a hook on how to apply them, so what I am suggesting here is that we add to the spec that a patch file can declare to require custom handling from the world, and bump the version number once to make old code error out for those patches.

**Comment by beauxq** [comment]
> The current spec of APBP (or APContainer) did not expect for worlds to provide a hook on how to apply them, so what I am suggesting here is that we add to the spec that a patch file can declare to require custom handling from the world, and bump the version number once to make old code error out for those patches.

It's not `APContainer` that was providing that hook.
That's what `APPatch` in https://github.com/ArchipelagoMW/Archipelago/pull/2808 was for.
Whatever implements that interface will work will work.
Rather than checking the version number, you check to see if it implements that interface.

**Comment by black-sliver** [comment]
Maybe to be even more clear:
If a patch can be identified as lttp-style APBP, you don't need python or AP to apply it at all. https://github.com/black-sliver/apbpatch (hosted at evermizer.com/apbpatch ) is an alternative implementation of a tool to apply lttp-style APBPs.
The spec is loosely defined here: https://github.com/black-sliver/apbpatch/blob/master/FORMAT.md

**Comment by black-sliver** [comment]
Typically
> Could not read delta.bsdiff4 from zip: file not found!

However with APProcedurePatch, or if you add any other custom handling on top of delta.bsdiff4, this kind of error detection can not work anymore, hence me suggesting to bump the version and adding a procedure = custom marker.

**Comment by beauxq** [comment]
This Zillion change doesn't add "any other custom handling on top of delta.bsdiff4"

I support you having good error checking for evermizer.com/apbpatch - but this doesn't seem that relevant to this pull request.

This changes Zillion to use a simple `APContainer` like Mystic Quest or Factorio.

If you don't want to run this python code, I don't think it would be worth it for you to support the new Zillion patches in evermizer.com/apbpatch

There's no delta.bsdiff4 involved anymore.

**Comment by black-sliver** [comment]
But the APContainer format changed between 0.4.4 and 0.4.5 in that you can now officially have custom handling. Zillion requires custom handling, so Zillion should add a marker, and since the marker does not exist in version 5, it should bump the required version to 6.

Factorio was an outlier so far, and for MQ we did not go into this discussion for whatever reason.

**Comment by black-sliver** [comment]
I don't think it's fair for me to take this out on Zillion fwiw, we should have had this discussion earlier. However the error message this produces for trying the new .apzl on old AP is nicer.

> Exception: File (version: 6) too new for this handler (version: 5)

vs

> KeyError: "There is no item named 'delta.bsdiff4' in the archive"

**Comment by beauxq** [comment]
> Factorio was an outlier so far

My list was not exhaustive...
OoT
KH2
FFMQ
Factorio
Adventure
...and lots more apworlds that aren't in core

Plain APContainers that aren't APDeltaPatch have been around for a long time.

And the custom handling isn't directly related to `APContainer`.
There's nothing in the actual file that makes it any different from these.
The only difference is in the Python code that's reading the file.

**Comment by beauxq** [comment]
> I don't think it's fair for me to take this out on Zillion fwiw, we should have had this discussion earlier. However the error message this produces for trying the new .apzl on old AP is nicer.
> 
> > Exception: File (version: 6) too new for this handler (version: 5)
> 
> vs
> 
> > KeyError: "There is no item named 'delta.bsdiff4' in the archive"

I think something like that would be good.
But it seems like it should be in a different pull request.

**Comment by black-sliver** [comment]
Of those, 
- Factorio is not a Patch. That's why I called it an outlier.
- KH2 is not a Patch
- OoT could have had a similar system to Bsdiff where "if this file exists, then it's an OoT patch".
- FFMQ and Adventure should've raised the issue already

However just because we missed updating the spec and the meta data update and bumping the version for KH2 et al does not mean that we shouldn't do that now - now that we have APContainer -> APPatch -> AP*Patch inheritance and a clear idea of APPP.

**Review by black-sliver — APPROVED** [review]
I'll approve it as-is, but I still strongly believe that any Patch that requires custom handling should have a marker that says so, and adding that marker requires bumping the version.

This can be in a separate PR though, as you suggested. The separate PR will have to touch Zillion again to add this marker, which is why I wanted to make it part of this PR.

**Comment by black-sliver** [comment]
Continuing this in https://github.com/black-sliver/apbpatch/pull/2 and https://github.com/ArchipelagoMW/Archipelago/pull/2536

**Pull request merged**
