### PR TITLE
CommonClient: fix json prints not being logged in UI mode

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
fix json prints not being logged in UI mode

## How was this tested?
quickly

### CODE REVIEW

**Review by black-sliver — CHANGES_REQUESTED** [review]
nope

---

also the log contains the ansi terminal color codes. not sure if that is wanted or not, but i would've expected the log to be plain text?

**Comment by Berserker66** [comment]
That turned more complex than I initially thought, but I should have it now: 
image

**Comment by black-sliver** [comment]
Sorry, didn't find time to actually run it this morning. I'll test it tonight, but
do exceptions still show up in the UI now? I feel like that relied on the UI being connected to the logger, and we filter the logger now?

**Comment by Berserker66** [comment]
I have not tested that yet either.

**Review by black-sliver — APPROVED** [review]
When doing a bad `/connect`, I see `OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 1234, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1234)` in the log and terminal, so that should be fine.

**Pull request merged**
