### PR TITLE
Blasphemous: Remove poptracker pack from setup guide

### PR DESCRIPTION
**Pull request by TRPG0**
It doesn't work on the current version anymore.

### CODE REVIEW

**Review by NewSoupVi — APPROVED** [review]
Sure

**Review by Exempt-Medic — APPROVED** [review]
LGTM

**Comment by black-sliver** [comment]
> It doesn't work on the current version anymore.

Can you explain? Is the AP rando now incompatible to the solo rando, or is the pack broken and unmaintained? Or is PopTracker broken and the pack doesn't work anymore?

**Comment by TRPG0** [comment]
> Can you explain?

The poptracker pack was originally made to work with both Archipelago and standalone Blasphemous randomizer by making use of a websocket server, and since Blasphemous has to rely on c-wspp for WSS support, the websocket server doesn't work for multiworld anymore. It would technically still work in standalone Blasphemous randomizer, but Damocles decided to just cut it in favor of an in-game map tracker that he made instead, which is what we recommend people use instead now.

**Comment by black-sliver** [comment]
Interesting. I am wondering if I should "fix" (i.e. make it more complete) c-wspp then. I never expected that to end up being used outside of what MultiClient asks from it.

**Comment by Exempt-Medic** [comment]
It's also worth noting that, at this point, the PopTracker pack's logic is heavily outdated compared to both Blasphemous Randomizer and the AP Randomizer.

**Review by black-sliver — APPROVED** [review]
Thanks for the explanation and I agree that it should be removed (for now at least; if it got replaced, probably forever).

**Pull request merged**
