### PR TITLE
Stardew valley: Emergency 1.6 fixes

### PR DESCRIPTION
**Pull request by agilbert1412**
## What is this fixing or adding?
I went through the entire changelog for the newly release Stardew Valley 1.6, and categorized every single change into 5 categories, based on the work required to make them compatible with the randomizer.

This is the work for the category "Emergency", because the new game introduces actual softlocks in the randomizer due to the logic becoming invalid. It would be very important to get these fixes for the release.

The next PRs will not be as critical and can be mitigated by the mod, or simply ignored by the player as an "incomplete" experience that still works.

## How was this tested?
Unit tests. It's changed requirements based on a textual changelog, and none of the actual code has changed, only specific values in it.

### CODE REVIEW

**Review by Jouramie — APPROVED** [review]
Code LGTM. It's only config changes, nothing risky. 

Once this is merged, generation from source will be compatible with both Stardew Valley 1.5 and 1.6, which is definitely the way to go.

**Comment by Berserker66** [comment]
Do you really want this path? The way I see it, telling people to downgrade and using the for weeks tested version seems much better than merging in the rushed changes, that may have missed something, possibly leading to a broken version you cannot fix for weeks/months.

**Comment by agilbert1412** [comment]
@Berserker66 People will still play on 1.5 regardless, as the 1.6 mod is not ready.
I don't know when it will be ready (the changelog we got yesterday is quite big), but when it is, and fully tested, I need to be able to release it.

These changes are **not** the full set of backend changes that we will want to make. But they are the ones that are needed to avoid people getting softlocked. In other words, even if the 1.6 mod gets ready, I won't be able to release it for months (until the next AP release) if I don't get the changes from this PR.

The "next layer" of changes for backend will be stuff like adding the new items to the existing settings. For example, adding new crafts to craftsanity. These changes are important, as without them the randomization will feel "incomplete", but they are not critically necessary, as an incomplete randomization is still playable. So I will not be pushing to get them in 0.4.5, I'm fine having an "incomplete" randomization for a while. It will also allow some back and forth between 1.5 and 1.6, specifically once the mod seems ready but isn't fully tested, I'll probably tell people "try it, but if things go wrong, downgrade".

As you might notice, the logic changes in this PR do not adapt to the 1.6 changes. They adapt to Max(1.5, 1.6), so that both versions are garanteed winnable.

**Comment by agilbert1412** [comment]
Closing this PR as we have decided to not even try to release a 5.x.x mod compatible with 1.6, so the logic changes won't be needed

https://discord.com/channels/731205301247803413/1208847391671980143/1220792268483465236

**Pull request closed without merging**
