### PR TITLE
Docs: Update Trap classification comment

### PR DESCRIPTION
**Pull request by Exempt-Medic**
## What is this fixing or adding?

It no longer says Nothing items should be traps.

## How was this tested?

Reading

### CODE REVIEW

**Comment by Berserker66** [comment]
The idea is that Nothing items should trigger trap item handling in games like LttP. So, for me, this is the wrong way around.

**Comment by Exempt-Medic** [comment]
> The idea is that Nothing items should trigger trap item handling in games like LttP. So, for me, this is the wrong way around.

No other game has Nothing items that are traps and every world dev I've asked has said they should be Filler not Traps. So for everybody else, this is the right way around.

**Comment by Berserker66** [comment]
So they  didn't read my comment then. And the solution is to delete the comment?

**Comment by agilbert1412** [comment]
I don't understand what would be the point of marking a nothing item as trap. To me, a trap means something negative. Establishing that a useless item should be a trap has unfortunate implications.

For example, in a macguffin hunt (Minecraft Egg Shard), if the player chooses something like "100 Macguffins exist, I need to find 80 to win", then 20 Macguffins are completely useless. Some worlds may mark all 100 as progression, while other worlds may choose to mark 20 as useful or even filler. But if useless items should be traps, then it logically follows that these extra macguffins should have the flag "trap" as well (or instead).

Plus, from the Discord conversation, I also got the impression that pretty much everyone agrees that nothing items should not be traps. Whether existing games have followed the existing documentation is a separate question entirely, and people who have followed it, as well as people who have not followed it, can have an opinion on this. And the existence and technical limitations of alttp should not dictate how the entirety of the world API should behave.

**Review by agilbert1412 — APPROVED** [review]

**Review by Jouramie — APPROVED** [review]

**Comment by Jouramie** [comment]
IMO, good naming is better than good doc. It makes more sense to have "nothing items" as filler than as trap. It's more intuitive and easier to understand for newcomers.

**Review by Alchav — APPROVED** [review]

**Comment by NewSoupVi** [comment]
Considering filler is also 0 in this bitflag (i.e. "no classification"), this makes most sense to me as well.

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
