### PR TITLE
Explaining the "Style Lockdown"

### PR DESCRIPTION
**Pull request by LegendaryLinux**
I'm trying to explain the intent of the "style lockdown" and what it actually means.

Little changes like adding a button or a couple new select elements are perfectly fine. Tweaks to styles specific to a PR's content are also probably not a problem. For example, if you build a new page which needs two side by side tables and you need to write a CSS file specific to your page, that is perfectly reasonable. 

The PRs that I reject are primarily ones which change the overall look and feel of the website. It is valuable to maintain a consistent design throughout. Therefore there are a couple files which I guard closely, but could be convinced to make tweaks with designer approval. These closely guarded files are:
- `globalStyles.css`
- `islandFooter.css`
- `landing.css`
- `markdown.css`
- `tooltip.css`

I am admittedly also rather protective of the `/player-settings` and `/weighted-settings` pages, although again, I am not without reason and can be convinced to make changes if they improve the user experience.

I've been told people are simply not suggesting changes to the site because they assume I will immediately shoot them down, which is not the case. Content that mandates new styles or assets costs me money unless I can adapt existing styles to it. Therefore, if a PR adds content to the site for which no styles yet exist, I will have to work with the designer to get those styles created. This isn't me trying to shut anyone down, I'm just saying it's going to take a little bit.

Also, although I pay for the site styles solely out of pocket, I'm not trying to make people feel guilty. I just want it to be known why your content change might not be merged immediately. I'm trying to save to buy a house, so my budget for site designs is a little tighter than it used to be, **but the budget is not gone**.

Regarding new themes, they come in every now and again, and sometimes I get excited and pay the designer for them if someone suggests a really cool idea (stone theme happened this way). At the moment, I have no ideas for new themes. If someone suggests one and people like it, it'll probably happen as soon as budget allows.

So the goal here is to take this intent, and write it into a markdown file so new developers know what to expect when working on new content for the WebHost. I know the markdown file included definitely does not cover all this, so feel free to suggest edits. I'll probably make another commit before long to include more of the above info.

### CODE REVIEW

**Review by SoldierofOrder — APPROVED** [review]
I am aware that all of this is out of my scope, and that my approval does not matter here when it comes to the actual message of the file, but it had words that were not code, so I scanned it for clarity, flow, and punctuation. 🦺 Checks out.

**Review by Ijwu — CHANGES_REQUESTED** [review]
I do not believe that outright blanket saying that PRs which edit look and feel will be rejected is constructive. It's normal to have an intended look and feel and to discourage divergence from it. I, however, find proclaiming an umbrella PR rejection to be discouraging to potential contributors at a minimum.

In the short term: I want that language changed. 

Perhaps something describing how there will be increased scrutiny of changes which overlap with the look and feel. You should acknowledge it is possible for an external contributor to make design changes and maintain look and feel and operate on that premise.

In the long term:
I believe the best future state of this should be the inclusion of a definitive style guide which fully describes the complete intended look and feel of the site. People should be encouraged to make pull requests against the site in all capacities, they just need to be provided with documentation on what is acceptable and what isn't other than a blanket rejection.

I understand producing style guides is difficult and time consuming. I am willing to pay our designer for their time on this out of my pocket, since I am the requestor of the work. @LegendaryLinux would you be willing to have this conversation with them and relay any info back?

**Comment by LegendaryLinux** [comment]
As the point of this document is specifically to explain that changes to the look and feel of the website are restricted, I believe the wording as written conforms to my intent as the primary caretaker of the site. It is in fact my intention to discourage developers from submitting PRs which change the look and feel.

I also think you might be focusing too much on one specific sentence, and not the full context in which it is written. The document makes it clear that content changes, and indeed small style changes, are fine. Moreover, it explains that content changes which require new styles are accepted.

> Perhaps something describing how there will be increased scrutiny of changes which overlap with the look and feel. You should acknowledge it is possible for an external contributor to make design changes and maintain look and feel and operate on that premise.

I believe the current form of the document sufficiently expresses the increased scrutiny for specific files as seen here:
https://github.com/ArchipelagoMW/Archipelago/blob/style-lockdown-explanation/WebHostLib/README.md?plain=1#L27

I also believe it describes how an extra step exists between new content, my styling it with the designer, and the PR being merged into main:
https://github.com/ArchipelagoMW/Archipelago/blob/style-lockdown-explanation/WebHostLib/README.md?plain=1#L19

Finally, I do not want to engage anyone else in payment for the site design and assets for several reasons.
1. It makes identifying who owns copyright to each asset more complicated.
2. If someone pays for different styles then submits them, they may well feel entitled to their work being included on the site, and offended if it is not.
3. It's very easy to get into a dick measuring contest when it comes to money spent, which is why no member of AP pays for something already covered by someone else.
4. I can see a future where people want to pay me to pay the designer to make more themes, which is more work for me.

As for a style guide, that may be possible. For reasons mentioned above, I will pay for it if and when the time comes.

**Comment by LegendaryLinux** [comment]
By way of example here, I looked at Phar's new random button on the `/player-settings` page and I think it looks good. I need to go over it with the designer because it needs some colors for each theme, but I fully intend to accept his PR once styles are applied.

**Comment by Ijwu** [comment]
As long as language remains which states there will be outright rejection, I am not approving this PR. I am telling you directly that I want to see that replaced with something which gives steps towards cooperation, not rejection. If you feel that lines 19 and 27 explain that adequately then just remove the portion on rejection. 

I am indeed focusing on one sentence. That is the sentence I am giving feedback on. The rest of the document is good and explains your logic and reasoning within reasonable bounds.

**Review by Ijwu — APPROVED** [review]
Per conversation with Farrak, we're on the same page. I did not have a problem with site look and feel curation, I had a problem with there being language which seemed outright discouraging.

We do want to discourage people from coming out of the blue and editing global styles, it is intentionally curated. However, we do want the language to be constructive and to denote that we _would indeed_ like people to submit PRs, but there are standards.

Thanks for working with me on this.

**Pull request merged**
