### PR TITLE
Tests: test that item/location name groups are not empty

### PR DESCRIPTION
**Pull request by black-sliver**
## What is this fixing or adding?

Adds a test to see if any game defines empty item/location name groups, which is likely a bug.

## How was this tested?

Unit tests.

### CODE REVIEW

**Comment by black-sliver** [comment]
SoE fixed in #2747

KH2 failing for `Location name group "Armored Xemnas" of "Kingdom Hearts 2" is empty` @JaredWeakStrike

**Review by Berserker66 — APPROVED** [review]

**Comment by alwaysintreble** [comment]
maybe not this PR but since we're adding a new module for groups probably want to move the existing tests to this module such as https://github.com/ArchipelagoMW/Archipelago/blob/main/test/general/test_items.py#L17

**Review by Jarno458 — APPROVED** [review]
LGTM

**Comment by black-sliver** [comment]
> maybe not this PR but since we're adding a new module for groups probably want to move the existing tests to this module such as https://github.com/ArchipelagoMW/Archipelago/blob/main/test/general/test_items.py#L17

Makes sense, yeah. I'm waiting for KH2 before I do something that might conflict later. :sweat_smile:

**Comment by JaredWeakStrike** [comment]
> > maybe not this PR but since we're adding a new module for groups probably want to move the existing tests to this module such as https://github.com/ArchipelagoMW/Archipelago/blob/main/test/general/test_items.py#L17
> 
> Makes sense, yeah. I'm waiting for KH2 before I do something that might conflict later. 😅

https://github.com/ArchipelagoMW/Archipelago/pull/2757

**Comment by black-sliver** [comment]
> > maybe not this PR but since we're adding a new module for groups probably want to move the existing tests to this module such as https://github.com/ArchipelagoMW/Archipelago/blob/main/test/general/test_items.py#L17
> 
> Makes sense, yeah. I'm waiting for KH2 before I do something that might conflict later. 😅

I put it on my TODO list. I think merging this now is better than delaying it.

**Pull request merged**
