### PR TITLE
Text Client DeathLink toggle. (default off)

### PR DESCRIPTION
**Pull request by CaitSith2**

### CODE REVIEW

**Comment by KonoTyran** [comment]
a possible workaround is to have a tag/flag set that will give a client ALL bounce messages even ones not specifically targeted to them. I think setting a tag in the text client just to view specific  bounce messages is kind of awkward as well.

**Comment by Ijwu** [comment]
Where are we at on this @Berserker66? Cait has made some changes since your feedback, does it make it better or worse?

**Comment by Berserker66** [comment]
It goes sideways, I suppose.

**Comment by KonoTyran** [comment]
I think the best solution is the have a new tag the server recognizes something along the lines of `observer` that will have the server send ALL bounce packets regardless of who they are aimed at to it. that way it can do whatever it wants with bounce packets without having to identify itself as `deathlink` or `mc35` or wheatever.

**Comment by Ijwu** [comment]
I will ask, then, @CaitSith2, what is the purpose of the change here? Is it to allow the TextClient to receive messages that it otherwise is unobservant of (such as deathlinks) or is it to enable tag editing on the TextClient?

**Comment by CaitSith2** [comment]
The original intent was to be able to observe deathlinks, and possibly other bounce packets that might have observable details.  I can see that in order to observe MC35, I would have to add a handler for it.  (In text client, it can just announce player x killed mob y. The idea behind the adding of tags, is to be able to be selective of which bounce packets to observe.

**Comment by Ijwu** [comment]
Thanks for the clarification. I find that adding/removing tags on the fly is useful for an advanced user (and having advanced features in software isn't a bad thing). Is this something _worth_ genericizing as @KonoTyran is suggesting? Is this _worth it_ for _everyone_ to be able to toggle on an `Observer` tag at all?

My honest opinion is: no, it's not worth genericizing. So, I think this should ship as-is if it is seen as a value-add.

**Comment by KonoTyran** [comment]
I think berserker's main concern was that if the text client sets the "deathlink" flag an other can see it. they think that the text client can send deaths, even though its just for monitoring/displaying them.

**Comment by Ijwu** [comment]
> I think berserker's main concern was that if the text client sets the "deathlink" flag an other can see it. they think that the text client can send deaths, even though its just for monitoring/displaying them.
> 
> edit: and my concern as well.

My response to this concern is: so? So what if someone else is, what, concerned(?) that the given text client can send deathlinks? As long as it doesn't actually send deathlinks then it's probably fine.

**Comment by CaitSith2** [comment]
Now added in support for a "BounceObserver" tag for observing ALL bounce packets without knowing what tag is needed to see it.  Also made the text client aware of MC35 in order to display some info about the mobs killed in a minecraft world that sends MC35 bounce packet.

Server will now also block sending of bounce packets coming from Text Clients as well as Trackers.

**Comment by JarnoWesthof** [comment]
I personally think the commen client should not know anything about the existence of `MC35`

**Comment by CaitSith2** [comment]
Which is why MC35 is handled in the TextClient portion of the common client.  Even then, one still has to add the tag in order to receive the bounce packet to begin with.

**Comment by JarnoWesthof** [comment]
But only a minecraft client should know about MC35
Imagine if I add a coopsync bounce packet to timespinner, you don't want the textclient to start spamming unknown packet messages

**Comment by Ijwu** [comment]
I agree that the CommonClient shouldn't have game knowledge (what MC35 is and how it works). If you want to implement parsing of and user friend display of that data then it may be best to implement BouncePacket log filters or something of that sort which maybe exist in an external module.

**Comment by CaitSith2** [comment]
Okay, CommonClient itself no longer directly knows about MC35 nor any other game specific bounce packets.  This is now handled within a decoder in the AutoWorld.

**Comment by Ijwu** [comment]
I'm aware that I'm going to sound argumentative, I'm sorry. 

I'm uncomfortable with client logic living in the world object. It's convenient, but also commits us to muddy the water for what the world object is for. Previously it was just "here's how generation works" and now it's "here's how generation and client packet decode" works. It's not an easy precedent to work around for newer devs.

I like the idea of moving the decode logic outside of the client and placing it somewhere relevant to the world, however I cannot think of a good place to put it.

In the interest of moving this PR along, I think if you genericized things and kept everything up to bounce packet printing, but excluding the mc specific (or world specific) bounce decoding, I'd be all for accepting this. I find that the value add of everything around the mc packet decoding is high enough that having (and finding the right place for) world specific decoding isn't worth holding this up over.

**Comment by black-sliver** [comment]
> I'm uncomfortable with client logic living in the world object

We have DKC3 client living in worlds/dkc3 now, if that changes your opinion

**Pull request closed without merging**
