### PR TITLE
SM - Option to remove empty locations

### PR DESCRIPTION
**Pull request by Alchav**
Option that sets address to None if it is a local Nothing or NoEnergy item, setting the location to an Event and thus removing it from the list of active locations, since they are not collectable.

### CODE REVIEW

**Comment by Berserker66** [comment]
@lordlou your verdict?

**Comment by lordlou** [comment]
Doesnt
`hint_blacklist = {'Nothing', 'No Energy'}`
do this already? If not, then I think its good, if it was at least verified to work once.

**Comment by Alchav** [comment]
As far as I know the hint blacklist does not do that. If you intended for it to automatically remove these locations from hint consideration, then I can just take the setting out and make it do it automatically

**Comment by lordlou** [comment]
It was intented to fix this (https://discord.com/channels/731205301247803413/909599773949050890/916391229481173073) issue.

**Comment by Alchav** [comment]
Should I remove the option and just make it always do this

**Comment by lordlou** [comment]
Yes: I don't see why someone would want the old behavior.

**Comment by Berserker66** [comment]
@lordlou does it check out?

**Comment by lordlou** [comment]
Yes, it looks good.

**Pull request merged**
