### PR TITLE
ALTTP: Add "Silver Star" to differentiate progression/non-progression on non-ALTTP items

### PR DESCRIPTION
**Pull request by Kappatechy**
## What is this fixing or adding?
This adds a silver version of the "Power Star" that is used for non-native items, to make progression items visually distinct from non-progression items. This allows players to actually tell which purchasable, or otherwise "scoutable," items to prioritize, and which can be safely ignored for later.

Uses an updated basepatch, generated off of this branch: https://github.com/ArchipelagoMW/z3randomizer/pull/8

## How was this tested?
Games were generated using one ALTTP YAML with all non-local items, and several Bumper Stickers YAMLs. The ALTTP file was then loaded up, and several checks were collected, ensuring the stars looked correct based on which Bumper Stickers items they corresponded to. This was tested with chests, freestanding items, shop items, and Key Drop locations.

## If this makes graphical changes, please attach screenshots.
AP_16894030208794895037_P1_StarTest1000
AP_16894030208794895037_P1_StarTest1002
AP_16894030208794895037_P1_StarTest1003
AP_16894030208794895037_P1_StarTest1004

### CODE REVIEW

**Comment by Berserker66** [comment]
I  happen to know that this is based on someone else's work that you took.

**Comment by Berserker66** [comment]
As was discussed at a similar time when this feature was first brought forth, I do not accept features from people who don't want their stuff in AP LttP, this is even pinned to our discord channel. Taking their work, without credit and trying to smuggle it in past this rule is a very questionable action.

**Comment by Kappatechy** [comment]
It's one thing for a developer to build something for a completely different project and have it taken without permission for use in ours. It's another thing entirely for a developer to build something for _our_ project, something our players want to use, then change their mind and take it away from us. I can respect not porting things like Door Shuffle to Archipelago, due to some of their original developers never intending them for Archipelago and not being okay with them being ported. But not allowing use of work that was built _for this project,_ not even a recreation thereof, is going a step too far.

Furthermore, if independent development of another developer's concept is not sufficient, then we need to discuss the new Bombless addition to AP LTTP. It is _identical_ to an existing option in other branches of the randomizer known as Bomb Bag-- preventing the player from using bombs until they first find an upgrade to enable carrying them. And I know for a fact that you did not get permission from the original developers of Bomb Bag to add it to Archipelago, as you had not even heard of the setting until 24 hours ago.

**Comment by eudaimonistic** [comment]
If the original author intended for their work to remain available to this project, they would simply not have closed the PR.  Closing it fully speaks to not wanting it's inclusion.

Can you prove that Bomb Bag as you've described it is a full 1:1 ASM lift, in the same manner as this PR clearly is?

**Comment by krelbel** [comment]
Hi, I'm not sure why everyone's avoiding naming me or referring to the previous PR for this feature, but here's the previous PR in case anyone would like to compare them: https://github.com/ArchipelagoMW/Archipelago/pull/2139

**Comment by Kappatechy** [comment]
Since the creator of the previous PR is here now (which, honestly, surprised me), I think it best we take a moment to hear his thoughts on the matter. This would all be resolved quite simply and easily if it turned out he was okay with all this.

So, krelbel. What are your thoughts on this matter?

**Comment by krelbel** [comment]
Thanks for asking :) I would be happy to grant permission for anyone to use my previous PR, fork it, polish it up, and complete it.  It's still a feature I'd love to see in AP (I still play AP about once a week, even though I'm no longer allowed on the development server).  If I understand correctly, the licensing of my work allows for this as well.

I think it would probably be cleaner to do it that way (assuming our implementations are similar enough; I haven't looked too closely yet), just from an attribution perspective, rather than trying to reimplement it from scratch.  Sorry I wasn't around to help you out with this, please let me know if there's anything else I can do to help.

**Comment by eudaimonistic** [comment]
You weren't around to "help" Kappa (what, take your work?) because you proved yourself to be a danger to the community Krelbel, and you held no remorse for the personal toll that you personally would not have to bare.  You closed the PR citing harassment while simultaneously threatening to reignite intercommunal conflict, in the Discord.  Presumably your comments here recant those accusations?  It's hard to believe in your sincerity here.  It was made perfectly clear that your intent to disobey the wishes of code authors was against community values, and would harm many others.

Kappa didn't "ask" you initially, nor were you attributed.  This PR was closed for that reason, and you showing up now doesn't change that.  Archipelago takes attribution very seriously.  We demand it up front, and it isn't optional.  You don't get to show up after the fact and wave a magic amnesia wand to make the initial transgression go away.

**Comment by krelbel** [comment]
I don't believe Kappa was attempting to take my work; my previous PR was a while ago now, and like he said, this is a pretty trivial code change and there's really only one way it can be implemented. Even the silver star color being the same is likely coincidence; I tried several different colors in my original change, attempting to add a third star color as well, but found that there was only really one good color available already, and adding another color (for example, a blue star to differentiate "nice to have" items) would have required a lot more work beyond my skill level).

I'm not interested in relitigating old drama (it's clear that I'm still not welcome to do so, and that's fine, I'm happier purely as an AP user than I was attempting to be an AP developer anyway). Kappa asked me a question, I answered it making my intent clear, and granted permission as well as I could. I also just reopened https://github.com/ArchipelagoMW/Archipelago/pull/2858 in case people would rather resume this work there instead, if people really believe that Kappa's work copied my expression of the idea behind this change (illegal) instead of simply reimplementing the same idea behind this change with purely coincidental similarities (legal). Personally, I don't believe Kappa did anything improper in this PR, and I don't think he (and the members of the AP community that want this feature) should be punished for its coincidental similarity to an old PR by an unpopular developer who's been long gone anyway. But Berserker seems to think this was "based" on my work, and I'm not sure what made him think that.

I'm sorry for how I behaved in the past, both on the discord server and in my rash decision to "take my ball and go home" by closing my original PR for this feature. I'm not asking to be forgiven for any of that, I just think this is a cool feature that I'm glad to see someone else implementing, and I sincerely hope that any remaining hurt feelings regarding my past actions won't get in the way. I don't think it's a good idea to prohibit any implementation of this feature from ever being submitted by anyone simply because the first person who got around to doing it isn't welcome anymore.

**Pull request closed without merging**
