### PR TITLE
The Witness: Improve starting inventory

### PR DESCRIPTION
**Pull request by NewSoupVi**
1. If an item gets put into the starting inventory, but already exists due to the settings, one instance of it is removed.
2. If an item that does not naturally exist in the settings is put into the starting inventory, it will become logical and associated data is put into slot_data so the client can actually handle it. (only matters for doors & lasers, adding a symbol without symbol shuffle obviously doesn't do anything)

Edit: 3. Made some slot_data changes in order for !get_item and /send to work client-side for doors not part of the mode

Also in this PR: Docs updates (Describing the above changes + How Puzzle Skips work + fixing a minor outdated instruction)

### CODE REVIEW

**Comment by NewSoupVi** [comment]
Test fail? Oh no, let me do an investigate

**Comment by NewSoupVi** [comment]
Wait it's a Zillion error? o_O

**Comment by NewSoupVi** [comment]
I found a bug with these changes, I think. Let me investigate

**Comment by NewSoupVi** [comment]
Nvm, I forgot how my own code works :)

**Comment by Berserker66** [comment]
This might be good to mention to the user somewhere. Setup Guide, FAQ or such.

**Comment by NewSoupVi** [comment]
I think that should do :)

**Pull request closed without merging**
