### PR TITLE
Hollow Knight get_filler_item_name

### PR DESCRIPTION
**Pull request by Alchav**
Took this out of the earlier PR because I was seeing errors, but I believe these were related to this issue: https://github.com/Ijwu/Archipelago.HollowKnight/issues/65 when I was connecting. These items should be fine.

### CODE REVIEW

**Comment by dewiniaid** [comment]
I'd like to see this be based on what's randomized, so you won't see geo rocks in unusual places if you don't have geo rocks randomized; likewise for soul totems (which may not be the best garbage items anyways, as they have useful effects in some places).  This also helps if someone is running mystery settings and is trying to learn what their settings are.

- `One_Geo` is a safe option all the time.  It's not even a randomizable category, normally.  (The normal One_Geo chest is not a check)
- `Lumafly_Escape` (not in your list) and the junk pit geo chests are good options if junk pit is on.  Probably if it's off, too, other than confusing mystery settings players who might think junk pit is on.
  - People might complain that this means no more meme check.  That's on them.
- The geo rock options should only be included if geo rocks are shuffled.
- The soul totem options should only be included if soul totems are shuffled.
- Lore is also an option if lore is shuffled
  - Make sure this doesn't include lore tablets excluded by WP settings.  We don't want people thinking white palace is randomized when it isn't.
- Other possible options might include Quill at a low weighting.

Also, generation can replace things with additional geo rocks -- namely when level two spells are disabled.  I'd like to see that pull from the junk fill list instead of always being Geo_Rock-Default.

**Comment by Alchav** [comment]
@dewiniaid I did not include Lumafly_Escape or Lore tablets as other games with "Nothing" items do not have them included as filler options, so I thought leaving them out here would keep it consistent with the other games.

**Comment by Alchav** [comment]
Granted, those were decisions made by myself alone. I will add these items if you want them

**Comment by Alchav** [comment]
How does this look @dewiniaid

**Comment by dewiniaid** [comment]
Instead of hardcoding all of the per-randomization options, you can probably look at `hollow_knight_randomize_options["RandomizeGeoRocks"].values()` and such, likewise for lore, soul totems, and junk pit (though that reintroduces the Lumafly Escape).  As a bonus, this will make the junk fill roughly match the same distribution percentage as occurs in the vanilla game.  It also means a very small chance of the 420 geo rock being duped -- which is perhaps excessive as junk, but I think it's funny so it can stay in.  From this list, you can remove anything in the set returned by `self.white_palace_exclusions()`

The list for junk fill should probably be computed once rather than reconstructed every time a junk item is requested.  This either be done in `generate_early` or -- likely better -- cached the first time `get_filler_item_name` is called.

Perhaps (not to rewrite the entire PR, but... I go overboard; sorry) something akin to this *which I have not tested*:

```python

    def get_filler_item_name(self) -> str:
        if not self.cached_filler_items:
            fillers = ["One_Geo", "Soul_Refill"]
            exclusions = self.white_palace_exclusions()
            for group in (
                    'RandomizeGeoRocks', 'RandomizeSoulTotems', 'RandomizeLoreTablets', 'RandomizeJunkPitChests',
                    'RandomizeRancidEggs'
            ):
                if getattr(self.world, group):
                    fillers.extend(item for item in hollow_knight_randomize_options[group] if item not in exclusions)
            self.cached_filler_items = fillers
        return self.world.random.choice(self.cached_filler_items)
```

**Comment by Alchav** [comment]
I took your code as a base and went from there. How's this look?

**Comment by Alchav** [comment]
Combined into #663

**Pull request closed without merging**
