### PR TITLE
Created a general triggers and plando guide for Archipelago.

### PR DESCRIPTION
**Pull request by alwaysintreble**

### CODE REVIEW

**Comment by Ijwu** [comment]
Skimmed it and it LGTM.

**Comment by Berserker66** [comment]
I'll try to find some time soon to read through it proper. After a quick skim; it might be worthwhile to point out that all names can be found at https://archipelago.gg/api/datapackage, even for games that guide doesn't list (yet)

**Comment by alwaysintreble** [comment]
While that is true and the way I did it would definitely require more maintenance, the purpose of these guides is to be understandable and accessible. If you know what you're looking for you can search through the data package for it, sure, but for some games it can be very hard to find what you need so I'm unsure if that's a good reference.

**Comment by Berserker66** [comment]
Yeah, looks good. Thank you!

**Pull request merged**
