### PR TITLE
DS3: Add more options for weapon upgrade randomization

### PR DESCRIPTION
**Pull request by FridbergT**
Add range for possible upgrades, as well as setting percentage of randomized weapons

## What is this fixing or adding?
Weapon upgrade chances are locked at 33%, this changes it to a user configured setting. In addition there are now settings to set the range of possible upgrades. If min is accidentally set higher than max it automatically sets it to the same value as max, in which case all weapons would have the same value.

## How was this tested?
Generated a game and tested it, it sent the appropriate items. Generated about 10 different games without failure and compared the item data generated to the settings, checking that each weapon falls under the parameters set, as well as checking if it fits the probability percentage set.

### CODE REVIEW

**Comment by Berserker66** [comment]
@Marechal-L

**Comment by FridbergT** [comment]
Hey everyone, new here and excited to start contributing! Wondering if it makes more sense for me to turn this into a draft until #1301 gets pulled? Since this will break anyway as soon as that gets pulled 🤔

**Comment by Br00ty** [comment]
i showed this PR to marech before he left but he didnt have to much time to look at it, but he did like the idea of it and i just finished integrating it into the DLC build and did some test gens tonight, a couple things had to get changed around but its a great addition!

**Comment by FridbergT** [comment]
Brilliant! Thanks a lot 😁

I was just planning on waiting for the DLC build to merge and then I would update this PR with the dlc weapons if that makes sense? But whatever best works im down for, just excited to start contributing on this excellent project, thanks for the warm welcome appreciate it!

**Comment by Br00ty** [comment]
yeah, that makes sense! ended up getting it working with the DLC, and since we are in feature freeze until next month, we can easily just add this to the existing PR marech has open as well, if we want. we've got your option in the code now so thats all good! probably going to do a beta test this week and try to get some DS3 players in!

**Comment by FridbergT** [comment]
Brilliant! Would it be better as a general rule to do DS3 PR's on marechal's branch?

**Comment by Br00ty** [comment]
Thats just where ive been doing my PR's, just because i DM him and work on it together with him, but it wouldnt be a bad idea just to be able to integrate it with anything new that might be planned for an upcoming update.

**Comment by FridbergT** [comment]
Great, I'll keep that in mind, thanks for all the help!

**Comment by black-sliver** [comment]
#1301 says this can be closed

**Pull request closed without merging**
