### PR TITLE
Added Timespinner support

### PR DESCRIPTION
**Pull request by JarnoWesthof**
Generation testing passed, and spoiler log seems to give logical paths so i think the server side is done

YAML

### CODE REVIEW

**Comment by Berserker66** [comment]
Can I hit the Squash and merge button, or would you like to preserve the individual history?

**Comment by JarnoWesthof** [comment]
feel free to squash it

**Comment by Ijwu** [comment]
Please do not merge until all supporting documentation is in place. Timespinner will need a game guide at the minimum. @JarnoWesthof hit me up on Discord if you need info on how to do that.

**Comment by JarnoWesthof** [comment]
> Please do not merge until all supporting documentation is in place. Timespinner will need a game guide at the minimum. @JarnoWesthof hit me up on Discord if you need info on how to do that.

i was holding off on making all documentation until the client is ready, as i cant explain a user how to use it if its not yet publicly available

**Comment by Berserker66** [comment]
Thank you!

**Pull request merged**
