### PR TITLE
LTTP: Update playerSettings.yaml to require AP version 0.4.4

### PR DESCRIPTION
**Pull request by t3hf1gm3nt**
## What is this fixing or adding?
@alchav had changed the required version in the playerSettings.yaml to 0.4.3 as a part of #282, but the PR didn't end up getting into a release until 0.4.4. Updating yaml to make sure people have the proper required version if they ever use this template to play with KDS

### CODE REVIEW

**Comment by t3hf1gm3nt** [comment]
> I am not quite sure why there is a single AlttP yaml in AP root directory at all tbh

It's there until all the LTTP options are ported to get picked up by auto world
Once that is done, we'll finally be able to just remove this, I believe

**Comment by Alchav** [comment]
#2357 removes playerSettings.yaml

**Comment by t3hf1gm3nt** [comment]
If #2357 gets merged first, then I'll close this PR. Thanks for the heads up Alchav

**Review by black-sliver — APPROVED** [review]
I'm not the right person to review 2357, so gonna merge this for now.

**Pull request merged**
