### PR TITLE
Multiserver: rename all references to forfeit and deprecate it

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
Renamed all the host options to use `release_mode` instead

## How was this tested?
Generated and tested all of the commands locally on webhost and on multiserver both as client and as server

## If this makes graphical changes, please attach screenshots.
Screenshot_62
Screenshot_63

### CODE REVIEW

**Comment by Berserker66** [comment]
This changes the server to send release_mode instead of forfeit_mode, so will need testing with various clients

**Comment by ThePhar** [comment]
That would definitely break existing libraries, so we'll need to get all libraries to update for this.

**Comment by ThePhar** [comment]
If you're going to rename release all these to release, let's also refactor the name of this function signature and it's callers: `def forfeit_player(ctx: Context, team: int, slot: int)` to `release_player(...)`

**Comment by Jarno458** [comment]
I added forward compatibility support for this in the .Net Client 4.1+

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
