### PR TITLE
Test: fix setting seed from the hash of the seed method, rather than …

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
I'm guessing seed was meant to be called, rather than passed in as "bound method or function".

## How was this tested?
it is a test

### CODE REVIEW

**Comment by black-sliver** [comment]
I think seed was supposed to be configurable by the test in the [WorldTestBase](https://github.com/ArchipelagoMW/Archipelago/blob/main/test/TestBase.py#L114)  and this is wildly copied together with PyCharm resolving `seed` to `random.seed`? The player:int = 1 is also probably not supposed to be there? @alwaysintreble

**Review by alwaysintreble — APPROVED** [review]
seed was likely an accidental copy paste leftover that i didn't notice since pycharm resolved it correctly. player I like due to it being more readable so I'd personally prefer that stay but isn't that important

**Comment by black-sliver** [comment]
hm, but you put `{1: "Tester"}` instead of `{self.player: "Tester"}`

**Review by black-sliver — APPROVED** [review]
Anyway, proper `seed` can be added once required, so removing it is fine by me.

**Pull request merged**
