### PR TITLE
Factorio: use orjson

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
trial run of the orjson json library in Factorio

## How was this tested?
running Generate with Factorio involved.

### CODE REVIEW

**Comment by black-sliver** [comment]
to sum up what i said in discord, i see two things:
1. on current main output is not stable, making the orjson change hard to test. it looks like it places the same items in the same spheres, but at different locations
2. orjson dicts look like they are not ordered, but sorted by something like hash(key). Not sure if that happens when reading or writing, but in case of factorio it should not be a problem, i would like to tested that though once 1. is solved

**Comment by Berserker66** [comment]
1. should be solved by now

**Review by black-sliver — APPROVED** [review]
Generated spoiler for the same seed is identical between main and orjson.

Speed Improvement: 43% for all of factorio 
```bash
$ python -m timeit 'import orjson; [orjson.loads(open(f"data/{f}.json").read()) for f in ("fluids","items","machines","recipes","resources","techs")]'
1000 loops, best of 5: 258 usec per loop
$ python -m timeit 'import json; [json.loads(open(f"data/{f}.json").read()) for f in ("fluids","items","machines","recipes","resources","techs")]'
500 loops, best of 5: 454 usec per loop
```

However it should be noted that, as long as we only use it for factorio, the switch has a negative impact:
* it is not builtin (i.e. not shared between different venvs), using up cache and taking longer[^1] to load
* it uses ~10MB of RAM, which is a fair trade-off if we use it in more places


[^1]: loading a single, small file gives almost no improvement:
```bash
$ python -m timeit 'import orjson; orjson.loads(open("data/fluids.json").read())'
20000 loops, best of 5: 10.3 usec per loop
$ python -m timeit 'import json; json.loads(open("data/fluids.json").read())'
20000 loops, best of 5: 11.8 usec per loop
```

**Comment by black-sliver** [comment]
Re **EDIT** above: I remeasured
`python -c "import NetUtils; import orjson; orjson.loads('{\"1\":123456}')`
vs.
`python -c "import NetUtils; import json; json.loads('{\"1\":123456}')`
and the difference is 7.2MB

**Pull request merged**
