### PR TITLE
Fill: Changing deprecated option getter

### PR DESCRIPTION
**Pull request by Exempt-Medic**
## What is this fixing or adding?

Stumbled upon a generation that printed "UserWarning: Getting options from multiworld is now deprecated. Please use `self.options.accessibility` instead." This changes a single line in `fill` to fix this.

## How was this tested?

Generated with the same seed and it was no longer printed the warning.

### CODE REVIEW

**Review by NewSoupVi — APPROVED** [review]
Looks right

**Comment by black-sliver** [comment]
Hm, I feel like there was another PR that did this? Can someone check/dig it up and cross link?

**Comment by Exempt-Medic** [comment]
> Hm, I feel like there was another PR that did this? Can someone check/dig it up and cross link?

There's [this one](https://github.com/ArchipelagoMW/Archipelago/pull/2626) which is a draft, touches several individual worlds, and does not include this specific fix

**Comment by black-sliver** [comment]
I believe I was thinking about  #2516, but that touches a different file. (Always referencing 2626 is also good if someone opens that and wants to check the state of things.)

Anyway, I think #2749 should be merged first (because reviewing that again is more work), which will break this PR, and then this should be updated and merged. Gonna do that soon if there is no veto over there.

**Review by black-sliver — APPROVED** [review]

**Pull request merged**
