### PR TITLE
Core: Require excluded locations to be reachable with full/locations accessibility

### PR DESCRIPTION
**Pull request by Exempt-Medic**
## What is this fixing or adding?

Changes full/locations accessibility and all_state_can_reach_everything tests to require excluded locations to still be reachable.

## How was this tested?

Unit tests and a generations with every game with default options except for DKC3.

### CODE REVIEW

**Review by ScipioWright — APPROVED** [review]
It's weird this wasn't like this to begin with.

**Review by NewSoupVi — APPROVED** [review]
Another case of "any issues that crop up with this I would consider a bug"

**Review by NewSoupVi — CHANGES_REQUESTED** [review]
Actually, both the `WorldTestBase` `test_all_state_can_reach_everything` and the `test_reachability.py` `test_default_all_state_can_reach_everything` work around excluded locations. These unit tests should be changed as well. Then we will see if this actually breaks any worlds too haha

**Review by NewSoupVi — APPROVED** [review]

**Comment by NewSoupVi** [comment]
Since there are currently no issues with this, I will merge it, but if issues crop up and they can't be solved, we might have to revert it

**Pull request merged**
