### PR TITLE
Core: Floor and ceil in datastorage

### PR DESCRIPTION
**Pull request by Ishigh1**
## What is this fixing or adding?
Currently it's not doable to divide an integer by another without it becoming a float. This PR adds floor and ceil to the list of possible operations to fix that issue. 
I thought about adding an operation to change the type, but that would be either vulnerable to code injection or annoying to do for a niche feature

## How was this tested?
I just tested if floor and ceil worked as intended

### CODE REVIEW

**Comment by ThePhar** [comment]
Rather than a `floor_div` function, why not add generic floor and ceil operations?

Then you do the "div" operation and finish with a floor operation as you pass in a list of operations to do in order. Then it can also be useful for other operations that may have float results but we want to remove the decimal somehow.

**Comment by Ishigh1** [comment]
That's also an idea, I'm not against it
I added both of them then will remove either the floor/ceil or div depending on feedback (also I reordered the operations to match the doc because it was bothering me)

**Comment by ThePhar** [comment]
Yeah, if we're going to add `floor` and `ceil`, then we can remove `floor_div` as it can be done with two `DataStorageOperation` objects. I'll wait and see if another core dev disagrees however.

**Comment by Jarno458** [comment]
I agree separated floor and ceil operations would be best, just like other operations it can be chained.
and we can remove floor_dev

**Comment by Jarno458** [comment]
an oddity would be that floor and ceil dont use the operator value, but the same is true for the default operation

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
