### PR TITLE
Core: "Fix" Priority Fill

### PR DESCRIPTION
**Pull request by NewSoupVi**
Read the related issue: https://github.com/ArchipelagoMW/Archipelago/issues/3467

### CODE REVIEW

**Comment by korydondzila** [comment]
Really would like to see this get in, not just because the Shivers option we want to add... but seeing as 5.0 added the slew of options and group being priority locations... this might be important for anyone using those?

I mean like if I do this, this should be exactly what the option would be, which should run into the exact same issue we had with failed gens.
Screenshot 2024-07-13 at 20 39 44

**Review by korydondzila — APPROVED** [review]
Generated seeds of 100 Shivers games where all Ixupi captures were priority.
On main it fails consistently to place a lot of items.
On this branch it generates successfully.

**Review by Exempt-Medic — APPROVED** [review]
I think the change is fine and it fixes at least two worlds where I encountered generation problems. Tested it with Lingo and Shivers and the problems were removed/resolved.

**Review by Berserker66 — APPROVED** [review]
Still has conflicts to sort out though.

**Pull request merged**
