### PR TITLE
Options: introduce SpecialRange

### PR DESCRIPTION
**Pull request by Berserker66**
Allows Ranges with special named values in a cutoff section.
Could use WebHost menu integration.

Might be possible to make it a cross-child of Choice and Range, but that attempt turned out very messy, so I opted for this solution.

### CODE REVIEW

**Comment by beauxq** [comment]
I was hoping for a special label that would appear on the web interface at the top of the range, rather than at the bottom.

(Because the special label I was thinking of "Infinity" makes more sense at the top.)

I'm just hoping that when the web interface for this is implemented, that will be considered, since this code assumes that the special labels are at the bottom.

The web interface might be implemented in such a way that it doesn't make a difference...

**Comment by LegendaryLinux** [comment]
@beauxq The plan for the player-settings page is to include a <select> element with all the custom names and an extra "custom" option. If the user chooses a specified name, the range option will be set to the appropriate value. If the user moved the range option, the <select> input will be changed to "custom". The weighted-settings page will be implemented slightly differently.

**Comment by beauxq** [comment]
That sounds good.

I'm wondering: Will the number still be displayed when a named option is selected?

In the HK examples here from Berserker, and in my "infinity" example, the range numbers for the special options have no meaning to the end user and are just an implementation detail.

It's not a big deal if they are displayed, and for some other examples, the numbers might have meaning to the end user.

**Comment by LegendaryLinux** [comment]
Because both a `select` and a `range` input will be present for all `SpecialRange` options, the custom name and the associated range value will both be displayed.

**Review by LegendaryLinux — APPROVED** [review]

**Pull request merged**
