### PR TITLE
Docs: update Pokemon R/B spanish guide

### PR DESCRIPTION
**Pull request by ShinyNT**
## What is this fixing or adding?
this is updating the pokemon r/b spanish guide, which became a bit obsolete after the 0.4.4 release
essentially I updated the sections about bizhawk client and removed the client chose part on the installation step, so now the guide looks alike with the english one

## How was this tested?
by me translating the outdated parts and comparing it with the english guide

### CODE REVIEW

**Review by nicholassaylor — APPROVED** [review]
Changes look good. Read through and nothing stuck out, corroborated by a quick Google Translate to confirm my understanding. Information is still up-to-date.

**Review by eudaimonistic — APPROVED** [review]
Spanish isn't my first language, but even passable Spanish shows that these changes bring the guide in line with more recent Archipelago versions, namely with the inclusion of Bizhawk Client, the deprecation of Pokemon Client, and the change to use the Bizhawk connector lua.  These changes will immediately reduce the number of tech support requests we get from the outdated guide.

As for the quality of the Spanish, I'm able to read it without being 100% fluent.  Future adjustments could be made if there's imprecision, but the guide appears to properly instruct users how to setup Archipelago for patching the game, how to play single player without server functions (if desired), and how to connect to a multiworld server.

**Comment by NewSoupVi** [comment]
Confused why @Alchav was never pinged for this. I'm down to merge this if it's wanted from both sides.

**Comment by NewSoupVi** [comment]
Oh, this ping was probably not warranted since this is an *update* to an already existing doc. My bad.

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
