### PR TITLE
SC2: Changed client to ignore removed objectives and fixed two missions from not seeing added missions

### PR DESCRIPTION
**Pull request by TheCondor07**
## What is this fixing or adding?
If an objective is removed from the game, the ID isn't overridden and instead just skipped over to allow for backwards compatibility.  This causes issues when the game tries to read those locations in order to check what objectives a mission has.  This has been fixed by checking for unknown locations and skipping over them when checking for unfinished locations for a mission.

As for Safe Haven and Haven's Fall not showing their new locations, a simple update to the mission table was all that was required to fix that.

## How was this tested?
Starting a new seed, checking that the locations table was still properly calculating mission objectives properly, then by taking a seed that had the issue with Moebius Factor's objectives and making sure they properly fixed the issue.

## If this makes graphical changes, please attach screenshots.
Before:
image
After:
image

### CODE REVIEW

**Comment by Berserker66** [comment]
Moebius is still listed as 9 objectives in the table.
Instead of [:16] == text one can do str.startswith(other_str)

**Comment by TheCondor07** [comment]
> Moebius is still listed as 9 objectives in the table.

So with this change, the 9 objectives more mark 'The last objective this mission has ends with the ID 9' rather then this mission has 9 straight objectives.  It only looks for 7 objectives in the mission now because ID 1 and 2 are 'Unknown locations'.  

> Instead of [:16] == text one can do str.startswith(other_str)

Copy, changing.

**Comment by Berserker66** [comment]
Pretty sure you still need to set the minimum client requirement to 0.3.5 as the old client looks to be not compatible anymore. What happens if you use a 0.3.5 client on a 0.3.4 multiworld?

**Comment by TheCondor07** [comment]
Closed because of: https://github.com/ArchipelagoMW/Archipelago/pull/967

**Pull request closed without merging**
