### PR TITLE
FF1: fix PrintJSON assuming type is always given

### PR DESCRIPTION
**Pull request by Berserker66**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
a crash on handling on_package

## How was this tested?
wasn't

### CODE REVIEW

**Comment by Alchav** [comment]
I attempted this same change to Pokemon Client (where I had copied this code from ff1 client) and ran into other crashes in this code block. I seemed to have fixed it by removing the whole section (print json is handled by common client?)

**Comment by black-sliver** [comment]
the rest of that block
```python
            item = args['item']
            receiving_player_id = args['receiving']
            receiving_player_name = self.player_names[receiving_player_id]
            sending_player_id = item.player
            sending_player_name = self.player_names[item.player]
```
would definitely crash as well.

> I seemed to have fixed it by removing the whole section (print json is handled by common client?)

Have you tried `!countdown` and text messages for good measure?

**Comment by Alchav** [comment]
> the rest of that block
> 
> ```python
>             item = args['item']
>             receiving_player_id = args['receiving']
>             receiving_player_name = self.player_names[receiving_player_id]
>             sending_player_id = item.player
>             sending_player_name = self.player_names[item.player]
> ```
> 
> would definitely crash as well.
> 
> > I seemed to have fixed it by removing the whole section (print json is handled by common client?)
> 
> Have you tried `!countdown` and chat messages and seen output?

There was a countdown and text chat occurring during the beta test tonight, seemed fine

**Comment by Berserker66** [comment]
@jtoyoda as this is affecting your code, input would be appreciated.

**Comment by jtoyoda** [comment]
> @jtoyoda as this is affecting your code, input would be appreciated.

This looks like it is replacing an unintentional hack with the fully supported way of handling it. Looks good to me. My only question is if you would suggest adding in additional messages that are "relevant"

**Comment by Berserker66** [comment]
These are on-screen in the emulator view, right? I might even suggest cutting down the relevancy to contains a send that concerns this slot to keep the spam low.

**Comment by jtoyoda** [comment]
Yeah that is correct. I think it would be better to do that. Is there an officially supported way of doing that at this time? Are you okay to make that change in here?

**Comment by Berserker66** [comment]
I'd just copy how the SC2 client does it, as it's the same way there, it's an ingame display of related data.

**Comment by Berserker66** [comment]
Alright, did that. Would be nice if someone could playtest this and report back.

**Comment by Berserker66** [comment]
@jtoyoda "Salarius" did some testing and apparently some thing are broken. In discord the report starts at https://discord.com/channels/731205301247803413/731214280439103580/1017202536459014164
As I don't really know the exact manner of breakage and expected behaviour it would be good if someone who does could look into it.

**Comment by jtoyoda** [comment]
> @jtoyoda "Salarius" did some testing and apparently some thing are broken. In discord the report starts at https://discord.com/channels/731205301247803413/731214280439103580/1017202536459014164 As I don't really know the exact manner of breakage and expected behaviour it would be good if someone who does could look into it.

I will take a look at it tomorrow night. Unfortunately I am out tonight.

**Pull request closed without merging**
