### PR TITLE
Lua: Further centralize code, fix Bizhawk 2.9

### PR DESCRIPTION
**Pull request by zig-for**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
* Fixes the socket library for bizhawk 2.9/lua 5.4 by including another one in parallel
* Fixes lua 5.4 support by making socket.lua into a "modern" module (the `module` keyword is gone)
* Adds the linux version and 32 bit windows socket dlls because why not
* Merges common functions into `common.lua` - the only functional change of this should be that:
  * Some things that were locals are globals now - this can be changed, I just was lazy and it likely doesn't matter
  * `drawText` now uses middle/bottom for all prints - feel free to do what you like with that change

## How was this tested?
I haven't tested this at all beyond making sure pokemon connects on 2.8 and 2.9 - I don't have the other games installed.

### CODE REVIEW

**Comment by Berserker66** [comment]
Would be nice if the maintainers would test nothing got broken by this, such as @espeon65536 @Alchav @Rosalie-A @t3hf1gm3nt @JusticePS 

Also pinging @black-sliver for Linux testing.

**Comment by zig-for** [comment]
Yeah, would really appreciate it!

**Comment by JusticePS** [comment]
Adventure seems to be working fine running from source with the 2.8 Bizhawk (Win10 x64).  I'll try to find time to try 2.9 and a built client later tonight.

**Comment by t3hf1gm3nt** [comment]
@zig-for well connector-tloz.lua is broken. wont work on either bizhawk 2.8 or 2.9. get the following error. 

NLua.Exceptions.LuaScriptException: .\socket.lua:51: The specified module could not be found.

i don't know enough about lua to know what's happening, and @Rosalie-A did basically everything on the connector lua anyway. have fun fixing (or yelling at me about doing something that i didn't do to make it work).

**Comment by JusticePS** [comment]
If there's supposed to be dlls in the lua/x64 and lua/x86 folders already, they are missing.

**Comment by t3hf1gm3nt** [comment]
adding the sockets didn't fully fix TLOZ. got some new errors this time. first on 2.8:

NLua.Exceptions.LuaScriptException: .\common.lua:2: bad argument #1 to 'pairs' (table expected, got nil)

and 2.9:

NLua.Exceptions.LuaScriptException: .\common.lua:2: bad argument #1 to 'for iterator' (table expected, got nil)

**Review by t3hf1gm3nt — APPROVED** [review]
for the sake of recordkeeping, a lot of the previous commits were from discussions on the discord. have successfully completed a full run of TLOZ with these commits (about 2/3's of the game on 2.8 and the final stretch on 2.9) with no issues. giving it my stamp of approval for the TLOZ changes at least

**Comment by JusticePS** [comment]
BizHawk 2.9 works for a few seconds to a couple minutes for Adventure and then silently crashes, but 2.8 seems to be alright now.

**Review by JusticePS — APPROVED** [review]
The new dll fixes my crashes and it generally works.  I'll need to submit a one-line PR once this is merged to fix a bug in my code that isn't very significant in 2.8 but throws in 2.9.

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
