### PR TITLE
WebHost: fix filename rename in flask update

### PR DESCRIPTION
**Pull request by Berserker66**

### CODE REVIEW

**Review by black-sliver — COMMENTED** [review]
Do we need a new flask>= in the requirements, or is the current == broken and i failed when testing?

**Comment by Berserker66** [comment]
The new name was available since 2.1.0; we list 2.1.3 as our requirement. 2.2.0 seems to have removed the old keyword. No warnings were ever emitted to my knowledge, so unless we start actively reading changelogs of dependencies this was kind of unavoidable.

**Review by alwaysintreble — APPROVED** [review]
I tested it on minimum required flask version already and it works fine.

**Review by black-sliver — APPROVED** [review]
Already rolled out

**Pull request merged**
