### PR TITLE
WebHost: Fix Named Range displays on Player Options page

### PR DESCRIPTION
**Pull request by NewSoupVi**
As with my other two WebHost PRs, I have no idea if this is "structurally" the best fix.

Note: Just telling worlds to change the option names in `special_range_names` to what they want **does not work**. If any of the names in there contain capital letters, your yaml will never generate (unless you use the numeric values instead)

Before:

image

After:

image

### CODE REVIEW

**Review by Jouramie — COMMENTED** [review]
Tho I do not disagree with the `title` part, I think the underscores in the special ranges are just a Stardew thing. Specifically with the `Chefsanity` option, since it was converted to a special range in 5.x.x, and the option names copied and pasted in the special ranges.

Also, this change should probably be applied as well to the weighted options

image

**Comment by NewSoupVi** [comment]
Oh, you're saying this is actually intentional on Stardew's part? I thought this was a bug

If that's the case, I will just close this

**Comment by NewSoupVi** [comment]
Confirmed that this is not a bug and Stardew just chose to have its names like this

**Comment by NewSoupVi** [comment]
Reopening because my suggested world-side fix **doesn't work**

If you have capital letters in `special_range_names`, your yamls using those option names will never generate.

**Comment by NewSoupVi** [comment]
In fact, I just realised the docstring of the NamedRange class says that you can't use upper case letters

So if that is going to be the case, we do at least need the call to `title`, because worlds can't do that part themselves.

**Review by agilbert1412 — APPROVED** [review]

**Comment by NewSoupVi** [comment]
Ok, I think I got everything the way I want it now.

**Review by agilbert1412 — APPROVED** [review]

**Review by LegendaryLinux — APPROVED** [review]

**Pull request merged**
