### PR TITLE
Stardew valley: Update settings presets

### PR DESCRIPTION
**Pull request by agilbert1412**
## What is this fixing or adding?
A few new values for the existing settings fit well into the presets, so I updated them to be more accurate with their intent

## How was this tested?
It's just presets, but I did run unit tests just in case

### CODE REVIEW

**Review by nicholassaylor — APPROVED** [review]
Is basically just shuffling values around
Did not test, but should be fine
LGTM

**Comment by Jouramie** [comment]
Didn't test, but we are unit testing all option pairs, so I'm pretty confident it's fine. 

LGTM

**Review by Jouramie — APPROVED** [review]

**Review by eudaimonistic — APPROVED** [review]
These changes are simple and straightforward.  Most of which emphasize or accentuate the existing presets using better option choices.

LGTM, I would use some of these updated presets as presented.

**Review by silasary — APPROVED** [review]

**Review by benny-dreamly — APPROVED** [review]
lgtm

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
