### PR TITLE
[OC2] Horde Levels Logically Give 1-Star

### PR DESCRIPTION
**Pull request by toasterparty**
## What is this fixing or adding?

In the current client implementation (v1.4.1), there is a bug where horde levels grant up to 3 stars depending on how much health is remaining when completing the level. In vanilla horde levels do not grant stars, so the world implementation does not assume any stars gained on successful completion of horde levels. I've decided to split the difference, and (starting in client v1.5.0) completing a horde level will award one star no matter how much health is remaining.

Players who are slow to update will still be able to beat all seeds (there will be 2 illogical stars they will have the potential of collecting per horde levels), otherwise players will be 1:1 with logic.

## How was this tested?
- `/test/overcooked2/`
- Reading spoiler logs

### CODE REVIEW

**Comment by Berserker66** [comment]
you may want to increment the client sending version to 0.3.7 and then make that the required client version server side, so that people update to the client that gives the extra star.

**Comment by toasterparty** [comment]
@Berserker66 I'm okay with how the version numbers are as is. I don't think this change is worth forcing an update.

**Comment by Berserker66** [comment]
I may be misunderstanding behaviour then, my assumption based on your description is:
older clients add up to 3 stars into inventory
newer client adds 1 star into inventory
logic wise:
horde levels used to give 0 stars
now give 1 star into inventory

I then suggested bumping the required version to make sure users don't get 2 extra stars by running an old version.

**Comment by toasterparty** [comment]
@Berserker66 are you suggesting that I set
`required_client_version` to 0.3.7 and the version reported by my client to the same?

**Comment by Berserker66** [comment]
yes

**Comment by toasterparty** [comment]
@Berserker66 done

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
