### PR TITLE
Core/Webhost: Add a unit test that games don't have presets with illegal randoms

### PR DESCRIPTION
**Pull request by agilbert1412**
## What is this fixing or adding?
Some option types do not support "random" as a value, but they are currently allowed in presets. Picking such a preset causes some under-the-hood problems on the webhost page that makes all presets not work anymore until a reload.

Related conversation: https://discord.com/channels/731205301247803413/731214280439103580/1306366651771388038

This PR does not fix any related problems, but it introduces a unit test that should catch these cases.

Currently, the only offender is Stardew Valley, maintained by @agilbert1412 , so it will need to get fixed before this PR can be merged

Waiting on https://github.com/ArchipelagoMW/Archipelago/pull/4206

## How was this tested?
Ran the test, looked at the failing worlds, they match the observed behavior

### CODE REVIEW

**Comment by alwaysintreble** [comment]
not only is this *way* too specific to justify being its own test, but there's already an existing test to check presets are valid. i.e. that test should be adjusted to fix this oversight rather than completely circumventing it.

**Comment by black-sliver** [comment]
Not sure this is exactly the idea treble has, but putting `walnutsanity: random` into a player yaml will not roll, which means there is no reason to special-case this.

**Comment by alwaysintreble** [comment]
#4208

**Comment by agilbert1412** [comment]
Closing since #4208 was merged

**Pull request closed without merging**
