### PR TITLE
Stardew Valley: Options page documentation improvements

### PR DESCRIPTION
**Pull request by agilbert1412**
## What is this fixing or adding?
1: Fixed a typo (leaning -> learning)
2: Shortened the goal documentation so that the tooltip is more readable (hopefully)

## How was this tested?
Documentation

### CODE REVIEW

**Review by EmilyV99 — APPROVED** [review]
LGTM

**Comment by Witchybun** [comment]
Looks fine to me.

**Review by nicholassaylor — APPROVED** [review]
LGTM, mainly shortening things up

**Comment by Exempt-Medic** [comment]
Some of these option descriptions have questions marks, which makes them read strangely. Some of them much more than others and there are some periods missing from the end of some sentences, but those are out of scope for this change. The actual changes here seem good to me

**Review by Exempt-Medic — APPROVED** [review]

**Review by ThePhar — APPROVED** [review]

**Pull request merged**
