### PR TITLE
add world api documentation

### PR DESCRIPTION
**Pull request by black-sliver**

### CODE REVIEW

**Comment by black-sliver** [comment]
Mostly done, ready for comment.
Still 3 FIXMEs i need feedback for.

**Comment by Berserker66** [comment]
So, uh @Ijwu satisfied?
image

**Comment by black-sliver** [comment]
if i replace your proposal with something else in a commit, they are marked as outdated. i do think this is the way it's supposed to work? is there a "yes, but use this instead"? i did not see it.

do you want me to close all the outdated ones? i can do that, but i did expect you to close them for the thumbs-up and "Whatever you choose is fine by me." one at least

**Comment by Ijwu** [comment]
> marking all discussions you started as resolved did not close the change request. do you want me to re-request the review? i'd be happy to learn how this work flow is supposed to work

Marking them as resolved does not automatically close the change request nor the PR. The point is to indicate to the original commentor what the status of the conversation is. Marking as resolved says "I've taken your feedback and incorporated it or otherwise addressed it.". Not marking anything as resolved does not indicate to me your status.

> if i replace your proposal with something else in a commit, they are marked as outdated. i do think this is the way it's supposed to work? is there a "yes, but use this instead"? i did not see it.
> 
> do you want me to close all the outdated ones? i can do that, but i did expect you to close them for the thumbs-up and "Whatever you choose is fine by me." one at least

There is a button under each suggestion that allows you to automatically take the suggestion and apply it as a commit or "add it to a batch" so you can have multiple suggestions committed at once. It is the whole reason I used the suggestion system.

I expect the person whose last word is necessary to resolve a conversation. That might have been me at times, which I apologize for not doing. I guess I expected you to make use of the suggestion system which was my mistake for not communicating.

Next time I will take a different, and hopefully more clear, approach to delivering feedback. Thanks again for doing this, your contribution is still significant and deeply helpful.

**Comment by Ijwu** [comment]
This is fair. I think things were probably done well enough but the
abundance of suggestions I made was confusing all around. If you replaced a
section with a commit then it makes sense to resolve the conversation,
indicating you've completed that feedback element.

Thanks again.

**Pull request merged**
