### PR TITLE
Tests: add a test that worlds have their own tests

### PR DESCRIPTION
**Pull request by alwaysintreble**
## What is this fixing or adding?
Tests

## How was this tested?
Tests

### CODE REVIEW

**Comment by Jarno458** [comment]
Yeah let's not do this, forcing the existence of texts does not create good quality tests

**Comment by alwaysintreble** [comment]
I would much rather people write "bad quality" tests than no tests at all.

**Comment by Jarno458** [comment]
Low quality test make your code hard to maintain

**Review by toasterparty — APPROVED** [review]

**Review by black-sliver — APPROVED** [review]
I'll give it a +1

We had enough problems to warrant more tests, and I believe simple world tests can quickly be written with the `WorldTestBase`.

I'll let another maintainer press merge though, so I don't take the blame alone.

**Comment by Joethepic** [comment]
I personally don’t think this will be the best of ideas. Due to if a world maintainer doesn’t have a lot of knowledge on tests their tests might not even do what they think it will or do nothing at all.

**Comment by alwaysintreble** [comment]
https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/contributing.md

**Comment by black-sliver** [comment]
> I personally don’t think this is the best of ideas. Due to if a world maintainer doesn’t have a lot of knowledge on tests their tests might not even do what they think it will or do nothing at all.

If you managed to understand how to write (or properly copy & paste) a world, you'll probably also be able to write (or copy & paste) something like worlds/soe/test, so I don't think that is a good reason to reject it.

As I said in discord, the base tests will not be able to know which of your options might change layout or rules, so having sanity checks for all major options ensures that a change to one feature will not break another - this also includes core not breaking your world.

**Comment by Jarno458** [comment]
Surely there is value in having test, but forcing them is not the way. World maintainers need to be in charge of thier own world and add the tests they seem fit

I work at a company where they enforced a certain percentage of test coverage years ago, now that old code is super hard to fix any. As many meaningless tests will fail, it makes to code harder to edit and update. Especially as some tests start failing and you have no idea what they are even testing

**Comment by Jarno458** [comment]
I mean this test might seen all innocent, but we all know where this is heading, you make 1 small change to your world and it gets rejected until you add a test for it, that's super demoralizing

**Comment by black-sliver** [comment]
> Surely there is value in having test, but forcing them is not the way.

The readme (now contributing) always stated that logic should be covered by tests.

> World maintainers need to be in charge of thier own world

AP is still a complete package. I don't think this is necessary because people should be forced to get a certain test coverage i think it is necessary because almost nobody writes *any* tests for their worlds at all.

> where they enforced a certain percentage of test coverage years ago

We don't.

**Comment by Berserker66** [comment]
While I agree tests are generally good and we can use more of them, by enforcing it like this all you get is someone writing a little stub that satisfies the existence requirement and every lazy person copies it, achieving nothing.
So I think we need to figure out a better way to encourage more tests.

**Comment by black-sliver** [comment]
Not sure how to *encourage* more tests if world maintainers claim it's not required, even though core can't test some of their options. Any suggestions?

**Comment by Gaelan** [comment]
"It's not required, but if core changes and it doesn't break your tests, it's your problem to notice and fix it?"

**Comment by Gaelan** [comment]
Also worth noting that the people you're trying to get the attention of won't be running tests anyway - so this won't come up until they make a PR and CI fails, at which point a human reviewer could point out the same thing.

**Comment by black-sliver** [comment]
> it's your problem to notice and fix it

Broken worlds, the need of hotfix and unbeatable multis do not just concern the world maintainer, so it's not just their problem.

> so this won't come up until they make a PR and CI fails, at which point a human reviewer could point out the same thing.

A red X is a good indicator that it shouldn't be merged yet, and not requiring human input is also faster most of the time.

**Comment by t3hf1gm3nt** [comment]
> While I agree tests are generally good and we can use more of them, by enforcing it like this all you get is someone writing a little stub that satisfies the existence requirement and every lazy person copies it, achieving nothing. So I think we need to figure out a better way to encourage more tests.

honestly: this sums up my feelings on the matter. if you want tests: you need to do something better than just seeing that a test exists. as is: this is just going to have maintainers do exactly what Berserker said: write a dummy test that satisfies the assert that a test exists. 
forcing a test with a test does nothing. my suggestion would be to add something to the docs (either adding games or world api. perhapes even a brand new doc?) that explains why creating tests for your world implementation is a good idea. at the very least, something about writing a test for your worlds logic with an example would probably be good.

**Comment by alwaysintreble** [comment]
Docs update pr is already done separate from this since I figured this one would be more controversial. I'm open to better ideas but we can't exactly force people to write thorough tests only promote them and force the bare minimum.

**Comment by black-sliver** [comment]
> if you want tests: you need to do something better than just seeing that a test exists

When reviewing we can detect `return True`-tests., getting that red X might speed up stuff.

> forcing a test with a test does nothing. my suggestion would be to add something to the docs

we already have two maintainers that are not willing to write tests. what is a doc update gonna change if the readme *always* said that we require tests for logic?

**Comment by t3hf1gm3nt** [comment]
> When reviewing we can detect `return True`-tests., getting that red X might speed up stuff.
Like Berserker already brought up: that will just lead to people writing a code stub that satisfies that instead of writing proper tests

> we already have two maintainers that are not willing to write tests. what is a doc update gonna change if the readme _always_ said that we require tests for logic?
The doc update will at least outline WHAT we want with tests

Basically, this in it's current form only looks to see that a file exists. To get what you actually want from this will require a more in depth test method. Maybe creating some sort of generalized skeleton test with definitions of what we want devs to test for (i.e. logic) and asserting that the definitions for those are written/return what we want from them
How you generalize that, I have no idea. But all this is gonna do currently is going to result in:

1) Dev writes a dummy file to satisfy the test
2) when reviewers go over the PR, see that it's a dummy test and either let it pass or demand something more, making this test moot

This needs more time in the hopper and more time to think things out on what we actually want from tests

**Comment by Berserker66** [comment]
An example of what could be done, instead of checking for existance, is a certain % of coverage.

**Comment by black-sliver** [comment]
I thought we didn't want to have a minimum coverage?
Anyway, I see two problems with that
- i wouldn't know how to split coverage into base tests and world tests (we would want to check the coverage% of the world tests?)
- if base tests cover most of it, an extra test would not give a big numeric delta, but the extra test might be for a secondary goal, which could break independently

**Comment by Berserker66** [comment]
to 1 and sort of 2: if the base tests already cover most if not all of the world, that would indicate that the world is doing very little to nothing special, so it also has nothing special that needs testing

Having thought some more about it, I think we have an opportunity with the apworld manager in the future, we could tag worlds as having been officially approved, tag them with "has self-tests", having at least some x% coverage and other such "badges".

**Pull request closed without merging**
