### PR TITLE
Docs, Various Games: Add Unique Local Commands to Game Page

### PR DESCRIPTION
**Pull request by nicholassaylor**
## What is this fixing or adding?
Adds the commands unique to various clients to the appropriate game page.
This PR is in response to the discussion on #2213 concerning where these client commands should be documented.

Commands were pulled from their respective client python files. If any were missed, please let me know so that I can add them.

Additionally, it might be in our interest to require that world maintainers include these commands to their game page. This is not enforced in this PR, but I figured this would be a good place to spark that discussion.

Affected Games and CodeOwners:

- [ ] ChecksFinder @jonloveslegos 
- [x] Final Fantasy 1 @jtoyoda
- [x] The Legend of Zelda @Rosalie-A @t3hf1gm3nt 
- [ ] Megaman Battle Network 3 @digiholic 
- [ ] Ocarina of Time @espeon65536 
- [ ] Pokemon Red and Blue @Alchav 
- [ ] Starcraft 2 Wings of Liberty @Ziktofel
- [ ] Undertale @jonloveslegos 
- [x] Wargroove @FlySniper 
- [x] Zillion @beauxq 

## How was this tested?
Was not, doc change

### CODE REVIEW

**Review by t3hf1gm3nt — APPROVED** [review]
TLOZ section LGTM

**Review by beauxq — APPROVED** [review]
Zillion section lgtm

**Review by FlySniper — APPROVED** [review]
Wargroove is approved.

**Comment by LegendaryLinux** [comment]
Markdown changes in general look okay. Will wait a while for affected world maintainers to respond.

**Comment by Bicoloursnake** [comment]
Sorry to add more to this list, but StarCraft 2 has several unique commands missing from this list. Their implementation can be found at `worlds/sc2wol/Client.py` and how their current descriptions can be found in the image below.
image

**Comment by nicholassaylor** [comment]
> Sorry to add more to this list, but StarCraft 2 has several unique commands missing from this list. Their implementation can be found at `worlds/sc2wol/Client.py` and how their current descriptions can be found in the image below. image

Thank you for bringing this up. I recognized that I would be missing some clients since not all of them use the CommonClient. I have added these commands in 5396b564a3366c2d84e9f908947641572274b5f4

**Comment by LegendaryLinux** [comment]
At this point, I think everyone who is going to give an approval will. I'll leave my approval here, and if nobody has any objections before I stumble through this PR again in a week or so, I'll merge.

**Review by LegendaryLinux — APPROVED** [review]

**Pull request merged**
