### PR TITLE
Protocol: Improve machine-readability of prints

### PR DESCRIPTION
**Pull request by recklesscoder**
## The Problem
Various pieces of information are sent only as `PrintJSON` packets. Bots and clients alike may be tempted to parse the human-readable messages to be able to react to specific messages, while becoming reliant on the server not changing the way it formats certain messages.

For example, a bot bridging messages to an external chat room may want to suppress the tutorial message which asks the reader to type `/help` for more information.

### Detecting echoed chat messages
Another example manifestation of this problem are games with native chat systems, such as Minecraft and Factorio. In-game chat messages sent by players are typically not prevented from entering and being displayed by the native chat system. This means that chat messages that are bridged to the Archipelago server and subsequently echoed back in `PrintJSON` packets will appear twice. The solution currently employed is clients detecting these echoed messages and filtering them out, but this filtering currently has to rely on heuristics and string comparisons. If the server for some reason slightly changed the way it formatted username, alias and content, the filtering would break.

## What is this fixing or adding?
Much like how some `PrintJSON` packets are already being annotated as being of type `ItemSend`, `Hint` or `Countdown`, this PR aims to add types to all other `PrintJSON` messages. Where applicable the player causing the message is identified by their team and slot IDs. This allows programmatically and reliably identifying which player a chat message originated from, or which player just reached their goal, for example.

### Compatibility
This change merely adds fields to existing packets. Since the protocol specification already states that `PrintJSON` packets with unknown types are to be tolerated and displayed as normal, no existing clients should break. Updated clients connecting to updated servers can choose to make use of any subset of the newly available information.

## How was this tested?
Mildly. I ran the updated server, had a few 0.3.7 clients (Subnautica, SM64, Minecraft, SC2WoL) connect, get a check and receive/send chat. Everything seemed to work fine.
I also connected with a custom client that prints the raw received packets to confirm that the new types and fields were in fact being sent.

### Aren't some of those `PrintJSON` types redundant?
* The reason that one might not want to merge ItemCheat into ItemSend is that it would require introducing a breaking change to ItemSend: so far it was assumed that all ItemSends a client receives pertain to that client's team, which isn't always the case with ItemCheat notifications. Hence, old clients would display a wrong recipient. (One obvious but probably undesirable alternative would be to simply not broadcast ItemCheats beyond the affected team.)
* ServerChat could be merged into Chat if we defined a team ID that represents the server. I don't think there is a precedent for this, but one could use team ID `-1`. (_Slot_ ID `0` has already been defined to refer to the server.)

### Shouldn't each of these `PrintJSON` sub-types be its own packet type?
One could certainly look at it that way, but at their core these packets still share the property that they carry a simple human-readable message that clients can fall back to. Moving these these prints to their own packet types would cause a lot of breaking changes and make implementing a game client capable of displaying all these kinds of messages a lot more work.

I would say that the intention of `PrintJSON` packets is to convey ephemeral informational events. These packets should not dictate a change in protocol or client state and should be completely ignorable.

### Additional Overhead
These changes roughly double the size of some packets. However, considering that the most common `PrintJSON` type by far, ItemSend, is unaffected (as it is already fully machine-readable), the impact on network traffic should be negligible. Further, even with this additional overhead, all `PrintJSON` packets should easily remain below typical network MTUs.

### Alternative solution to echoed chat messages
We may want to deploy a different solution to the echo problem described above, namely a dedicated feature allowing clients to opt out of echoes of their own chat messages. This would have the advantage of providing the debatably useful feature of allowing multiple players connecting to the same slot (playing "co-op") to chat to each other and see each other's chat messages.

### CODE REVIEW

**Comment by Jarno458** [comment]
i expect quite some merge conflicts with #1364 lets see who gets merged first and get lucky

**Comment by Jarno458** [comment]
I like how you added types for join and leave messages, this was requested way back in #812

**Comment by Berserker66** [comment]
So, which of the two is preferred, or how do we proceed?

**Comment by recklesscoder** [comment]
> So, which of the two is preferred, or how do we proceed?

I don't think there exists any semantic conflict between this and #1364. However, if both are accepted, some manual merging will certainly have to be done. I don't mind doing that, so feel free to merge #1364 into main first.

In my eyes, proceeding for this PR mainly means collecting more feedback/opinions.

---
Unrelated: I noticed that I neglected to provide player chat message payloads in a separate field, which would probably benefit any conceivable chat bot, so I added that just now.

**Comment by Jarno458** [comment]
well it seems my branch was the lucky one to get merged first, so there are now conflicts here, feel free to ping me on discord if you have any questions about my changes

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
