### PR TITLE
[Yoshi's Island] Minor Fixes

### PR DESCRIPTION
**Pull request by PinkSwitch**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
-Changed '10-Up' classification to Useful
-Fixed option typo from 'bosses_guranteed' to 'bosses_guaranteed'

## How was this tested?
I generated after changing them to make sure they worked.

### CODE REVIEW

**Review by Exempt-Medic — APPROVED** [review]
Changes LGTM. Merged into `main` and it generates. Only other instance of "guranteed" is in [CV64](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/cv64/docs/obscure_checks.md?plain=1#L30) which is outside the scope of this

**Comment by PinkSwitch** [comment]
Personal comment, 10-Ups were always supposed to be classed as useful, it seems when I was refactoring the classification assignment, they accidentally got marked as filler and slipped past my notice.

**Review by ScipioWright — CHANGES_REQUESTED** [review]
Delete the apyi file you accidentally attached to this PR

**Review by ScipioWright — APPROVED** [review]
Looks fine, other than that extra file that shouldn't be in the PR

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
