### PR TITLE
Core: skip second sanity check when pushing an item into a location (-O)

### PR DESCRIPTION
**Pull request by Berserker66**
This falls under somewhat spicy optimization

### CODE REVIEW

**Comment by black-sliver** [comment]
I feel like this could be written like so
```python
    def push_item(self, location: Location, item: Item, collect: bool = True):
        if __debug__ and not location.can_fill(self.state, item, False):
            raise RuntimeError('Cannot assign item %s to location %s.' % (item, location))
        location.item = item
        item.location = location
        item.world = self  # try to not have this here anymore
        if collect:
            self.state.collect(item, location.event, location)

        logging.debug('Placed %s at %s', item, location)
```
for readability, but i have no idea what the performance difference would be

**Comment by Berserker66** [comment]
I suspect the performance difference would be minimal.

**Comment by Jarno458** [comment]
This is the kind of code that creates a `Huh? it works on my pc`

**Review by black-sliver — APPROVED** [review]
Lgtm. The speedup for an actual 500-item-multiworld with playthrough is in noise range for me though.

Another thing: some people have been complaining about how assert works (again), so we may want to keep an eye out for proposals to change assert :/

**Pull request merged**
