### PR TITLE
Core: Launcher: can drag-and-drop patch on Launcher window

### PR DESCRIPTION
**Pull request by beauxq**
## What is this fixing or adding?

Many people come to discord for help when they try dragging their patch file onto the window, instead of dragging it onto the executable.

(This is mostly for unsupported worlds, so there is no file-type association.)

So let's support dragging the patch file onto the window.

(I've seen the problem more with people dragging patches into the `SNIClient` window. Maybe I'll add this to `SNIClient` in a different PR later.)

## How was this tested?

I generated a game with an unsupported SNES game, then opened the `Launcher` window and dragged the patch file into the `Launcher` window. It patched the rom and opened up `SNIClient`.

### CODE REVIEW

**Comment by Zunawe** [comment]
For the record, it's entirely possible for unsupported worlds to associate extensions with components, including with both BizHawkClient and SNIClient. I'm not arguing against this change, but in my opinion the instruction to players should already be to use the Open Patch button in the launcher or to associate the patch file extension with the launcher, since drag and drop has these clarity problems.

**Comment by black-sliver** [comment]
We use the same thing (drag file onto main window) in a lot of applications these days, and even a lot of websites allow that, so I am all for it.

Is there any need for more feedback to the user? Is it clear enough if only the mouse cursor changes to "accept drop" (or does not change to "deny drop")? Should we only accept drop if it can be identified? (Is this even possible with kivy?)

**Comment by beauxq** [comment]
> For the record, it's entirely possible for unsupported worlds to associate extensions with components, including with both BizHawkClient and SNIClient.

Yes, the association that I was referring to is the Windows OS association that is made by the installer automatically for supported worlds, but is not made automatically for unsupported worlds.

> the instruction to players should already be to use the Open Patch button in the launcher or to associate the patch file extension with the launcher, since drag and drop has these clarity problems.

In my opinion, these are both inferior user experiences - having to navigate to find a file in the window that opens up after pressing the "Open Patch" button (when the player is often already looking at the file in a different window) - or having to manually create a Windows file association.
I think being able to drag and drop the file onto something is a better user experience than both of these.

**Comment by beauxq** [comment]
> Is there any need for more feedback to the user? Is it clear enough if only the mouse cursor changes to "accept drop" (or does not change to "deny drop")? Should we only accept drop if it can be identified? (Is this even possible with kivy?)

I don't see a kivy interface to change the indication for whether the file drop will succeed. There might be a way to do it, but I don't see a big need for it. Maybe it could be added in the future.

**Review by black-sliver — APPROVED** [review]
Thanks!

While I think this could use some user feedback (patching may take a while, opening the client may take a while), it works as advertised.

**Pull request merged**
