### PR TITLE
Fill: remove sweep_for_events(key_only=True)

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
removes the LttP locked key sweep, which was used to lump together key use in dungeons into a single sphere in playthrough and progression balancing for LttP only.

## How was this tested?
A bit of Generate and unittests.

### CODE REVIEW

**Comment by Alchav** [comment]
Is that why all the keys were showing up in spheres together in my Bombless Start branch? Good I thought something was horribly broken

**Comment by black-sliver** [comment]
What is the reason this existed - or better, will removal have negative effects for lttp players?

**Comment by Berserker66** [comment]
The reason this was invented was to  improve chances that progression balancing leaves items in dungeons, or places them into dungeons. We could offer a generic way of doing that, by allowing events that "skip sphere" I suppose. But so far nobody ever requested that to my knowledge.

**Comment by Berserker66** [comment]
The data point would certainly be interesting.

**Review by alwaysintreble — APPROVED** [review]
Change LGTM. I'm a bit interested in an API to make certain regions more "progression heavy" but i don't think this was it. it should probably be a region attr instead of a location attr but that would require prog balancing to look at regions so 🤷

**Comment by black-sliver** [comment]
Did you compare seeds? If so, was the balancing noticeably worse than before?

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
