### PR TITLE
Docs: add instructions for installing Dark Souls III on linux

### PR DESCRIPTION
**Pull request by Mojken**
## What is this fixing or adding?
Instructions for how to install the Dark Souls 3 mod on linux

## How was this tested?
It was performed successfully (specifically, on nix-os)

### CODE REVIEW

**Comment by nicholassaylor** [comment]
This will be outdated with #3128 and should probably be closed since it is close to being merged

**Comment by Mojken** [comment]
> This will be outdated with #3128 and should probably be closed since it is close to being merged

Then, perhaps #3128 should provide installation instructions for linux from the get-go? If this had been merged back when, that PR probably would have already done so, rather than just removing it.

**Comment by nicholassaylor** [comment]
#3817 Now covers linux installation under the 3.0.0 release

**Comment by Mojken** [comment]
> #3817 Now covers linux installation under the 3.0.0 release

That's great news!

**Comment by Mojken** [comment]
Closing as it's outdated, replaced by #3817

**Pull request closed without merging**
