### PR TITLE
Add Rogue Legacy to Archipelago

### PR DESCRIPTION
**Pull request by ThePhar**
Here is the layout for basic Rogue Legacy support in Archipelago based from my Rogue Legacy Randomizer client.

**Locations** include:

- All 25 diary locations.
- All 4 bosses.
- All 31 manor upgrades, which replace the vanilla shop-screen.
- Configurable number of chests and fairy chests per zone.

**Items** include:

- Groups of every blueprint and rune. (e.g. Blood Armor Blueprints, Vault Runes, etc.)
- Groups of 5 levels per skill in the game. (e.g. Health Up, Attack Up, Equip Up, etc.)
- Each class unlock and upgrade. (including Traitor class)
- Filler items of gold packs and stat increases if location pool is too large for required items.

**Options** include:

- Starting class and starting gender.
- Ability to toggle needing to buy equipment and paying Charon's toll to enter the castle.
- Increase (or decrease) the gold multiplier for gold drops.
- Change the number of children you can choose from on the Lineage screen after a death.
- Configuring the number of chests and fairy chests per zone.
- Setting new game plus mode to increase enemy level substantially.
- Death link. Would recommend disabling Charon for that though.

### CODE REVIEW

**Comment by ThePhar** [comment]
Cross my fingers, I think the client is ready. Just let me know what other changes need to be made before it gets merged.

**Comment by Berserker66** [comment]
> 

Looks good to me. Squashing it to one commit fine with you?

**Comment by ThePhar** [comment]
Sounds good to me.

**Comment by ThePhar** [comment]
Would help if I didn't forget to add an item to the item pool.

**Comment by Berserker66** [comment]
Thank you!

**Pull request merged**
