### PR TITLE
Pokemon RB: Fix logic for Route 10 Hidden Item Behind Rock Tunnel Entrance Cuttable Tree

### PR DESCRIPTION
**Pull request by remyjette**
This location requires access to hidden items and cut to check.

Also noticed some incorrect parens on this file

### CODE REVIEW

**Comment by ThePhar** [comment]
@Alchav

**Comment by Alchav** [comment]
The vermilion gym logic is resolved in #1963 and the other fix would create a merge conflict so I will just fix it in my PR

**Comment by remyjette** [comment]
Abandoning in favor of adding the fix to #1963

**Comment by Alchav** [comment]
Thank you for bringing this to my attention @remyjette

**Pull request closed without merging**
