### PR TITLE
Adding apostrophe quotes around variables in printed error messages

### PR DESCRIPTION
**Pull request by palex00**
Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
[Saye Hat in Time by Nephalia.txt](https://github.com/user-attachments/files/16934386/Saye.Hat.in.Time.by.Nephalia.txt)
If you generate this erronous YAML [here a txt because of github restrictions] on live you will get this error:

`Exception: Item Magnet Badge from option StartInventory(Umbrella: 1, Badge Pin: 2, Random Cosmetic: 40, Magnet Badge: 1) is not a valid item name from A Hat in Time. Did you mean 'Item Magnet Badge' (70% sure)`

In the YAML the player wrote "Magnet Badge". The real item name is "Item Magnet Badge". Because of missing quotations around the item_name variable in the beginning, "Item Magnet Badge" and "Item 'Magnet Badge'" is indistinguishable and confuse users.

This change is adding apostrophe quotations around all variables in printed error statements, such as Item, Location, Entrance/Exit, Boss and Game names.

## How was this tested?
The offending YAML was generated on a compiled build with the fix and it prints correctly.

## If this makes graphical changes, please attach screenshots.
Before:
```
Uncaught exception
Traceback (most recent call last):
  File "Generate.py", line 192, in main
  File "Generate.py", line 192, in <genexpr>
  File "Generate.py", line 507, in roll_settings
  File "Generate.py", line 445, in handle_option
  File "Options.py", line 80, in verify
  File "Options.py", line 814, in verify
Exception: Item Magnet Badge from option StartInventory(Umbrella: 1, Badge Pin: 2, Random Cosmetic: 40, Magnet Badge: 1) is not a valid item name from A Hat in Time. Did you mean 'Item Magnet Badge' (70% sure)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__startup__.py", line 138, in run
  File "console.py", line 17, in run
  File "Generate.py", line 549, in <module>
  File "Generate.py", line 211, in main
ValueError: File Saye Hat in Time by Nephalia.yaml is invalid. Please fix your yaml.
Traceback (most recent call last):
  File "Generate.py", line 192, in main
  File "Generate.py", line 192, in <genexpr>
  File "Generate.py", line 507, in roll_settings
  File "Generate.py", line 445, in handle_option
  File "Options.py", line 80, in verify
  File "Options.py", line 814, in verify
Exception: Item Magnet Badge from option StartInventory(Umbrella: 1, Badge Pin: 2, Random Cosmetic: 40, Magnet Badge: 1) is not a valid item name from A Hat in Time. Did you mean 'Item Magnet Badge' (70% sure)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__startup__.py", line 138, in run
  File "console.py", line 17, in run
  File "Generate.py", line 549, in <module>
  File "Generate.py", line 211, in main
ValueError: File Saye Hat in Time by Nephalia.yaml is invalid. Please fix your yaml.
Press enter to close.
```

After:

```
Uncaught exception
Traceback (most recent call last):
  File "Generate.py", line 192, in main
  File "Generate.py", line 192, in <genexpr>
  File "Generate.py", line 507, in roll_settings
  File "Generate.py", line 445, in handle_option
  File "Options.py", line 80, in verify
  File "Options.py", line 814, in verify
Exception: Item 'Magnet Badge' from option 'StartInventory(Umbrella: 1, Badge Pin: 2, Random Cosmetic: 40, Magnet Badge: 1)' is not a valid item name from 'A Hat in Time'. Did you mean 'Item Magnet Badge' (70% sure)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__startup__.py", line 138, in run
  File "console.py", line 17, in run
  File "Generate.py", line 549, in <module>
  File "Generate.py", line 211, in main
ValueError: File Saye Hat in Time by Nephalia.yaml is invalid. Please fix your yaml.
Traceback (most recent call last):
  File "Generate.py", line 192, in main
  File "Generate.py", line 192, in <genexpr>
  File "Generate.py", line 507, in roll_settings
  File "Generate.py", line 445, in handle_option
  File "Options.py", line 80, in verify
  File "Options.py", line 814, in verify
Exception: Item 'Magnet Badge' from option 'StartInventory(Umbrella: 1, Badge Pin: 2, Random Cosmetic: 40, Magnet Badge: 1)' is not a valid item name from 'A Hat in Time'. Did you mean 'Item Magnet Badge' (70% sure)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__startup__.py", line 138, in run
  File "console.py", line 17, in run
  File "Generate.py", line 549, in <module>
  File "Generate.py", line 211, in main
ValueError: File Saye Hat in Time by Nephalia.yaml is invalid. Please fix your yaml.
Press enter to close.
```

I apologise for the confusing updating of the plando_en.md. That was for a different PR, I could not get the branch to be reset on Github Web. But as the PR shows, this PR only modifies options.py

### CODE REVIEW

**Comment by qwint** [comment]
errors look like unit tests that check for exact text on these errors, should fix those as well,
else the changes looks reasonable,

purely a code review, no manual/automated tests run on my end

**Comment by Exempt-Medic** [comment]
Stylistically, these should be using double quotes, not single quotes

**Comment by ScipioWright** [comment]
> Stylistically, these should be using double quotes, not single quotes. Although Lufia II is probably fine to be kept as-is since that's consistent with its own styling. That said, you might want to just remove the Lufia II changes entirely or make that a separate PR so the core and world changes can progress at their own rates.

The two changes are completely dependent on each other. If one changes without the others, it'll just be a constant test failure.

**Review by ScipioWright — APPROVED** [review]
Generally looks good to me. I don't have strong opinions on ' vs " here.

**Comment by Exempt-Medic** [comment]
> > Stylistically, these should be using double quotes, not single quotes. Although Lufia II is probably fine to be kept as-is since that's consistent with its own styling. That said, you might want to just remove the Lufia II changes entirely or make that a separate PR so the core and world changes can progress at their own rates.
> 
> The two changes are completely dependent on each other. If one changes without the other, it'll just be a constant test failure.

Oh fun... Honestly baffled that's even possible and that it isn't already crashing because they aren't consistent but 🤷

**Review by qwint — APPROVED** [review]
whoops, forgot to hit the approve button and not just the comment button

my above comment applies

**Comment by ScipioWright** [comment]
Gonna put this on core review now -- I figure core might decide that the world maintainer review isn't super necessary here since it's literally just changing an expected error message in a test.

**Comment by palex00** [comment]
> Stylistically, these should be using double quotes, not single quotes. Although Lufia II is probably fine to be kept as-is since that's consistent with its own styling. That said, you might want to just remove the Lufia II changes entirely or make that a separate PR so the core and world changes can progress at their own rates.

I have been basing this off of the existing quotation of ´Did you mean 'Item Magnet Badge' (70% sure)´ which uses single quotation marks.

**Comment by Exempt-Medic** [comment]
> > Stylistically, these should be using double quotes, not single quotes. Although Lufia II is probably fine to be kept as-is since that's consistent with its own styling. That said, you might want to just remove the Lufia II changes entirely or make that a separate PR so the core and world changes can progress at their own rates.
> 
> I have been basing this off of the existing quotation of `'Did you mean Item Magnet Badge' (70% sure)` which uses single quotation marks.

Yeah that's fair. It really still probably should be doubles, but it's consistent with something that already existed and the whole set can always be changed later in one big swoop

**Comment by Exempt-Medic** [comment]
@el-u

**Review by Exempt-Medic — APPROVED** [review]

**Pull request merged**
