### PR TITLE
Factorio: "improve" default start items

### PR DESCRIPTION
**Pull request by Berserker66**
## What is this fixing or adding?
Makes it less likely that people kill themselves via pollution and gives them some healing items they may not even know about.

## How was this tested?
nope

### CODE REVIEW

**Comment by NewSoupVi** [comment]
Hmm. Did you ever make a decision on whether a progressive military should be and early local item like logistics and automation? I feel like that suggestion was a much more fun & natural way to resolve this, rather than slowing down the early game even more

**Comment by Berserker66** [comment]
Yeah, I don't like it. People can make it happen already via yaml.

**Comment by ReverM** [comment]
Is there any reason why the default amount of drill and furnace has been lowered? Is it to counter possibly polluting too much?

**Review by black-sliver — APPROVED** [review]
> Hmm. Did you ever make a decision on whether a progressive military should be an early local item like logistics and automation?

I think the solution would be to put Military in logic. You only need Military after consuming X items, so putting it early is not a real solution.

Anyway, I always felt the starting inventory was too generous, so approving this.

**Pull request merged**
