### PR TITLE
Fix failing out of priority fill when an item can't place

### PR DESCRIPTION
**Pull request by Alchav**
During the priority fill, if an item is unable to be placed, hold it until the regular fill

### CODE REVIEW

**Comment by Berserker66** [comment]
@wbhumphrey looks like more changes to your changes

**Comment by Alchav** [comment]
I mentioned this on discord but I'll repeat here:

I was trying to configure locations flagged as priority locations to also have item rules and was running into items being picked for placement during the priority fill that could not be placed into any priority location due to the item rules, and this was causing generation failure

**Comment by wbhumphrey** [comment]
I took a slightly different approach to avoid adding an extra flag to the fill_restrictive by essentially allowing it to determine that it has more locations than items. The drawback of my PR is that it potentially spends more time than is necessary filling before failing on an un-fillable seed. I could add additional logic to fail earlier if that is important, but I figured we are working towards avoid failing fills entirely, so this should be more of an (inconsequential) development problem, rather than an actual performance concern.

I also worry that we will eventually run into other issues that are caused by splitting the fill logic across two fill_restrictive steps and we will need to need to reconcile unplaced items/locations in distribute_items_restrictive instead of failing within fill_restrictive. 
 
https://github.com/ArchipelagoMW/Archipelago/pull/252

I'm happy with whichever way want to go, but in either case big thanks to Alchav for identifying and troubleshooting the issue.

**Comment by Alchav** [comment]
Closed as wbhumphrey's alternative solution was merged

**Pull request closed without merging**
