### PR TITLE
Aquaria: Renaming some locations for consistency

### PR DESCRIPTION
**Pull request by tioui**
## What is this fixing or adding?

Some location names did was not consistent with all other location names. So those locations have been renamed.

There is also a new option, but it is useful only to the client. It does not impact the logic.

Also, I removed the DeathLink option to put it in the client.

## How was this tested?

I have generate games with multiple options and have launched the unit tests. Every thing works with no problem.

### CODE REVIEW

**Review by ScipioWright — APPROVED** [review]
Changes look reasonable. Did not check other location names for other names that could be renamed.

**Review by Exempt-Medic — APPROVED** [review]
LGTM, it generates, there are not other instances of these particular names in locations, just `Cathedral right area` being in `regions.py`, but that's fine

**Review by Berserker66 — APPROVED** [review]

**Comment by Berserker66** [comment]
This also includes a new option, which isn't mentioned in the PR description.

**Comment by Exempt-Medic** [comment]
My signal is bad, but I'm just stating here that I am revoking my approval. Several additional changes were made afterwards

**Comment by tioui** [comment]
> This also includes a new option, which isn't mentioned in the PR description.

Oups. Sorry. The new option was add as a subsequent commit. So, I forgot to modify the description. But the option in question does not have any impact on the logic. It is just an information for the client. Also, I removed the DeathLink option after a discussion with @ScipioWright .

**Comment by ScipioWright** [comment]
I think their message was more about "the scope of this PR has changed so I would need to re-review it to give approval again".
Generally, it's recommended to open a separate PR for separate changes, since that makes it easier to review and avoids situations like this.

**Comment by tioui** [comment]
> I think their message was more about "the scope of this PR has changed so I would need to re-review it to give approval again". Generally, it's recommended to open a separate PR for separate changes, since that makes it easier to review and avoids situations like this.

Will know next time.

**Review by ScipioWright — APPROVED** [review]
Reapproving so it's clear that I'm still fine with this

**Review by Exempt-Medic — APPROVED** [review]
The changes LGTM. Can't test any generations for now, but presumably others did. `fill_slot_data` could be changed to use `options.as_dict` and some of the `.value`'s could be removed, but that's outside the scope of this PR.

**Comment by tioui** [comment]
> The changes LGTM. Can't test any generations for now, but presumably others did. `fill_slot_data` could be changed to use `options.as_dict` and some of the `.value`'s could be removed, but that's outside the scope of this PR.

For the fill_slot_data, I am not certain since I add some information in the slot data that are not in the options (ingredient and dishes randomization). For the .value, I will try removing them for a futur PR.

**Review by NewSoupVi — APPROVED** [review]

**Pull request merged**
