### PR TITLE
LADX: Client Fixes

### PR DESCRIPTION
**Pull request by zig-for**
## What is this fixing or adding?
1. Fixes `b''` garbage on RA connection
2. Properly pulls the URL from the .apladx file on start
3. Somewhat gracefully restarts the client loop if the previous connection failed due to bad start error (allows reconnection on bad slot data with correct data)
4. Adds support to client for swapping ROMs! Swapping ROMs no longer results in the client hanging, and should properly disconnect.
5. Adds support for launching the ROM when launching the patch
6. Fixes many many instances of non-async access to the emulator, causing client hangs
7. Fixes instance where bizhawk and client could get out of sync, by (a) disconnecting if response ever doesn't match request and (b) completely resetting the connection on reset
8. ...finally, fixes a bug in bizhawk 2.8 wherein old sockets aren't closed. Thanks, Bizhawk. This should hopefully not cause problems in other games, as I don't think anybody wants forever broken sockets.
 
## How was this tested?
Repeatedly starting, connecting, and disconnecting the client

### CODE REVIEW

**Comment by zig-for** [comment]
Swapping to draft - thought this was ready but wanna check another edge case

**Comment by t3hf1gm3nt** [comment]
since you're working on other client related things: request to add emulator autolaunching after patching. if you need an example, start at line 657 of SNIClient and then also look where the run_game function is used.

**Comment by zig-for** [comment]
Undrafted :)

**Comment by t3hf1gm3nt** [comment]
Did some testing. Can confirm points 2 and 5 work correctly. Unsure how to test points 1 and 3 so did not test those. Point 4, however, has a bit of a hangup with BizHawk. This update can gracefully disconnect on detecting a ROM change correctly...IF the user closes the Lua Console in BizHawk first before doing the ROM change. IF the lua console remains open at all, even if all scripts are stopped and/or removed, this will cause the LADX client to hang and stop responding. Unsure how you want to handle this. If anything, would recommend proper steps for ROM swapping in BizHawk to be noted down somewhere before I would approve this

**Comment by zig-for** [comment]
@t3hf1gm3nt I'll test with Bizhawk and either update the lua or update the client

**Review by t3hf1gm3nt — APPROVED** [review]
Previous comment's concern has now been addressed, so gets the ok from me.

**Comment by zig-for** [comment]
https://github.com/ArchipelagoMW/Archipelago/commit/827444f5a4e065bc310c889892580eb1f97c73cb :(

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
