### PR TITLE
Sonic Adventure 2: Battle Implementation

### PR DESCRIPTION
**Pull request by PoryGone**
Included is the v1.0.0 of the Sonic Adventure 2: Battle Archipelago Randomizer.

The included Setup Doc points to the game-side mod required for use, which can also be found [here](https://github.com/PoryGone/SA2B_Archipelago/releases/tag/v1.0.0).

### CODE REVIEW

**Comment by Berserker66** [comment]
Is squash fine with you?

**Comment by PoryGone** [comment]
> Is squash fine with you?

Yes, that is fine with both of us.

**Review by KonoTyran — CHANGES_REQUESTED** [review]
so we just changed how tutorials are handled, and the now need to be handled in your `__init__.py` as seen in this PR https://github.com/ArchipelagoMW/Archipelago/pull/455
this involves specifying a `WebWorld` for your game (where you can also choose what theme your pages will have on the website)
see https://github.com/ArchipelagoMW/Archipelago/blob/977159e5721b979faef14282de0bf9c592fb235c/worlds/AutoWorld.py#L88 for implementation details

if you have questions about implementation feel free to ask in the AP dev chat on discord

**Comment by PoryGone** [comment]
> so we just changed how tutorials are handled, and the now need to be handled in your `__init__.py` as seen in this PR #455 this involves specifying a `WebWorld` for your game (where you can also choose what theme your pages will have on the website) see
> 
> https://github.com/ArchipelagoMW/Archipelago/blob/977159e5721b979faef14282de0bf9c592fb235c/worlds/AutoWorld.py#L88
> 
> for implementation details
> if you have questions about implementation feel free to ask in the AP dev chat on discord

I believe I have successfully merged against these changes, and the PR should be clear of conflicts again.

**Comment by PoryGone** [comment]
Apologies, I had missed a couple of steps in the new WebHost workflow. Tests should all pass this time.

**Comment by KonoTyran** [comment]
still have the issue with `data_version = 0` where it should be 1 instead.

**Review by KonoTyran — APPROVED** [review]
everything looks good to me. if @Berserker66 has no further inputs then I think we are ready to merge this.

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
