### PR TITLE
SC2: UI update, Relegate No Build Option, and Filler Item Update

### PR DESCRIPTION
**Pull request by TheCondor07**

### CODE REVIEW

**Comment by Berserker66** [comment]
image

**Comment by TheCondor07** [comment]
I litterally just merged with main before submitting, how did there get to be conflict issues....  Checking out.

**Comment by TheCondor07** [comment]
image
I see, working on that.

**Comment by TheCondor07** [comment]
Alright, conflicts should be resolved

**Review by Berserker66 — APPROVED** [review]

**Pull request merged**
